### ISSUE TITLE
RStudio server blank page

### ISSUE THREAD

**Issue by ToniDS** [rocker-org/rocker-versioned2#107]
I've been using rocker/verse for a while now. With the new rstudio, I wanted to update, so I tried pulling rocker/verse. 
I now have the issue that the login screen appears and it seems to work, but then I get a blank page. I tried renaming .rstudio, as well as the rstudio folder. There's nothing in .share. I also renamed all the .Rhistory files, no dice. 
Checked all folder permissions, they all belong to the user I'm logging in as.

Does anyone have an idea what else I could check or what the issue might be?

**Comment by cboettig** [comment]
Sorry for the trouble and thanks for the report.  @ToniDS can you give us a bit more detail?  e.g. are you doing any volume mapping to the host?

**Comment by cboettig** [comment]
p.s. can you test in a private browser tab?  We have seen similar behaviour that arise from browser cache issues...

**Comment by eitsupi** [comment]
I'm closing this issue for lack of information. If you have additional information, please let us know and we can reopen it.
