### ISSUE TITLE
singularity container database error

### ISSUE THREAD

**Issue by mikecuoco** [rocker-org/rocker-versioned2#109]
Using singularity 3.5 on my university's HPC (CentOS Linux 7), I followed the [rocker singularity tutorial](https://www.rocker-project.org/use/singularity/) 

```
singularity pull --name rstudio.simg docker://rocker/rstudio:latest
singularity exec rstudio.simg rserver --www-address=127.0.0.1
```

and got the following error

```
27 Jan 2021 20:45:00 [rserver] ERROR database error 7 (sqlite3_statement_backend::loadOne: attempt to write a readonly 
database) [description: Could not delete expired revoked cookies from the database, description: Could not read revoked 
cookies from the database]; OCCURRED AT virtual rstudio::core::Error 
rstudio::core::database::Connection::execute(rstudio::core::database::Query&, bool*) src/cpp/core/Database.cpp:480; 
LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:729
```

Considering singularity automatically binds my home directory, I tried resetting the following rserver configuration files that are stored there, but got the same error

```
~/.config/rstudio/
~/.local/share/rstudio/
~/.rstudio/
```

**Comment by koetjen** [comment]
This is the same error I receive using the latest version of RStudio in rocker (not at all related to singularity). See #105 

You may want to try rstudio:4.0.2, that still works for me

**Comment by mikecuoco** [comment]
Thank you @koetjen, this solution fixes the issue for me!
