### ISSUE TITLE
using alternate CRAN mirror or installing packages from GitHub

### ISSUE THREAD

**Issue by vinay-swamy** [rocker-org/rocker-versioned2#113]
Hi, I'm using a rocker container inside Singularity. I'd like to be able to connect to an alternate CRAN mirror, or install packages from GitHub with `devtools::install_github` , but it seems the container is only able to get packages from `https://packagemanager.rstudio.com` . How would I go about getting packages outside this location

**Comment by cboettig** [comment]
You haven't really told us how you're going about this, but you should be able to set the mirror in all the usual ways (i.e. just change the value of the `repos` in `options()` (e.g. in an .Rprofile...) or pass a different repo (or multiple repos) to install.packages directly, etc.  We try and set reasonable defaults (e.g. note that using the RStudio mirror will give you binary installations which are much much faster, and they use a CDN so downloads should be pretty fast from most locations) but they can always be overwritten in the standard way.

**Comment by vinay-swamy** [comment]
I'm trying something like `install.packages("ggplot2", repos="https://cran.rstudio.com")` or `devtools::install_github('vinay-swamy/RBedtools')`, and get a message like `cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'` or `Could not resolve host: api.github.com`

**Comment by cboettig** [comment]
Can you visit https://cran.rstudio.com/src/contrib/PACKAGES at all on your machine?  You might want to verify you are not blocked by your firewall.   I cannot reproduce the errors you show.

**Comment by vinay-swamy** [comment]
I can access that link on my machine(For reference, this is an academic HPC). There's even other containers through which I can access that link. I guess more generally, is there anything specific I need to do within a docker file for a container to allow it to connect to different sites? if not, its probably a problem specific to my machine

**Comment by cboettig** [comment]
nothing special, sorry, sounds like a firewall issue to me, see if your sys admin can help?
