### ISSUE TITLE
Create R package for Dockerfile creation

### ISSUE THREAD

**Issue by noamross** [rocker-org/rocker-versioned2#12]
`make_rockerfile(from = ..., modules = ...,  ...)` creates single Rockerfile from arguments whose values are currently in the .json config files.

`make_rockerstack("config.json")` takes a JSON or list and makes a bunch of Rocker files.

Dockerfile metadata is an argument to `make_rockerfile()` that we set in the workflow here.

**Comment by noamross** [comment]
Develop-facing function should also generate a Docker compose file, which will be used with `docker compose build` in the Makefile to order the building of images.

**Comment by noamross** [comment]
`make_rockercompose()` to make docker-compose files to build images in order.

**Comment by noamross** [comment]
Package is here: https://github.com/noamross/rockerbuilder

**Comment by cboettig** [comment]
sticking with the two R scripts in this repo for simplicity instead.
