### ISSUE TITLE
rocker/r-ver:latest seems not to be auto-updated.

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#125]
The rocker/r-ver:4.0.3 was updated but rocker/r-ver:latest image was not updated 4 days ago, is it correct behavior ?

![image](https://user-images.githubusercontent.com/50911393/108586771-df611380-7393-11eb-8b4c-cf5c9467a74d.png)

**Comment by eddelbuettel** [comment]
Updates can happen on automated (i.e. `cron` job) pushes.  New entries may have to made manually.  And the project is a volunteer project ...

**Comment by eitsupi** [comment]
@eddelbuettel Excuse me for not having enough words. What I wanted to say was that "4.0.3" was auto-updated but "latest" didn't seem to be auto-updated.

**Comment by eddelbuettel** [comment]
It may have failed. One would have to look at the build log (which, IIRC, are not 'globally open').  Time permitting, I am sure Carl or Noam will look into.  I updated things over on my side and we have `rocker/r-base`, and from it the official `r-base`, for 4.0.4 both since Tuesday.

**Comment by eitsupi** [comment]
@eddelbuettel Thank you for your response. Also, thank you for your continuous image updates.

I didn't understand that build failures were common or not, so I created this issue.
I hope it's not a big problem.

**Comment by cboettig** [comment]
yeah apologies, should have posted yesterday.  Eventually these will be fully automated again, some of the stack is too large to build on GitHub Actions reliably.
