### ISSUE TITLE
GitHub actions workflow

### ISSUE THREAD

**Issue by noamross** [rocker-org/rocker-versioned2#13]
On commit: (@noamross)
 - Re-compile Dockerfiles, commit back to repo
    - This requires R installed and the `rockerbuild` package (#12)

Nightly: (@cboettig )
 - [ ] (post-release, on master) Ping Docker Hub to build images 
 - [x] (pre-release and post-release) Build images, push to GitHub registry

On successful Dockerfile creation with commit keyword (e.g, `[build images]`) or nightly on branch:
 - Build images, push to GitHub registry (possibly with additional tag)

**Comment by cboettig** [comment]
@noamross we should finish setting up these triggers with cron jobs now that things are a bit more stable?

**Comment by eitsupi** [comment]
Github actions workflows seem working well now.
