### ISSUE TITLE
rocker for databricks ❓ 

### ISSUE THREAD

**Issue by vidarsumo** [rocker-org/rocker-versioned2#131]
Hello,

I'm using Azure Databricks and I would like to be able to the rocker/verse image. However, according to the Databricks team I have to use databricksruntime/rbase. This doesn't seem to be well maintained image and was last updated 2 years ago.

Would it be possible for you to create a rocker/verse image that would work on Azure Databricks?

**Comment by eitsupi** [comment]
I did a little research.
[According to the databricks reference](https://docs.databricks.com/release-notes/runtime/7.6.html#system-environment), the R supported in the latest version of databricks is R 3.6.3, so the latest rocker-versioned2 R >= 4.0.0 images are not match this use.

The databricksruntime/rbase looks like be build form these Dockerfiles.
- minimal(Ubuntu16.04): <https://github.com/databricks/containers/tree/master/ubuntu/minimal>
- R: <https://github.com/databricks/containers/tree/master/ubuntu/R>

How about build your own image with editing these Dockerfiles?
Some people have switched the base image to ubuntu18.04 by themselves. https://github.com/databricks/containers/issues/46

**Comment by eddelbuettel** [comment]
Yes -- layering is good idea and how Docker works well.   And you could use the Rocker images for `r-ubuntu`:  https://hub.docker.com/r/rocker/r-ubuntu/tags?page=1&ordering=last_updated

Or the ones that put [BSPM](https://cran.r-project.org/package=bspm), one demo [here](http://dirk.eddelbuettel.com/blog/2020/08/26#029_introducing_bspm) and more in blog posts in the same corner. Then `install.packages("tidyverse")` automagically pulls binaries without a need for compilation. I use that in CI as described [in this post](http://dirk.eddelbuettel.com/blog/2020/09/26#030_bspm_for_ci).

**Comment by eitsupi** [comment]
@vidarsumo The `databricksruntime/rbase` seemed to be updated a month ago. Do you think this issue has been resolved?

**Comment by eitsupi** [comment]
I think this issue has been resolved, so I close it.
