### ISSUE TITLE
Location of ubuntu:20.04 Dockerfile

### ISSUE THREAD

**Issue by GitHunter0** [rocker-org/rocker-versioned2#132]
Sorry if this is a trivial question, I would post on Stackoverflow but there was no `rocker` tag there.

[Dockerfile_r-ver_4.0.4](https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/Dockerfile_r-ver_4.0.4) uses `ubuntu:20.04` as base, however I cannot find the Dockerfile for that image anywhere.

So, could you please inform me where can I find the `ubuntu:20.04` image and Dockerfile?

Thank you

**Comment by eddelbuettel** [comment]
If you search Google for 'docker ubuntu 20.04' the second link is the relevant one:

https://hub.docker.com/_/ubuntu

**Comment by eddelbuettel** [comment]
A large source of "official" Dockerfiles (that we contribute `rocker/r-base` as `r-base` to) is here:  
https://github.com/docker-library/official-images

**Comment by GitHunter0** [comment]
> A large source of "official" Dockerfiles (that we contribute `rocker/r-base` as `r-base` to) is here:
> https://github.com/docker-library/official-images

Great to know this source! Thank you
