### ISSUE TITLE
R_LIBS_USER respected for R, but not Rstudio Server

### ISSUE THREAD

**Issue by rkrug** [rocker-org/rocker-versioned2#133]
This is a followup to my question https://github.com/rocker-org/rocker/issues/441

I managed to get R to set `.libPaths()` as I want to by using 

```
11:27 $ docker run -it  --rm -v /Users/rainer/R/dockerlib:/opt/R/library  --env R_LIBS=/opt/R/library  -p 8787:8787 -e PASSWORD=password --entrypoint /bin/bash rocker/rstudio
root@f090d95f3bfc:/# R

R version 4.0.4 (2021-02-15) -- "Lost Library Book"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> .libPaths()
[1] "/opt/R/library"                "/usr/local/lib/R/site-library"
[3] "/usr/local/lib/R/library"
> Sys.getenv("R_LIBS")
[1] "/opt/R/library"
>
```

but when I start without the entry point to access the studio server, 

```
docker run -it  --rm -v /Users/rainer/R/dockerlib:/opt/R/library  --env R_LIBS=/opt/R/library  -p 8787:8787 -e PASSWORD=password rocker/rstudio
```

I get the following in the browser:

```
> .libPaths()
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"
> Sys.getenv("R_LIBS") 
[1] "/usr/local/lib/R/site-library:/usr/local/lib/R/library"
> 
```

My question: how can I specify a library path for the RStudio server for all users?

**Comment by noamross** [comment]
RStudio, in general, doesn't pass system-level environment variables to R sessions.  Instead, you generally need to pass these variables to a system-level `Renviron` file at `${R_HOME}/etc/Renviron`. See examples in the install scripts: https://github.com/rocker-org/rocker-versioned2/search?q=Renviron

**Comment by rkrug** [comment]
Thanks @noamross - makes sense now.

 I have seen that `R_LIBS_USER` can take more than one path separated by comma - so I should add `/opt/R/library,` in front of the already defined `R_LIBS_USER`. So far so good. What is the easiest to do this from the `docker run` command? Or do I have to create a new Dockerfile with the edits?

**Comment by noamross** [comment]
You could bind-mount a global `Renviron` file directly (to `/usr/local/lib/R/etc/Renviron`).  However, I recommend grabbing the container's `Renviron` first as a template so it contains everything else we set up in the installation scripts.  Otherwise, yes, you could create a Dockerfile with `RUN echo "R_LIBS=/opt/R/library" >> ${R_HOME}/etc/Renviron`

**Comment by rkrug** [comment]
I like the `RUN` in the Dockerfile.

But looking at the Renviron file, it already has

```
R_LIBS_USER=${R_LIBS_USER-'~/R/x86_64-pc-linux-gnu-library/4.0'}
R_LIBS=${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library'}
```

So shouldn't it use the environmental variable `R_LIBS` when I set it via `-e` in the `docker run` command, or does the studio server starts with a 'clean' envelop?

**Comment by noamross** [comment]
I believe it starts "clean" unless those variables are set in the `rstudio.conf` file: https://docs.rstudio.com/ide/server-pro/r-sessions.html#package-installation

**Comment by rkrug** [comment]
OK - the file `/etc/rstudio/rsession.conf` is empty!

So I just created a file `session.conf` which I bind via `--volume /Users/rainer/R/rsession.conf:/etc/rstudio/rsession.conf \` and there it is:

```
> .libPaths() 
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"      "/opt/R/library"
```

So it is there. But I do not seem to be able, to put it first or install in it without specifying the library in the install command.

**Comment by rkrug** [comment]
Found a solution.

I am now using the following `docker run` command

```
docker run \
	--interactive \
	--tty \
	--rm \
	--cpus=3 \
	--memory=50GB \
	--memory-swap=-1 \
	--volume /Users/rainer/R/dockerlib:/opt/R/library \
	--volume /Users/rainer/R/rsession.conf:/etc/rstudio/rsession.conf \
	--publish 8787:8787 \
	--env PASSWORD=password \
	--env ROOT=true \
	-v /Users/rainer/R/rstudio:/home/rstudio/ \
	-v /Users/rainer/Documents:/home/rstudio/Documents \
	rocker/rstudio
```

`rsession.conf` is as followed:

```
r-libs-user=/opt/R/library
```

and I have in the rstudio directory a '.Rprofile` 

```
.libPaths(.libPaths()[[3]])
```
which moves the third library into the first position.

So I have my documents, library path outside the container, and startup files as well.

The only issue is now if additional system libraries need to be installed, but I think there is no way around that without a docker file.

Thanks a lot for your help.
