### ISSUE TITLE
Error occurred during transmission

### ISSUE THREAD

**Issue by emilmahler** [rocker-org/rocker-versioned2#134]
I have for some time been experiencing an error that looks a bit like: _File listing error, error navigating to ~repo, error occurred in transmission_.

The problem can only be solved by removing the container and starting it again (thus requiring me to re-clone repos etc.). It feels like a memory leak, as it seems more likely to happen the longer I leave something running in memory.

The issue is explained in quite a few different threads, notably this one: [https://github.com/rocker-org/rocker-versioned/issues/82](https://github.com/rocker-org/rocker-versioned/issues/82)

I've experienced it on Centos and Ubuntu VMs. Does anyone have any tips on how to debug this kind of issue?

![image](https://user-images.githubusercontent.com/16254022/111664490-1b13bf80-8812-11eb-9428-9ad54f54dd26.png)

**Comment by cboettig** [comment]
yeah, I have also seen this occasionally, but this one is rather hard to reproduce reliably and thus hard to debug!  Any leads are much appreciated.  Previous threads have suggested this is related to various things in specific versions of Docker, so without more information we have been left to guess this is something outside our control hoped this would be resolve upstream.    Meanwhile, it would be good to start collecting a bit more data on the issue.  Can you report your current `docker info` where you see this?  Also, do you have volume mapping in place?  (re re-cloning repos, etc, on my end I tend to always map my working directories, e.g. `~/Documents` to the host volume on any persistent machine that will be up for a long time.  This allows me to destroy and recreate the container at will and pick up precisely where I left off.

**Comment by emilmahler** [comment]
docker info:

```
Client:
 Debug Mode: false
Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 47
 Server Version: 18.09.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
 Operating System: CentOS Linux 8 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 125.7GiB
 Name: nk-centos
 ID: AE37:RCTL:U72F:UEPE:U3TH:E52V:4MAZ:VAOZ:WTQL:2JZN:BYTI:GCTW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 52
```

**Comment by eitsupi** [comment]
I would like to close this as there does not seem to be any additional information. (Is the version of the Docker server out of date?)

If the problem occurs again, please feel free to reopen the issue.
