### ISSUE TITLE
Plotting crash with rocker/rstudio:4.0.0-ubuntu18.04

### ISSUE THREAD

**Issue by brianhuey** [rocker-org/rocker-versioned2#135]
I'm trying to upgrade to 4.0.0-ubuntu18.04 from 3.6.3-ubuntu18.04 but am running into an issue where calling any plotting function (i.e. plot(), ggplot()) causes the rstudio kernel to crash:

`docker run -e PASSWORD=<password> -p 8787:8787 rocker/rstudio:4.0.0-ubuntu18.04`
`plot(1:5,1:5)`
`21 Mar 2021 17:34:18 [rsession-rstudio] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) src/cpp/session/SessionMain.cpp:655`

This works as expected with rstudio:3.6.3-ubuntu18.04. I'm building with the latest docker desktop (3.2.2) on MacOS. Any help would be greatly appreciated, thanks!

**Comment by cboettig** [comment]
thanks, definitely unexpected.  Can you test with `rocker/rstudio:4.0.0` or `rocker/rstudio:latest` ?  (Both are based on ubuntu-20.04)
If it works on those for you but not on the 18.04, please provide `docker info`?

**Comment by brianhuey** [comment]
Both work but throws this message when I call `plot()`:
`Warning message:
In grSoftVersion() :
  unable to load shared object '/usr/local/lib/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory`

Here's what `docker info` returns:
`Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 16
  Running: 0
  Paused: 0
  Stopped: 16
 Images: 237
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 4.825GiB
 Name: docker-desktop
 ID: ND52:KFLR:L7FW:H7YV:XHEW:TJOU:DEY2:4A7R:ZR4J:CUGX:PHAQ:JNTR
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 42
  Goroutines: 46
  System Time: 2021-03-23T03:27:57.6972446Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**Comment by cboettig** [comment]
Thanks!  Note that `plot()` is a generic method, without a reproducible example it's difficult to know what's going on.  From the error it looks like you're doing something with X11.  (If you want Docker to bind your host X11 windowing system you'll need to configure that by binding the appropriate ports and installing the appropriate libraries first.  see https://github.com/rocker-org/rocker-versioned/tree/master/X11 for some pointers).  HTH!

**Comment by brianhuey** [comment]
Thanks Carl, I'm producing the error by executing the following commands which seems like it should be reproducible?
```
docker run -e PASSWORD=<password> -p 8787:8787 rocker/rstudio:4.0.0-ubuntu18.04
plot(1:5,1:5)
```

**Comment by cboettig** [comment]
ok i can take a look with that when I'm back in better internet.  things are fine on `rstudio:latest` though or you get the same X11 error there?

**Comment by brianhuey** [comment]
`plot(1:5,1:5)` works with `rstudio:latest` and `rstudio:4.0.0` but I get the X11 warning when I call the function. With `rstudio:4.0.0-ubuntu18.04` it crashes the kernel. I'm going to use `rstudio:4.0.0` so there's no urgency on my end, but I'm sort of curious whether the error is reproducible on other machines or if it's something to do with my configuration. Thanks for taking the time.

**Comment by michaelmayer2** [comment]
I am still hit by this, even with r-ver:4.1.2 from dockerhub. 

Wondering if it would make sense to add libxt6 and libtk8.6 to the containers so that all dynamic libraries of the R installation loading properly ?

**Comment by eitsupi** [comment]
@michaelmayer2 This issue is about RStudio Server, but RStudio Server is not installed on `rocker/r-ver:4.1.2`.
It may be better for you to create a separate issue.
