### ISSUE TITLE
Change port Rstudio session

### ISSUE THREAD

**Issue by phisanti** [rocker-org/rocker-versioned2#136]
I am writing a docker image based on `rocker/rstudio`, however, I am currently struggling with how to change the port. I am able to run the container in the 8787, however, I would rather use port 8888. It might sound rather simple, here is where I am stuck. 

So This is how my code looks like:
```
FROM rocker/rstudio

#
# Install some libraries and other stuff
#

# Expose default port
EXPOSE 8787 
# Expose the port I would like to use
EXPOSE 8888

CMD ["/init"]
```
With this script, if I run the code:

`docker run --rm -p 8787:8787 -e PASSWORD=test myrocker:local13`

I can perfectly log in to the Rserver session. If however, I try:

`docker run --rm -p 8888:8888-e PASSWORD=test myrocker:local13`

Then, it results impossible to open the docker from the browser (tried localhost:8888).

Please, any advice will be highly appreciated.

------------------------
EDIT:

I am running a Windows 10 machine with WSL (Ubuntu 20.04) and I run docker v20.10.2 from the VScode (1.54.2) extension.

**Comment by cboettig** [comment]
you can bind to any port you like on the host side (left side port number), there is no need to change the EXPOSE command.  This is how any docker application works :-)

e.g. run on port 8888 instead:

```
docker run --rm -p 8888:8787 -e PASSWORD=test myrocker:local13
```

HTH!
