### ISSUE TITLE
Issue with RStudio user authentication cookies

### ISSUE THREAD

**Issue by tsaastam** [rocker-org/rocker-versioned2#137]
There is an issue in these Docker images with the secret used for user authentication cookies not being sufficiently unique. This file:

    /var/lib/rstudio-server/secure-cookie-key

is constant, i.e. two completely separate Docker processes running `rocker/rstudio:4.0.4` have the same secret. This makes it possible for a user to obtain authentication cookies from one Docker process and use them to log in to a different RStudio running in a different Docker container.

Please see this issue for details: https://github.com/rstudio/rstudio/issues/9175

According to the information there, a fix would be to not include that file at all in the Docker image, in which case RStudio will generate a properly unique one itself upon startup. I had a brief look at the Dockerfiles and init scripts but couldn't find where this file is currently coming from. Perhaps you can help.

**Comment by tsaastam** [comment]
This issue can be worked around by using a custom Dockerfile which is based on the `rocker/rstudio` image, but includes the additional action of deleting the cookie authentication file - RStudio will then generate a properly unique one each time the image runs:

    FROM rocker/rstudio:4.0.4
    RUN rm /var/lib/rstudio-server/secure-cookie-key

But it would of course be better to fix the problem at the source, i.e. by not including that file in the `rocker/rstudio` image in the first place.

**Comment by cboettig** [comment]
@tsaastam Thanks for raising this.  The rstudio setup is performed by https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_rstudio.sh, it is a relatively vanilla installation though, so it's not obvious to me from first glance where this key is being created.  Any ideas?

**Comment by eddelbuettel** [comment]
It's not in the `.deb` either:

```sh
$ dpkg -c /tmp/rstudio-server-1.4.1671-amd64.deb | grep secure-cookie-key
$ 
```

and my first reaction was it might actually be installed the post-install script.  Not directly though:

```sh
$ grep cookie /var/lib/dpkg/info/rstudio-server.postinst 
$ 
```

Maybe one of the helper scripts creates it?  Dunno....

**Comment by cboettig** [comment]
@tsaastam this file appears immediately after the rstudio-server-1.4.1671-amd64.deb is installed, though I'm not sure why.
In any event, I'm adding a line to explicitly remove any such key from our scripts.
