### ISSUE TITLE
making environment variables accessible to R in singularity rstudio session

### ISSUE THREAD

**Issue by jflournoy** [rocker-org/rocker-versioned2#138]
I'm running rocker/verse:4.0.4 via singularity and am trying to use environment variables set a number of ways. First, I notice running `Sys.getenv()` that nothing is available from the environment from which I've run the singularity container. I tried setting variables prefixed with SINGULARITYENV_ but that didn't help either. Finally I tried using --bind to include the export command in //etc/rstudio/rsession-profile, but that also didn't work. 

When I run a shell inside the container, and run R, I can see all of the environment variables I would expect. I'm raising this issue here because I'm not sure if this is me misunderstanding how to expose environment variables to R Studio or if it's something about how rserver is implemented in the container.

Thanks!

**Comment by jflournoy** [comment]
I realized I don't need these variables in the R Studio session, but just in R, so I'm closing this. Woops.

**Comment by eitsupi** [comment]
@jflournoy I often write `.Renviron` file to use environment variables in RStudio Server. See https://github.com/rocker-org/rocker-versioned2/issues/93#issuecomment-714185343
