### ISSUE TITLE
LABEL update?

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#148]
It seems better to update the LABEL written in the Dockerfiles.

1. The URL of the repository is old `https://github.com/rocker-org/rocker-versioned`.
2. `org.label-schema` is currently deprecated and `org.opencontainers.image` is recommended now. See http://label-schema.org/rc1/

**Comment by cboettig** [comment]
good catch, yeah a PR to update to current conventions would be much appreciated!
