### ISSUE TITLE
Make Pandoc template version robust to staggered release of pandoc and templates

### ISSUE THREAD

**Issue by noamross** [rocker-org/rocker-versioned2#16]

**Comment by cboettig** [comment]
@noamross I think you completed this?

**Comment by eitsupi** [comment]
https://github.com/rocker-org/rocker-versioned2/blob/cfac661b2871f59b31b8d56b3c6217cd6d521c5b/scripts/install_pandoc.sh#L64-L72

I close this as I believe it has been resolved. Feel free to reopen it again if necessary.
