### ISSUE TITLE
ODBC driver missing on latest tidyverse image?

### ISSUE THREAD

**Issue by decentral1se** [rocker-org/rocker-versioned2#167]
Following https://github.com/rocker-org/rocker/issues/308#issuecomment-427868188 I see that the ODBC drivers should be installed on the image but using the latest one I am seeing the following error: `Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found`. Dropping into the container, I can see the following:

> root@9e5b2ddc3ea3:/# dpkg -l "*odbc*"
> Desired=Unknown/Install/Remove/Purge/Hold
> | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
> |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
> ||/ Name                   Version         Architecture Description
> +++-======================-===============-============-============================================
> un  libiodbc2-dev          <none>          <none>       (no description available)
> un  libmyodbc              <none>          <none>       (no description available)
> ii  libodbc1:amd64         2.3.6-0.1build1 amd64        ODBC library for Unix
> un  odbc-postgresql        <none>          <none>       (no description available)
> ii  odbcinst               2.3.6-0.1build1 amd64        Helper program for accessing odbc ini files
> un  odbcinst1              <none>          <none>       (no description available)
> un  odbcinst1debian1       <none>          <none>       (no description available)
> ii  odbcinst1debian2:amd64 2.3.6-0.1build1 amd64        Support library for accessing odbc ini files
> un  tdsodbc                <none>          <none>       (no description available)
> un  unixodbc               <none>          <none>       (no description available)
> un  unixodbc-bin           <none>          <none>       (no description available)
> ii  unixodbc-dev:amd64     2.3.6-0.1build1 amd64        ODBC libraries for UNIX (development files)

And looking at https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17 it seems that there is another package which needs to be installed.

Would you consider accepting a pull request to add this `msodbcsql17` package on the tidyverse image?

**Comment by cboettig** [comment]
@decentral1se thanks. I see that [r-dbi/odbc recommends](https://github.com/r-dbi/odbc#unixodbc---required-for-all-databases-1)

```
# Install the unixODBC library
apt-get install unixodbc unixodbc-dev

# For SQL Server on Linux it is recommended you use the Microsoft Drivers.
# SQL Server ODBC Drivers (Free TDS)
apt-get install tdsodbc

# PostgreSQL ODBC ODBC Drivers
apt-get install odbc-postgresql

# MySQL ODBC Drivers
apt-get install libmyodbc

# SQLite ODBC Drivers
apt-get install libsqliteodbc
```

so I think that would be the way to go?  PR welcome

**Comment by eddelbuettel** [comment]
(Debian maintainer for RODBC here:  ODBC is a pain in the rear because you need _two_ drivers to provide a connection to the 'consumer' (here R, otherwise analytical program) and then one to offer ODBC _for each of the backends_ hence the per-db backend list.  We may want to think twice about what we want here.  Also, for the former there tend to be two as well: unixodb and libiodbc.)

**Comment by cboettig** [comment]
yeah, `unixodbc-dev` has historically been installed, and should already installed, on tidyverse: https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_tidyverse.sh#L18, but typically we have supported MySQL, SQLite and friends via the DBI interface.  Not entirely sure what is apparently missing here.

@decentral1se can you provide more details with a reproducible example?

**Comment by eddelbuettel** [comment]
The native drivers are also (generally) more performant.  The real issue is that there are just too many drivers so we're back at the problem of bloating  the container images.  Maybe making this a local adjustment is best for all?  Unsure...

**Comment by cboettig** [comment]
Agree.  I read the issue initially as somehow `unixodbc-dev` was no longer installed by default on tidyverse, which it used to be.  But it's still there.  after that I think it's up to the users.  @decentral1se if you're using MySQL/MariaDB definitely recommend trying the DBI route where the native drivers should also already be installed, e.g. see https://db.rstudio.com/dbi/
