### ISSUE TITLE
Can't login into servers on different ports on the same computer

### ISSUE THREAD

**Issue by aputron** [rocker-org/rocker-versioned2#171]
Hello!

I have recently started using rocker for building servers for various purposes in my organization. We have used the RStudio and the ml versions of rocker. The containers are run on a Linux system. 
First, we ran an image of rocker/rstudio:4.0.4, built using a Dockerfile with the following command:
```
docker run -d --rm -e PASSWORD:PASSWORD -p 8787:8787 rocker/rstudio:4.0.4
```
The web version of RStudio was successfully opened and we were able to use multiple users as well.

Next, we ran a container based on the image of rocker/ml:4.0.5-cuda10.1 using the following code (on the same computer)
```
 docker run --runtime=nvidia --gpus all -e PASSWORD:PASSWORD -p 9000:8787 rocker/ml:4.0.5-cuda10.1
```
This also successfully opened the web version of RStudio that could run data on the system GPUs.

The problem arose when we tried using both servers (0.0.0.0:8787 and 0.0.0.0:9000) at the same time on one machine. The web versions would automatically logout from the R session if the two servers are opened together. 
Although both docker containers have the same internal ports (of 8787) they shouldn't logically interfere with each other if the local ports are different, right? (This wasn't an issue when running 2 express node.js servers via docker simultaneously, as a test)

I can simply build one server that contains the two versions I require, but was curious as to why this was happening.
I hope I was able to convey the issue appropriately.
Thank you for developing this cool platform and for helping out!

**Comment by cboettig** [comment]
Thanks for reporting.  

I wonder if this is related to #137/#165 ?  Can you check if `/var/lib/rstudio-server/secure-cookie-key` exists in both instances, and is not the identical file?

While this used to work, the issue may be instead related to intentional changes in RStudio server's handling of cookies.  You might also check if you can successfully connect to the different sessions simultaneously but in different browsers (eg firefox/chrome) or in a private window?  

Last thing to fiddle with, is that the automatic timeout logout behavior is configurable, it may be that we can also configure this logout behavior separately now, but haven't had a chance to dive into the rstudio server docs recently to look for any changes in configuration.   

last footnote: I mostly run multiple containers on a server, where a reverse proxy server (I like Caddy Server, also dockerized) serves them to separate domains (this way we don't publish the port at all to the host).  So anyway, though your instances are isolated on separate ports, accessing both in the same browser probably means it stores their cookies as being on the same domain, and thus triggers the log-out of one when you log into the other.  If you're running on a remote server already, I strongly recommend the reverse proxy, since it also means you can put your instances behind https.

**Comment by aputron** [comment]
Hello!

Thank you for your quick response and explanation!

Both containers had the `secure-cookie-key` file with the same key in its contents. I tried deleting the file from the docker container in one of the files, but the issue persisted. So I restarted the changed docker container, and the file was created again with a different key, and the issue remains. I will try removing the file while building via the Dockerfile next. 

As you suspected, I was successfully able to connect to the different severs using different browsers and/or in a private window. 

I will try your other recommendations of timeouts and the reverse proxy server and let you know how that goes!

Thanks again!

**Comment by cboettig** [comment]
@aputron thanks for the report. good see that the key changed on re-creation, but bummer that didn't fix it, the cache record must not be tied to the key.  We may need to discuss that one with RStudio and see if this is indeed the intended behavior for the browser cache.  

Do keep us posted, we're a community-driven project here and I and surely other users will benefit from what you figure out here! Thanks!

**Comment by StudioEtrange** [comment]
@aputron same problem here ! using traefik as reverseproxy
no solution found yet, since months... :/

**Comment by eddelbuettel** [comment]
FWIW I also have the same issue on an Ubunru system where I ran a 'native' RStudio Server. In the past I use to be able to also run a container (for a quick check or demo) offering RStudio Server (obviously via different port).  These days "something bites" and things get instantiated in such a way that I have to nix the external RStudio Server to test the container.  Not ideal, and a change from prior behaviour but in the end not that big an issue for me.

**Comment by cboettig** [comment]
also have observed this with ports, but have no trouble when serving multiple containers off the same host with a reverse proxy with different https subdomains...

Definitely agree this is a nuisance though, particularly as it's hard to change projects or open other interactive sessions on the same host while tasks are running.  I admit that vscode (including the open source code-server  version in #295 handles this much more nicely -- you can easily switch between additional projects in additional tabs without launching a separate container).  

Anyway, closing as this appears to be an RStudio design choice and not something `rocker` can resolve directly.

**Comment by floriandeboissieu** [comment]
My 2 cents on the topic with firefox browser:
- standard windows/tabs and private windows/tabs are not sharing cookies (but each type is sharing among windows/tabs of the same type) --> thus for two rstudio-servers, a server on each is working (cf https://support.mozilla.org/en-US/questions/960464)
- for more than two rstudio-servers, multi-account-containers allows to open one server by container: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by StudioEtrange** [comment]
Yes the pb come frome the cookies which is the same even we are on two rstudio server instance in container.
We can uses an addon to separete cookies OR use private navigation

BUT there is still a big problem : If i log into a rstudioserver container as root with my own password on my instance "http://rstudio/user1"
and if another user have launch its own instance ("http://rstudio/user2") with its own passowrd (but same login : root) 
the user1 once authentified on the first instance is logged in the second instance too without prompting password !! The cookie is shared among instances !
This is a security issue now :)

**Comment by MajoroMask** [comment]
> 

The browser container thing works like a charm, very helpful!
