### ISSUE TITLE
rocker/shiny-verse:4.1.0

### ISSUE THREAD

**Issue by Ada-Nick** [rocker-org/rocker-versioned2#178]
Latest version of shiny-verse base image is retuning the following error for new builds of our previously stable docker images.

rm: cannot remove '/srv/shiny-server/*': No such file or directory 

Has the location from which shiny apps are served changed?

**Comment by eitsupi** [comment]
Sorry, I accidentally pushed `rocker/verse:4.1.0` as `rocker/shiny-verse:latest`.
See #177

Now that the correct build is running, the correct `rocker/shiny-verse:latest` should be available in about an hour.
https://github.com/rocker-org/rocker-versioned2/actions/runs/943351773

**Comment by Ada-Nick** [comment]
Thanks for the quick reply!

**Comment by eitsupi** [comment]
Unfortunately, the build seems to have failed due to a bad connection with the repository.
![image](https://user-images.githubusercontent.com/50911393/122255056-b77c5980-cf08-11eb-9f55-763164b81b49.png)

@cboettig Can you please re-run this job?
https://github.com/rocker-org/rocker-versioned2/actions/runs/943351773

**Comment by cboettig** [comment]
Thanks @eitsupi , re-running now.

**Comment by eitsupi** [comment]
It seems to have worked. Thanks.

![image](https://user-images.githubusercontent.com/50911393/122263106-05955b00-cf11-11eb-811f-f69b1b7bf996.png)
![image](https://user-images.githubusercontent.com/50911393/122263115-07f7b500-cf11-11eb-9fb5-7749171b073f.png)
![image](https://user-images.githubusercontent.com/50911393/122263264-32e20900-cf11-11eb-9e14-1ccb2f2b388a.png)
![image](https://user-images.githubusercontent.com/50911393/122263278-35446300-cf11-11eb-8442-75ab3f18fddf.png)
