### ISSUE TITLE
Docker Hub rocker documentation 

### ISSUE THREAD

**Issue by stevegbrooks** [rocker-org/rocker-versioned2#191]
The docker hub site for rocker still mentions that the images are built on debian, but they're now being built on Ubuntu.

Should be an easy fix, and I'd submit the PR myself, but I just don't know where to do it.

Thanks

**Comment by cboettig** [comment]
Thanks!  Can you link to the page you are seeing?  Docker Hub is a bit convoluted on this: pages "Overview" shows the README of the page that was once connected to an automated build. e.g. the overview you see at: https://hub.docker.com/r/rocker/rstudio comes from this readme: https://github.com/rocker-org/rocker-versioned/tree/master/rstudio#readme, even though the image is no longer built from that repo.  (Hub doesn't support enough tags in automated builds, and doesn't provide an independent way to re-wire which readme is displayed for which image!)

**Comment by stevegbrooks** [comment]
https://hub.docker.com/r/rocker/verse

Here it mentions Debian:

"This repository provides alternate stack to r-base, with an emphasis on reproducibility. Compared to those images, this stack:

builds on debian stable (debian:jessie for versions < 3.4.0, debian:stretch after, etc) release instead of debian:testing, so no more apt-get breaking when debian:testing repos are updated and you had to muck with -t unstable to get apt-get to work."

**Comment by eitsupi** [comment]
https://hub.docker.com/r/rocker/verse is linked to https://github.com/rocker-org/rocker-versioned, but the contents of README.md do not seem to be reflected.

DockerHub
![image](https://user-images.githubusercontent.com/50911393/129469831-8c895da3-6067-45f0-9f63-3a6dab21d8ed.png)

GitHub
![image](https://user-images.githubusercontent.com/50911393/129469837-f077464f-b0e1-4409-bd11-b8a3ca8372d6.png)

**Comment by pgramme** [comment]
I also had the same problem: following the link from DockerHub to Github leads to the old repo (R v3.x), not here. I understand it would be best to have that DockerHub-GitHub link depending on the version but you can't.

Simple fix: Assuming most people are now interested in R 4.x, wouldn't it be useful to update the Github link on https://hub.docker.com/r/rocker/verse? (should point here)

**Comment by dpprdan** [comment]
> hub.docker.com/r/rocker/verse is linked to rocker-org/rocker-versioned, but the contents of README.md do not seem to be reflected.

This is basically true for all versioned2 images, i.e. their README and their Source Repository links are outdated. 
(TBF some READMEs contain a note about the versioned2 stack).

**Comment by eitsupi** [comment]
Since there are many documents with similar contents in various places, it might be better to consolidate the documents on the Rocker Project website and link to them from other sources.

**Comment by eitsupi** [comment]
There is a GitHubActions that can update the DockerHub documentation.
Why not aggregate the documentation for images generated from this repository into this repository and deploy them to DockerHub with GitHubActions?
https://github.com/peter-evans/dockerhub-description

**Comment by cboettig** [comment]
ooh, that's a great idea!

**Comment by eitsupi** [comment]
As I mentioned in my comment, if the workflow I added in #307 works properly, you can consolidate documents into this repository to reduce management effort and user confusion.

@cboettig 
As I mentioned in my comment (https://github.com/rocker-org/rocker-versioned2/pull/307#issuecomment-990864893), I think the reason this workflow didn't work at the moment is the API limitation that we can't use it without a password instead of a token.
Would you try registering the secret again and see if it works again?

**Comment by dpprdan** [comment]
The GHA approach is really elegant. Would it be possible to update the Source Repository URL with this as well? (I looked at the GHA and it seems to me that it isn't, but then again, I wasn't even able to figure out where the Source Repository URL can be configured in the Docker Hub settings).

This is what I mean with "Source Repository URL" on https://hub.docker.com/r/rocker/verse for example:
![Screenshot of https://hub.docker.com/r/rocker/verse with the Source Repository URL highlighted.](https://user-images.githubusercontent.com/1423562/147929602-853e44dd-8f76-4930-a7bf-32a855c569a4.png)

**Comment by cboettig** [comment]
It would be great to update that, though I think it applies only to automated builds, which includes the 3.x series.

**Comment by eitsupi** [comment]
Since the automatic build on DockerHub stopped about half a year ago (and the last build of `rocker/r-ver:3.6.3` was in May 2020, so there is a possibility that the automatic build stopped before then), I don't think that changing the URL association will have any impact.
https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

**Comment by eitsupi** [comment]
We are currently creating reference pages for each image on [the Rocker website](https://www.rocker-project.org/).
After this work, I would like to remove the documentation from DockerHub, except for the links to the Rokcer website, to avoid confusion.

**Comment by eitsupi** [comment]
I manually updated the READMEs of the repositories pushed from here.
I think manual updating is sufficient, although recent DockerHub updates seem to be able to update READMEs using the API.
