### ISSUE TITLE
Add smoke tests to modules

### ISSUE THREAD

**Issue by noamross** [rocker-org/rocker-versioned2#20]
Single line commands at end of model partial Dockerfiles that check installation works, e.g. gets R version.

**Comment by eitsupi** [comment]
I have done this for several scripts in my recent refactoring works (#386, #395).

https://github.com/rocker-org/rocker-versioned2/blob/cfac661b2871f59b31b8d56b3c6217cd6d521c5b/scripts/install_R_source.sh#L158-L163
https://github.com/rocker-org/rocker-versioned2/blob/cfac661b2871f59b31b8d56b3c6217cd6d521c5b/scripts/install_rstudio.sh#L113-L118
https://github.com/rocker-org/rocker-versioned2/blob/cfac661b2871f59b31b8d56b3c6217cd6d521c5b/scripts/install_tidyverse.sh#L50-L55
