### ISSUE TITLE
geospatial stack should include terra package

### ISSUE THREAD

**Issue by myoung3** [rocker-org/rocker-versioned2#207]
From the authors:

> The “terra” package is a new R package to replace “raster”. “terra” is easier to use, has more functionality, and it is faster. So if in doubt use the terra version.

https://rspatial.org/

From my testing, terra is much faster than raster in some cases. Installing it should be as easy as install.packages("terra") since it doesn't have any additional system dependencies beyond those of raster.

**Comment by cboettig** [comment]
Thanks @myoung3 , agreed. want to send a PR against https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_geospatial.sh ?

**Comment by myoung3** [comment]
minor correction: it has basically the same system dependencies of sf, not raster. But that's a moot point since sf is also already in geospatial.

terra:
C++11, GDAL (>= 2.2.3), GEOS (>= 3.4.0), PROJ (>= 4.9.3), sqlite3

sf:
C++11, GDAL (>= 2.0.1), GEOS (>= 3.4.0), PROJ (>= 4.8.0), sqlite3

the slight difference in PROJ dependency I think does not matter since geospatial seems to be using 7.2.0

**Comment by eddelbuettel** [comment]
Are there other packages from the 'new' geo stack we're missing?

**Comment by myoung3** [comment]
Just looking at r-spatial.org, maybe gdalcubes and rstac. Maybe a question for Edzer Pebesma?

**Comment by myoung3** [comment]
also mapedit https://r-spatial.org/r/2019/03/31/mapedit_leafpm.html

**Comment by myoung3** [comment]
also rgee. Is it ok that this links to python? If we include rgee, we'd need to put reticulate in geospatial.

**Comment by myoung3** [comment]
rgee also has a bunch of suggests that are pretty important for fully using it. Definitely googledrive and googleCloudStorageR if you want to download data. Probably a bunch of those others for interactive mapping.

**Comment by cboettig** [comment]
Thanks @myoung3  :+1:  for adding `gdalcubes`, `rstac` & `mapedit`. 

Let's think about `rgee` and friends ... adding `reticulate` itself is simple enough, but I think I'm still dialing in the version control for python.  (It does look like the `rgee` developers fix the `ee_version` string in the R package's installer method, which is good from our perspective.  That serves to lock the python version of the package to the R version, but doesn't ensure the python module's own dependencies will be version stable).  

 @edzer, @Robinlovelace we always love your input!

**Comment by myoung3** [comment]
Yeah I'm inclined to agree on rgee--adding python opens up a whole set of issues it would be nice to avoid in the geospatial stack.

**Comment by Robinlovelace** [comment]
+1 for keeping the rocker/geospatial images focussed on in-memory analysis and preventing mission creep. I think there may be demand for `rgee` images but this may not be the best place for that.

**Comment by myoung3** [comment]
Looks like the post on mapedit also recommends lwgeom

**Comment by cboettig** [comment]
I think we already pull in `lwgeom` indirectly (probably from `stars`) but no harm in listing it explicitly

**Comment by edzer** [comment]
I agree.

On August 5, 2021 6:08:19 PM GMT+02:00, Robin ***@***.***> wrote:
>+1 for keeping the rocker/geospatial images focussed on in-memory analysis and preventing mission creep. I think there may be demand for `rgee` images but this may not be the best place for that.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rocker-org/rocker-versioned2/issues/207#issuecomment-893580747
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
