### ISSUE TITLE
Rename the Dockerfiles

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#219]
Currently, the Dockerfiles in this repository have names like `Dockerfile_foo_X.Y.Z-bar`, which is not recognized as Dockerfiles by many tools.

For example, GitHub does not recognize them as Dockerfiles, so there is no syntax highlighting.

This repo, it seems to be recognized as Roff.

![image](https://user-images.githubusercontent.com/50911393/129315483-a4157c5e-6d1e-44cd-a628-fe8ddd7a83f5.png)

[rocker-org/rocker-versioned](https://github.com/rocker-org/rocker-versioned)

![image](https://user-images.githubusercontent.com/50911393/129315545-8a6a365b-fb68-46b0-b639-bb67d3130cfa.png)

I think it is better to rename them to `foo_X.Y.Z-bar.Dockerfile`.

Perhaps just fix the following?

https://github.com/rocker-org/rocker-versioned2/blob/c62c4ca1193bf29f724e42a8d3549568989dd24a/build/make-dockerfiles.R#L43
https://github.com/rocker-org/rocker-versioned2/blob/c62c4ca1193bf29f724e42a8d3549568989dd24a/build/write-compose.R#L24-L41
https://github.com/rocker-org/rocker-versioned2/blob/c62c4ca1193bf29f724e42a8d3549568989dd24a/build/make-bakejson.R#L23
https://github.com/rocker-org/rocker-versioned2/blob/c62c4ca1193bf29f724e42a8d3549568989dd24a/Makefile#L100-L101

**Comment by cboettig** [comment]
yes! totally :100:  support renaming like this.  ( starting with `Dockerfile_` is also annoying because you cannot tell what's what when names are truncated, and it's less friendly for tab-completion)
