### ISSUE TITLE
GitHub Actions capacity

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-versioned2#22]
GitHub Actions seems unable to handle pushing all images in a stack :cry: .  Seems to get through between 1 and 4 images before giving an authentication error, which is nonsense since it was clearly authenticated for the first few builds (unless we're hitting some kind of rate-limiting, but I thought those rates didn't limit you on public repos when pushing from within Actions).  

Anyway, I suppose one could try splitting it up into several stages (in the extreme, each image builds in a separate action?)  that's kinda antithetical to how things are set up currently.

Also I wonder if this is just the GitHub Docker registry being junk, and maybe the same action but pushing directly to docker hub would be fine...

**Comment by noamross** [comment]
Switch to pushing to docker hub, maybe with dev tags

**Comment by cboettig** [comment]
Mostly improved, still seeing some occasional failures.  Could be more robust by merely repeating the push command twice in the same call, e.g. like 


```
docker-compose -f compose/core-devel.yml push || docker-compose  -f compose/core-devel.yml push
```

**Comment by cboettig** [comment]
(note that everything has been switched over to pushing to docker hub directly, so we're not using the github docker registry at all now.  dev images get pushed to `rockerdev`, so far nothing is going live yet to `rocker`)
