### ISSUE TITLE
[Feature Request] rocker/deseq2

### ISSUE THREAD

**Issue by bounlu** [rocker-org/rocker-versioned2#225]
Hi,

Please create rocker/deseq2_dexseq image.

Thanks.

**Comment by cboettig** [comment]
Sorry, but you haven't provided us with much information.  In general, we encourage user communities to create their own derivative images for specific software needs unless there's a compelling general-interest use case.

**Comment by bounlu** [comment]
Hi,

Please create rocker/deseq2_dexseq image.

**Rationale:** DESeq2 / DEXSeq are very popular tools used in the R community for differential gene and isoform expression analysis of RNA-Seq data. Although it's possible to derive it from other available images, the build time increases significantly as these tools have an exhaustive list of dependencies. My last try took several hours to build this:

```
FROM rocker/tidyverse
RUN /usr/local/lib/R/site-library/littler/examples/installBioc.r DEXSeq
```
Note that DEXSeq installs DESeq2 and other dependency packages needed.

I believe this image will be very useful for many other users.

Thanks.

**Comment by eitsupi** [comment]
@bounlu Hi, I don't use Bioconductor and don't know much about it, but how about a suggestion to [Bioconductor/bioconductor_docker](https://github.com/Bioconductor/bioconductor_docker) that might be more geared towards Bioconductor users?

Alternatively, you can use GitHub Actions on the GitHub repository to build container images and save them to GHCR in a fully automated manner.
For example, I have images in this repository that takes 6 hours to build. I have never built these images locally.
https://github.com/eitsupi/r-ver
![image](https://user-images.githubusercontent.com/50911393/129869358-d69a5831-b5d5-4c2b-b553-be78cbf27bd1.png)

**Comment by bounlu** [comment]
@eitsupi 
Thanks for the useful suggestions. I will look at them if I can use for my purpose.
