### ISSUE TITLE
Change the copy order according to best practices?

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#230]
Currently, the Dockerfiles of `rocker/r-ver` has the following structure, so when one of the files in `scripts` is updated, the subsequent layers will be new even if the cache is available.

```Dockerfile
FROM ubuntu:focal

COPY scripts /rocker_scripts
RUN /rocker_scripts/install_R.sh
```

According to [the best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-multi-stage-builds), the following configuration is more desirable as it increases the likelihood of sharing layers with each build. If the base image `ubuntu:focal` has not been updated and `install_R.sh` has not been changed, the new layer will be only the last `COPY`, whose build time and the new layer size is very small.
(Of course, `rocker/r-ver:devel` expects the result of `install_R.sh` to be different every time, so we need to disable the cache.)

```Dockerfile
FROM ubuntu:focal

COPY scripts/install_R.sh /rocker_scripts/install_R.sh
RUN /rocker_scripts/install_R.sh
COPY scripts /rocker_scripts
```

This change and the enabling of caching (which can be controlled in `docker-bake.json`, e.g. `"cache-from": ["rocker/r-ver:X.Y.Z"]`) will shorten the build time and slightly reduce the pull time.
Especially for multi-architecture builds, the execution time of `install_R.sh` can be very long, so this change is very worthwhile from the perspective of reducing the build time.

**Comment by cboettig** [comment]
Yeah, caching issues are always tricky.  We actually started doing this when the `/rocker_scripts` dir was first introduced, and dropped the successive `COPY` commands to improve cache performance (COPY breaks cache when any of the files have changed, as you know) when rebuilding images (which I think was prior to RSPM integration so builds were very slow).  

I agree that we should put the COPY back into all Dockerfiles for the reasons outlined above!

**Comment by eitsupi** [comment]
@cboettig Thank you for your explanation.
Am I correct in assuming that "all Dockerfiles" in your comment means all Dockerfiles of rocker/r-ver?
Considering the current structure of including `/rocker_scripts` in all images and (and, if we use cache, the result of the scripts execution will not change and the package will not be updated), I believe that we should use cache only in `install_R.sh`.

I'm currently in the process of changing the stack file in #227, so may I make this change along with it?
I think this can be achieved by dividing `COPY` section in the stack files into two parts, such as `COPY_before_RUN` and `COPY_after_RUN`, and making the same changes to the `make-dockerfiles.R`.

**Comment by cboettig** [comment]
:+1: yeah, the `r_ver` flavor Dockerfiles.  folding this into the #227 edits makes sense to me!

**Comment by eitsupi** [comment]
Oddly enough, it seems that cache was not used in today's build, even though the digest of the base image was the same from the build 12 days ago and there were no changes in `install_R.sh`.

According to the message, cache should have been enabled...

![image](https://user-images.githubusercontent.com/50911393/133116329-c3167200-63c2-42ac-b8d6-04d32d9b6b57.png)

![image](https://user-images.githubusercontent.com/50911393/133116342-a4c2f691-5669-4e8a-9433-ce0cc8cd5bc3.png)
