### ISSUE TITLE
-e ROOT=true option not making rstudio user root

### ISSUE THREAD

**Issue by abalter** [rocker-org/rocker-versioned2#237]
I'm starting rstudio server with

    docker run -d -p 8787:8787 -e ROOT=TRUE -e PASSWORD=rstudio rocker/rstudio

And yet

![image](https://user-images.githubusercontent.com/5349876/132778400-ee7c9b1c-776a-4723-a50f-d5895a59afe5.png)

and

```

(base) balter@balter-host:~$ docker exec -it boring_buck bash
root@9cf43917d75b:/# su rstudio
rstudio@9cf43917d75b:/$ groups
rstudio staff

```

Also referencing https://github.com/rocker-org/rocker/issues/94#issuecomment-64753170

**Comment by eitsupi** [comment]
We need to set a password other than "rstudio". If the password is "rstudio", the following script executed at startup will end the process halfway, so most of the setting items will be skipped.

https://github.com/rocker-org/rocker-versioned2/blob/f7ab1bf96926a735f65e60ed07d376019bc67fb7/scripts/userconf.sh#L27-L36

```shell
$ docker run --rm -it -p 8787:8787 -e ROOT=TRUE -e PASSWORD=password rocker/rstudio
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] userconf: executing...
Adding user `rstudio' to group `sudo' ...
Adding user rstudio to group sudo
Done.
rstudio added to sudoers
skipping /var/run/s6/container_environment/HOME
skipping /var/run/s6/container_environment/PASSWORD
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

![image](https://user-images.githubusercontent.com/50911393/132839535-ecdc7a0f-8dd9-4e05-9e80-c0b321426ec7.png)

**Comment by cboettig** [comment]
Thanks @eitsupi .  Yeah that looks like a bug, the config script should be throwing an error when a user uses the default `rstudio` password.  Currently it throws the error message but allows the script to continue:

```
docker run -ti --rm -e ROOT=TRUE -e PASSWORD=rstudio rocker/rstudio
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] userconf: executing... 


ERROR: You must set a unique PASSWORD (not 'rstudio') first! e.g. run with:
docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio


[cont-init.d] userconf: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by abalter** [comment]
You can close my issue if you want, unless you want to leave it open until the bug is fixed.

**Comment by eitsupi** [comment]
Simply deleting this line will continue the process and I think it will be resolved.

https://github.com/rocker-org/rocker-versioned2/blob/eb56c133834d9131c3e9606cd1cae5926cc59766/scripts/userconf.sh#L35

I had noticed this behavior before(https://github.com/rocker-org/rocker-versioned2/issues/151#issuecomment-867541487), but I was wondering if the author intended to cause the user to notice the error by causing a malfunction when the container was started in the background. (Like this issue!)
