### ISSUE TITLE
base package tcltk cannot be loaded

### ISSUE THREAD

**Issue by reikoch** [rocker-org/rocker-versioned2#268]
Just tested r-ver 4.1.1 and 4.0.5 both freshly downloaded from dockerhub. R sessions start fine, but "library(tcltk)" results in both versions in  
``` 
Error: package or namespace load failed for ‘tcltk’:
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/usr/local/lib/R/library/tcltk/libs/tcltk.so':
  libtcl8.6.so: cannot open shared object file: No such file or directory
```

**Comment by eitsupi** [comment]
See https://github.com/rocker-org/rocker-versioned2/issues/707#issuecomment-1747612997

**Comment by eddelbuettel** [comment]
> It's always a bit of a nuisance that we have to use the version strings in debian runtime libs (tcl8.6, tk8.6) but we don't need to know the version strings dev...

Thinking out loud, we could do what my (baby) package [chsli](https://github.com/eddelbuettel/chshli) does, or Jeroen's `maketools`, or just poke `ldd` at the library.  It will tell you post build.

Actually so does `apt-cache show r-base-core | grep libtk | head -1` so it is "computable" but then again tcl/tk do not change that much anymore so a fixed string may be "easiest" even if inelegant...
