### ISSUE TITLE
Two different RSPM repositories; `https://packagemanager.rstudio.com/all` and `https://packagemanager.rstudio.com/cran`

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#290]
Currently, the RSPM URLs configured as CRAN mirrors use `https://packagemanager.rstudio.com/all/` for the latest images and `https://packagemanager.rstudio.com/cran/` for the frozen images.

https://github.com/rocker-org/rocker-versioned2/blob/6d5eed8501d092903b194df6d45c6bd4c0a6c6bd/dockerfiles/r-ver_4.1.2.Dockerfile#L13

https://github.com/rocker-org/rocker-versioned2/blob/6d5eed8501d092903b194df6d45c6bd4c0a6c6bd/dockerfiles/r-ver_4.1.1.Dockerfile#L13

However, when I looked at [the RStudio Public Package Manager website](https://packagemanager.rstudio.com/client/#/repos/2/overview), I noticed that `all` and `cran` refer to different repositories, and one of them can be used for both the latest and frozen images.
The only difference between `all` and `cran` seems to be whether or not the `bikeHelpR` package, which is a package for [the demo](https://github.com/sol-eng/bike_predict) and not registered in CRAN, is registered.

I also noticed that in the past, `all` was used even for frozen images. (Changed in https://github.com/rocker-org/rocker-versioned2/commit/da083d4c0181cd396304c413d4996ec264475a31)

https://github.com/rocker-org/rocker-versioned2/blob/ee579a61fcc215c6493b00de3413b54e7f04902e/dockerfiles/Dockerfile_r-ver_4.0.2#L13

For simplicity's sake, do you think it makes sense to change the CRAN of the latest images to `https://packagemanager.rstudio.com/cran/__linux__/focal/latest` ?

**Comment by cboettig** [comment]
iirc, `all` date format ~~is not available for frozen versions~~ uses a different syntax for frozen snapshots, eg https://packagemanager.rstudio.com/all/__linux__/focal/2021-09-14+Y3JhbiwyOjQ1MjYyMTU7MjQ1QUQ0RA.  

I agree that it would make more sense to standardize on CRAN.
