### ISSUE TITLE
Root permissions on rstudio

### ISSUE THREAD

**Issue by paupaiz** [rocker-org/rocker-versioned2#293]
Might be related to issue #237
I am `root` in container and `rstudio` inside session despite having used `-e ROOT=true`
<img width="376" alt="Screen Shot 2021-11-23 at 8 11 42 AM" src="https://user-images.githubusercontent.com/59720098/143125430-371612c1-2895-421d-a802-255dedd8b33b.png">

**Comment by eitsupi** [comment]
As written in this document, `-e ROOT=TRUE` only gives sudo privileges to the non-root user (`rstudio`), so it seems that the `/root` directory cannot be opened without using the `sudo` command.

https://www.rocker-project.org/use/managing_users/

> Root (sudo) privileges in RStudio containers
> In RStudio containers, you can also add the non-root user to the sudoers group when the container is launched simply by specifying the environmental variable, -e ROOT=true in your docker run command. Note that if you have disabled authentication and not specified a password, the password to use sudoas the rstudio user will also be rstudio.

Other environment variables for switching users exist, but the root user with UID=0 (<499) cannot be set as the RStudio Server user now.

https://github.com/rocker-org/rocker-versioned2/blob/889a33b959a319f59acc634563f8d8eca8abbac0/scripts/userconf.sh#L38-L50

**Comment by paupaiz** [comment]
Thank you @eitsupi so I can give RStudio user root privileges but I cannot set it as the root user even with `chown` ?

**Comment by eitsupi** [comment]
As far as I am aware, this is not possible unless `userconf.sh` is rewritten.
I don't know why you would want to do that, but I suppose you could try replacing `userconf.sh` and building the image yourself if you need to.

`userconf.sh` is located `/etc/cont-init.d/userconf` in `rocker/rstudio`.

https://github.com/rocker-org/rocker-versioned2/blob/d0df52bdd47336f5bdf9bb85e88b42c58b96a55a/scripts/install_rstudio.sh#L130-L131

**Comment by eitsupi** [comment]
I close this as I believe it has been answered. Feel free to reopen it again if necessary.
