### ISSUE TITLE
Start with /auth-sign-in not possible

### ISSUE THREAD

**Issue by steckhan** [rocker-org/rocker-versioned2#297]
Dear Rocker Team,

I am running the docker on a multi user system and would like to start RStudio with /auth-sign-in in order to be password protected. The Rocker RStudio always opens immediately with my default user account when visiting the 8787 port. Here everyone can open my RStudio only by knowing and visiting the Port 8787. Any suggestions or workarounds ? Tried DISABLE_AUTH=false which did not work.
Thanks in advance
Nico

**Comment by cboettig** [comment]
@steckhan are you sure this is not simply a case of your browser having cached your credentials after login?  Can confirm this happens after clearing browser cache, using a different browser, or using a private browser window?  As @eitsupi recommends, it would also help us if you report the command you used to launch the instance.

**Comment by steckhan** [comment]
Dear Rocker Team,

I did ask my colleague and he could open the port without logging in.
This is how I start the Docker instance:

enroot start --rw -e PASSWORD=password rocker+rstudio+4.0.5 &


Best,
Nico

**Comment by cboettig** [comment]
@steckhan Thanks!  It looks like you are using `enroot` and not the docker engine to the run the container.  While I'm not familiar with enroot, from https://github.com/NVIDIA/enroot I see:

> It uses the same underlying technologies as containers but removes much of the isolation they inherently provide 

and your run command doesn't need to expose a port.  I'd recommend trying with:

```r
docker run --rm -p 127.0.0.1:8787:8787 -e password=YourPassword rocker/rstudio:4.0.5
```

if possible. Also note that if you docker on an exposed port, e.g. 0.0.0.0:8787, your colleague will be able "to see the port", though they should be asked for the login screen first.   

I'd suggest asking for help explicitly about enroot and controlling ports in stackoverflow.  To me, this does not appear to be an issue with rocker configuration per se but a general question about docker, enroot, and public ports.

**Comment by steckhan** [comment]
Dear Carl,

Thanks for your explanation, it seems like the docker fetches the credentials from my environment and logs automatically in. Also when thrying to log out I never reach the auth_sign_in page.

Best
Nico
 

> Am 29.11.2021 um 16:11 schrieb Carl Boettiger ***@***.***>:
> 
> docker run --rm -p 127.0.0.1:8787:8787 -e password=YourPassword rocker/rstudio:4.0.5

**Comment by steckhan** [comment]
I would like to have:

-e DISABLE_AUTH=False


But this doesn’t apply.

**Comment by steckhan** [comment]
I got the auth-sign-in page while adding auth_none=0 to the rserver.conf.

Unfortunately I can not login because “username/password incorrect” …
Although I have used the login details that PAM should have

Would be nice if you have any idea

Best regards,
Nico

**Comment by cboettig** [comment]
Hi Nico,

as mentioned before, we really cannot help debug issues without even knowing exactly what commands you are running in what environment.  We're also volunteers, and try to focus time on bug reports where we have reproducible examples of the unexpected behavior. I realize Rstudio, docker, etc have many configuration options that can be tricky, but suggest you try asking on a more general forum like stackoverflow or RStudio community first.
