### ISSUE TITLE
install fails when RSPM is inaccessible

### ISSUE THREAD

**Issue by VicenteYago** [rocker-org/rocker-versioned2#301]
Hi 
im using the `rocker/tidyverse:latest` docker

I have tried to install the `tidymodels` package among others with this Dockerfile:

```{Dockerfile}
FROM rocker/tidyverse:latest

RUN R -e "install.packages(c('tidymodels'), dependencies = T)"
```
Obtaining the following error:
```{bash}
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib:
  cannot open URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/PACKAGES'
Warning message:
package ‘tidymodels’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
```

Any hint ?

**Comment by eitsupi** [comment]
RStudio Public Package Manager, the repository configured in the Docker image, seems to be down (c.f. https://github.com/rocker-org/rocker-versioned2/pull/299#issuecomment-984540741)

So the workaround at this stage is to install the package from another CRAN mirror.
Try setting up a CRAN mirror of your choice in the repository on Rprofile. This is the general R configuration procedure.

If you want to configure the settings on the Dockerfile, you can add the following line to make it work.

```Dockerfile
RUN echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> ${R_HOME}/etc/Rprofile.site
```

**Comment by VicenteYago** [comment]
Thanks! now works like a charm
