### ISSUE TITLE
"cannot change locale" warnings

### ISSUE THREAD

**Issue by dpprdan** [rocker-org/rocker-versioned2#302]
I get "cannot change locale" warnings, when I build r-ver (4.1.2) images. They occur on GHA here as well: 

E.g. [here](https://github.com/rocker-org/rocker-versioned2/runs/4355910963?check_suite_focus=true#step:6:114)

```sh
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

and [here](https://github.com/rocker-org/rocker-versioned2/runs/4355910963?check_suite_focus=true#step:6:186)

```sh
#10 6.729 perl: warning: Setting locale failed.
#10 6.729 perl: warning: Please check that your locale settings:
#10 6.729 	LANGUAGE = (unset),
#10 6.729 	LC_ALL = "en_US.UTF-8",
#10 6.730 	LANG = "en_US.UTF-8"
#10 6.730     are supported and installed on your system.
#10 6.730 perl: warning: Falling back to the standard locale ("C").
```

I can't really tell whether it succeeds in the end. I just noticed that the following code [is recommended](https://github.com/docker-library/docs/tree/master/ubuntu#locales) for the official Ubuntu image:

```sh
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
```

**Comment by cboettig** [comment]
Thanks @dpprdan .  We do install locales and configure as such:

https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_R.sh#L59-L61

but maybe we ought to switch to that recommended way using  `localedef` instead?  

We also set LANG, https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/r-ver_4.1.2.Dockerfile#L11, but maybe that needs to be `utf8` instead of `UTF-8`?  I'm not really up-to-speed on locale issues, @eddelbuettel probably knows more about this.  Dirk, would you recommend we set locales as Daniel recommends above instead?  Or is something else the issue here perhaps?

**Comment by eddelbuettel** [comment]
Yes, saw this issue, scratched my head, remember I have seen it too.  Like you, I think it has to do with which locales are installed. and maybe something (or a value) is missing. But I do not recall what I did to nip this myself.  The answer is likely tucked away in one of my containers -- if `rocker/r-base` does not have it, see what it does that the (similar but different) `versioned2` does not.

**Comment by dpprdan** [comment]
> I can't really tell whether it succeeds in the end.

I've built `r-ver` [on GitLab](https://gitlab.com/dpprdan/rocker_locale/) and [my tests confirm](https://gitlab.com/dpprdan/rocker_locale/-/jobs/1850050923#L107) that the locale is set to `en_US.UTF-8` in the end. 

So it is just a matter of getting rid of those pesky warnings.

The `r-base` Dockerfile seems more or less the same as `r-ver`, though in somewhat different order:

https://github.com/rocker-org/rocker/blob/df1414259dceb0282f163f29f4dccfa184d38d86/r-base/4.1.2/Dockerfile#L18-L35

My hunch is that setting the ENV vars before installing the locale package in `r-ver` may be causing the warning. 
Or maybe that the ENV vars are set both in the Dockerfile and the `install_R.sh` script.

**Comment by dpprdan** [comment]
Confirmed my hunch that setting the ENV vars before the locale package is available is causing the warning. 
Setting `ENV LANG` [after](https://gitlab.com/dpprdan/rocker_locale/-/blob/5f7a88ca2fbb7357464536c0ba4ddfbced86cb0b/Dockerfile) the `install_R.sh` script is run get's rid of the warnings re: locale (see [this build log](https://gitlab.com/dpprdan/rocker_locale/-/jobs/1874496302) and [this test log](https://gitlab.com/dpprdan/rocker_locale/-/jobs/1874496304) confirm that the locale is set.).

I am [using](https://gitlab.com/dpprdan/rocker_locale/-/blob/5f7a88ca2fbb7357464536c0ba4ddfbced86cb0b/scripts/install_R.sh#L8) the [recommended](https://github.com/docker-library/docs/tree/master/ubuntu#locales) setup (via localedef) here, which is also recommended for [Debian](https://github.com/docker-library/docs/tree/master/debian#locales), BTW. It is essentially identical to using local-gen as used by rocker, because, as the [locale-gen manpage](https://manpages.ubuntu.com/manpages/focal/man8/locale-gen.8.html) says:

> locale-gen is a program that reads the file /etc/locale.gen and invokes localedef for the chosen  localisation profiles.

Since we are only generating one locale, localedef should be sufficient, I suppose. Apparently it is also not necessary to update `/etc/default/locale`?!

Finally, I've also _not_ set `LC_ALL`, since it is strongly discouraged e.g. in the [Debian wiki](https://wiki.debian.org/Locale#Configuration). 

If you want, @cboettig, I can draft a PR with these changes.

**Comment by cboettig** [comment]
@dpprdan nice, thanks!  a PR on that would be great
