### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by kondofersky** [rocker-org/rocker-versioned2#304]
Hi all,
I am getting a little desperate as I am simply not able to upgrade to the `rocker-versioned2` system. I have been using `rocker-versioned` for quite some time but want to now finally move on. I think I am very close though and hope to get a little help from the pros.

**Problem:**
After starting a container and accessing the RStudio Server, everything looks normal. Opening an R script, typing `library(ggplot2)` and sending it to the console also works fine. However, after quitting the current R session (via the red switch in the uper right) and then starting a new session, the command `library(ggplot2)` runs into 4 error messages:

```
2021-12-06T20:36:37.201638Z [rsession-rstudio] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXPREC* rstudio::r::options::getOption(const string&) src/cpp/r/ROptions.cpp:83
2021-12-06T20:36:37.201767Z [rsession-rstudio] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) src/cpp/r/RExec.cpp:140
2021-12-06T20:36:37.402003Z [rsession-rstudio] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXPREC* rstudio::r::options::getOption(const string&) src/cpp/r/ROptions.cpp:83
2021-12-06T20:36:37.402089Z [rsession-rstudio] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) src/cpp/r/RExec.cpp:140
Error: package or namespace load failed for ‘ggplot2’ in is(fdef, "genericFunction"):
 object 'class2' not found
```

Quitting again, starting a new session and again running `library(ggplot2)`, results in two error messages:

```
2021-12-06T20:38:35.009816Z [rsession-rstudio] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXPREC* rstudio::r::options::getOption(const string&) src/cpp/r/ROptions.cpp:83
2021-12-06T20:38:35.010048Z [rsession-rstudio] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) src/cpp/r/RExec.cpp:140
```

and then the server hangs itself. Restarting the browser produces a core dump of 2,2GB, and again running `library(ggplot2)`, results in another two a bit different error messages:

```
2021-12-06T20:41:21.065412Z [rsession-rstudio] ERROR R.getOption: rstudio.errors.suppressed made from non-main thread; LOGGED FROM: SEXPREC* rstudio::r::options::getOption(const string&) src/cpp/r/ROptions.cpp:83
2021-12-06T20:41:21.065606Z [rsession-rstudio] ERROR evaluateExpression called from thread other than main; LOGGED FROM: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) src/cpp/r/RExec.cpp:140
Error: package or namespace load failed for ‘ggplot2’ in get0(x, envir = env, inherits = inherits, ifnotfound = myObj):
 invalid 'inherits' argument
```

**Steps to reproduce:**
```
docker pull rocker/tidyverse
#(alternatively: docker pull rocker/tidyverse:4.1.1, same behaviour)
docker run -d -e PASSWORD=mypass -p 9999:8787 --name rocker docker.io/rocker/tidyverse
#then start server:9999 and repeat steps from above
```

**System**
`CentOS Linux release 7.9.2009 (Core)`

**Docker Info**

```
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-1160.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
ID: T2X2:ZB5W:ZV6E:QQM7:6LFE:UF24:TIEV:I6UL:KZLG:SMHQ:LCVE:HKB2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Final words**
The described behaviour does not happen in console if I `docker exec` the container and run `sudo R`... I also cannot guarantee, that it happens only with `ggplot2`. I noticed however, that e.g. with `magrittr` it does not seem to be an issue...
I would really appreciate if someone finds what I am doing wrong. The rocker project is really awesome and I would like to continue to use it. If I can't solve this, I would go back to my old debian-based image and then try to upgrade R in there, however this seems like a terrible approach... Thank you very much for looking into this!

**Comment by eitsupi** [comment]
I think this could be a problem between the RStudio Server version and the Linux kernel version.
The Docker version is also very old, but that may not matter this time.

It is possible that you can solve this problem by installing an older RStudio, but the older RStudio may not be compatible with the newer version of R.
If you don't need the new R, then you may be able to use an image that has the old R version as its tag.
For example, if you try `rocker/tidyverse:4.0.0` with RStudio Server 1.3.959 installed, do you get an error?
https://github.com/rocker-org/rocker-versioned2/wiki/tidyverse_280f3c6b153e

**Comment by kondofersky** [comment]
Hi @eitsupi and thank you very much for your help!

Your solution did work! I tried the `rocker/tidyverse:4.0.0` Version and at least until do not experience problems. I can also confirm that the rstudio-server version is: `1.3.959 (Middlemist Red) for Ubuntu Bionic`. Thanks again!

I have two follow-up questions:
1) Upgrading to 4.1.2 and above would be now possible with `sudo apt install r-base`? This way I would stay on the old version of rstudio-server but would use the newer R. Or would you recommend another approach?
2) (Please excuse my almost nonexistant knowledge on this topic) The kernel version is `3.10.0-1160.21.1.el7.x86_64`. If I upgrade it via `sudo apt-get dist-upgrade`, do I risk that suddenly all the docker images/containers and other software stop working or is this something you would recommend?

Thanks a lot again, it was really helpful!

**Comment by eitsupi** [comment]
> Upgrading to 4.1.2 and above would be now possible with `sudo apt install r-base`? This way I would stay on the old version of rstudio-server but would use the newer R. Or would you recommend another approach?

In this repository, R is installed from the source code, and I don't think it is supposed to be re-installed.
RStudioServer, on the other hand, can be easily reinstalled.

You can try to install any version of RStudio Server on `rocker/tidyverse:4.1.2` with a Dockerfile like the following.

```Dockerfile
FROM rocker/tidyverse:4.1.2
RUN /rocker_scripts/install_rstudio.sh 1.3.959
```

However, as I mentioned earlier, I don't know if the combination of the old RStudio Server and the new R will work properly.

> The kernel version is `3.10.0-1160.21.1.el7.x86_64`. If I upgrade it via `sudo apt-get dist-upgrade`, do I risk that suddenly all the docker images/containers and other software stop working or is this something you would recommend?

Since Docker containers shares the Linux kernel with the Docker host (Try running the `uname -a` command inside the containers.), I don't think it is possible to upgrade the Linux kernel as long as you are using CentOS 7.

The RStudio Server installed on `rocker/rstudio` is for Debian, now Debian 10, and the Linux kernel version for Debian 10 is 4.19 or higher.
Since RStudio Server for CentOS 7 exists separately from this, you might want to consider installing R and RStudio Server on a Docker image of CentOS 7.

For example, some of the Docker images that RStudio builds seem to be based on CentOS7.
If you install the latest RStudioServer on it (which should not be too difficult), you can expect it to work properly.
https://github.com/rstudio/r-docker

**Comment by kondofersky** [comment]
Hi @eitsupi,
Thanks again, you really helped me a lot! I will close the issue and hope that it might be useful for others if they run into the same errors in future.
