### ISSUE TITLE
Warning in RStudio when starting

### ISSUE THREAD

**Issue by wfma** [rocker-org/rocker-versioned2#306]
Hi Folks!

I cant believe I am just discovering this amazing tool! I have begun using Rocker and it has been great for reproducing the exact environment across my computers for analyzing single-cell data.

I have been using rocker/rstudio by the following command 

```
docker run -e DISABLE_AUTH=true -d -v /Users/wm5wt:/home/rstudio/Documents --rm -p 8787:8787 rocker/rstudio
```

And things are running and I can run libraries, etc. However, when I open the localhost:8787 each time theres a warning (with a different date in the beginning)

```
2021-12-07T16:09:01.624157Z [rsession-rstudio] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::__cxx11::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
```
is this anything to be concerned of? 

![Xnip2021-12-07_11-12-57](https://user-images.githubusercontent.com/23326773/145065339-b87e8b21-af77-4c70-b01a-dbd9568abeb8.jpg)

**Comment by cboettig** [comment]
@wfma I think the short answer is  that you can just ignore that, it's just a source of metadata about the memory use of the container I believe.  

Not entirely sure why that's missing for you, maybe specific to the architecture you're running on or your docker config (you could check what  `cat(readLines('/proc/self/cgroup'))` shows, if anything?).  RStudio is a bit verbose about reporting these 'warning messages' to the user's console, when this is really a low-level warning that should probably be redirected to some administrator log file I think.  There's a range of these `rstudio::core::system`  messages that RStudio produces in the R console that can all be ignored (fortunately or unfortunately).

**Comment by wfma** [comment]
Hi! Thank you for quickly helping me with this issue! When I run that command I get a weird output:

'''
> cat(readLines('/proc/self/cgroup'))
0::/
'''

I have noticed that when rstudio autosaves it pops up a BUNCH of red error codes and would also alert me that it cant autosave (despite that the saving feature works as well as file explorer). Pretty strange. I will follow up if it affects function.

Wei

**Comment by wfma** [comment]
This is the warning that it comes up while autosaving.

ps i am just running it via Docker on a mac!

![image](https://user-images.githubusercontent.com/23326773/145463876-5b791642-8a4a-43b3-b0cc-4ca956478dd5.png)
![image](https://user-images.githubusercontent.com/23326773/145463947-3f1c4130-017c-4afb-a82f-4413124e6470.png)

**Comment by wfma** [comment]
It has been popping up with this error, but manually saving works! So strange.

![image](https://user-images.githubusercontent.com/23326773/145688243-69b81350-c0db-4beb-85e9-c1b8a35b7044.png)

**Comment by eitsupi** [comment]
This may be a problem that generally occurs when bind-mounting a Mac OS file system.
I recommend looking for information about Docker Desktop for Mac.
https://www.docker.com/blog/user-guided-caching-in-docker-for-mac/

**Comment by wfma** [comment]
thank you! ill look into this today and post back with updates.

**Comment by ShichenXie** [comment]
> Hi Folks!
> 
> I cant believe I am just discovering this amazing tool! I have begun using Rocker and it has been great for reproducing the exact environment across my computers for analyzing single-cell data.
> 
> I have been using rocker/rstudio by the following command
> 
> ```
> docker run -e DISABLE_AUTH=true -d -v /Users/wm5wt:/home/rstudio/Documents --rm -p 8787:8787 rocker/rstudio
> ```
> 
> And things are running and I can run libraries, etc. However, when I open the localhost:8787 each time theres a warning (with a different date in the beginning)
> 
> ```
> 2021-12-07T16:09:01.624157Z [rsession-rstudio] WARNING No memory control group found in /proc/self/cgroup; LOGGED FROM: std::__cxx11::string rstudio::core::system::{anonymous}::getMemoryCgroup() src/cpp/core/system/LinuxResources.cpp:335
> ```
> 
> is this anything to be concerned of?
> 
> ![Xnip2021-12-07_11-12-57](https://user-images.githubusercontent.com/23326773/145065339-b87e8b21-af77-4c70-b01a-dbd9568abeb8.jpg)

I have the same issue.

**Comment by cboettig** [comment]
Thanks @ShichenXie .  I believe you can ignore the Warning.  IMHO RStudio really should not be logging these warnings to the R console, but AFIK we do not have the ability to redirect them in the open source version. I have reported the issue to RStudio as linked above.
