### ISSUE TITLE
Problem Rendering Rmd Files to PDF

### ISSUE THREAD

**Issue by RERobbins** [rocker-org/rocker-versioned2#317]
I am running rocker/geospatial inside a fresh install of Ubuntu server running on my network.

I invoke the system with:

``docker run -v /home/MY_USER_NAME_HERE:/home/rstudio -p 8787:8787 -d -e PASSWORD=MY_PASSWORD_HERE -e USERID=1001 rocker/geospatial``

When I attempt to knit a bare-bones Rmd file to PDF the conversion by LaTex fails with the following log information:

```
! kpathsea: Running mktexfmt pdflatex.fmt
! mktexfmt [ERROR]: -user mode but path setup is -sys type, bailing out.
```
I would very much like to run RStudio from one of the Rocker containers, but need to be able to knit Rmd to PDF.

**Comment by eddelbuettel** [comment]
:-/  

To a rough first approximation the world is roughly divided into people that think tinytex helps (which it probably does on Windows or macOS) and those grumpy folks like myself who feel that it tends to get in the way (on Linux where things often work just fine without it).  The Rocker containers I look after tend to be 'skinny' and not even bother with the (large) footprint of texlive but I a) do run that merrily on my normal machines and I b) once did a container just for rmarkdown-to-pdf work including some (at least at the time) more esoteric fonts.  You could look into that one [1] and bring the command over to the rstudio container and enhance it as the versioned stack below the geospatial container will likely stick with tinytex as it is lighterweight.

[1] https://github.com/rocker-org/rocker/blob/master/r-rmd/Dockerfile -- but the file is dated so this may not actually work

**Comment by RERobbins** [comment]
Thank you very much for that explanation @eddelbuettel -- so it sounds like I should not devote a lot of time banging my head against the wall on this one.

**Comment by cboettig** [comment]
@RERobbins yeah, apologies. Can you share what your minimal Rmd was?  Can you also provide more of the error log you see? (sometimes the missing file is mentioned further up and a manual tlmgr install will fix it).  


I just tested on a fresh pull of a vanilla `rocker/geospatial` using the default Rmd pdf created by the rmarkdown pdf template (new Rmd -> pdf format from the File menu), and it took a long time to install the needed packages after I hit knit button but it did work and render the PDF.  

That said, I totally hear you, manual tlmgr installs are a pain in the behind and are proving pretty fragile.  apt-get texlive just works like Dirk says.  But just as a possible quick fix,  did you try `tinytex::install_tinytex()` first and then try knitting again?  

`rocker/geospatial`  ships with a very minimal tlmgr installation that is intended to work across multiple users but may need some additional love right now, and occassional hand-holding on fonts.  Yihui's tinytex is less stripped-down, but not really designed well for providing a tex library that can be shared across multiple users, so the above command will install for a single user's home directory (which seems to be the fashion these days anyway) but has a greater chance of working out of the box.  

Can't say I'm really in either camp, tinytex (really this means custom texlive installation with tlmgr instead of apt getting texlive debs; not specific to the R package tinytex) in my experience does require a lot more hand-holding, but getting all the fonts I use from texlive debs adds a bout 4 GB, which is a lot even in these already large images).

**Comment by eddelbuettel** [comment]
"Between a rock and a hard place problem" though because I think on the machine that I type this, all of the `texlive-*` adds to over 1 gb ....   There just aren't any clever subsets besides the 'need-based-on-demand' idea of tinytex which isn't all wrong.  (I just continue to wish it were smarter about reusing an existing, say, texlive when it sees it.)

**Comment by RERobbins** [comment]
@cboettig My Rmd file consists of nothing more than `# Hello World`

The log file, in its entirety, reads as follows:

```
! kpathsea: Running mktexfmt pdflatex.fmt
! mktexfmt [ERROR]: -user mode but path setup is -sys type, bailing out.
```
The render tab in R Studio is as follows:
```
  |......................................................................| 100%
  ordinary text without R code


/usr/lib/rstudio-server/bin/pandoc/pandoc +RTS -K512m -RTS hello_world.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output hello_world.tex --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' 

processing file: hello_world.Rmd
output file: hello_world.knit.md

! kpathsea: Running mktexfmt pdflatex.fmt

! mktexfmt [ERROR]: -user mode but path setup is -sys type, bailing out.

Error: LaTeX failed to compile hello_world.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See hello_world.log for more info.
Execution halted
```

**Comment by eddelbuettel** [comment]
I was briefly curious if the lack of a YAML header would drive this, but no.  Works fine here:

```r
> render("demo.Rmd", "pdf_document")


processing file: demo.Rmd
  |..............................................................................................................................................................................................| 100%
  ordinary text without R code


output file: demo.knit.md

/usr/bin/pandoc +RTS -K512m -RTS demo.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output demo.tex --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' 

Output created: demo.pdf
> 
```

Standard Ubuntu 21.04

**Comment by RERobbins** [comment]
I am running an install of Ubuntu 20.04.3 LTS and invoking docker as noted at the top of this thread.

Any thoughts on how I might debug this?

Suggestions as to how I should proceed?

I am using the Knit button to kick off the process, should I be doing something else?

**Comment by eddelbuettel** [comment]
(To clarify: the Docker container may well miss something as discussed.  I just confirmed that normal texlive, called the same way, has no issue.)

**Comment by RERobbins** [comment]
Thanks for that clarification.

**Comment by eddelbuettel** [comment]
Good point.  Seems to run:

```sh
edd@rob:/tmp/rocker_bug317$ dkrrr rocker/geospatial bash                                                 
root@3597a6a865a8:/work# R   
                                                    
R version 4.1.2 (2021-11-01) -- "Bird Hippie"                                                            
Copyright (C) 2021 The R Foundation for Statistical Computing              
Platform: x86_64-pc-linux-gnu (64-bit)                                                                                                                                                                             
                                                    
R is free software and comes with ABSOLUTELY NO WARRANTY.                                                
You are welcome to redistribute it under certain conditions.                                             
Type 'license()' or 'licence()' for distribution details.                                                
                                                    
  Natural language support but running in an English locale       
                                                                                                         
R is a collaborative project with many contributors.                                                                                                                                                               
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.                                             
                                                    
Type 'demo()' for some demos, 'help()' for on-line help, or                                              
'help.start()' for an HTML browser interface to help.                                                    
Type 'q()' to quit R.                                                                                    
                                                                                                         
> rmarkdown::render("demo.Rmd", "pdf_document")                                                                                                                                                                    
                                                    
                                                    
processing file: demo.Rmd                                                                                
  |......................................................................| 100%
  ordinary text without R code                                                                                                                                                                                     
                                                    
                                                    
output file: demo.knit.md
                                                    
/usr/local/bin/pandoc +RTS -K512m -RTS demo.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output demo.tex --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pa
gebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in'   
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)                                                                                                     
[1/2, ??:??/??:??] install: amsmath [31k]           
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)                                                                                            [0/17809]
[1/2, ??:??/??:??] install: amsmath [31k]
[2/2, 00:00/00:00] install: latex-amsmath-dev [30k]
running mktexlsr ...        
done running mktexlsr.      
running mtxrun --generate ...
done running mtxrun --generate.
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log                                       
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log    
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)                                                                                                     
[1/1, ??:??/??:??] install: iftex [3k]
running mktexlsr ...                                                                                     
done running mktexlsr.                                                                                   
running mtxrun --generate ...
done running mtxrun --generate.                     
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log                                       
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)                                                                                                     
[1/1, ??:??/??:??] install: kvoptions [7k]          
running mktexlsr ...                                                                                     
done running mktexlsr.                                                                                   
running mtxrun --generate ...                                                                            
done running mtxrun --generate.                     
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log                              
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)                                                                                                     
[1/1, ??:??/??:??] install: ltxcmds [5k]      
running mktexlsr ...                                                                                     
done running mktexlsr.                              
running mtxrun --generate ...                                                                            
done running mtxrun --generate.                                                                          
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log                                       
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log                              
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)                                                                                                     
[1/1, ??:??/??:??] install: kvsetkeys [4k]    
running mktexlsr ...              
done running mktexlsr.                                                                                                                                                                                             
running mtxrun --generate ...                       
done running mtxrun --generate.                     
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log                                       
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log    
tlmgr: package repository https://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)                                                                                                     
[1/1, ??:??/??:??] install: etoolbox [9k]           
running mktexlsr ...                                
done running mktexlsr.   
running mtxrun --generate ...                       
done running mtxrun --generate.                                                                                                                                                                                    
tlmgr: package log updated: /opt/texlive/texmf-var/web2c/tlmgr.log                                                                                                                                                 
tlmgr: command log updated: /opt/texlive/texmf-var/web2c/tlmgr-commands.log          

Output created: demo.pdf
> 
```

At the last step it sat for a good moment.  I had just pulled the container to ensure it is fresh and launched with a standard alias I use here:

```sh
edd@rob:/tmp/rocker_bug317$ alias | grep dkrrr
alias dkrrr='docker run --rm -ti -v$(pwd):/work -w /work'
edd@rob:/tmp/rocker_bug317$ 
```

So maybe no bug?

**Comment by RERobbins** [comment]
Do you think there's anything odd about how I invoke docker?  Please note that I am setting a USERID environment variable to correspond to the UID I want files to have when written to my volume.  The error seems to be related to the user.

**Comment by eddelbuettel** [comment]
Yeah that was my only thought too.  But I can't help much further -- I run RStudio outside Docker, and I tend to not use tinytex.

**Comment by RERobbins** [comment]
Thanks @eddelbuettel.

@cboettig -- any guidance on how to proceed?

**Comment by cboettig** [comment]
@RERobbins I'm not following what you are doing I'm afraid, so I cannot reproduce it and trouble shoot.  

How are you invoking docker?  Please try:

```r
docker pull rocker/geospatial
docker run --rm -ti -p 8787:8787 rocker/geospatial
```
logging in with the auto-generated password, and see if you can render your Rmd?

You say that your Rmd is nothing but `# Hello World` (i.e. no yaml header?) but that you are using the knit button in RStudio -- I assume the drop-down option then that says knit-to-pdf? (Otherwise without a yaml header to set the default output to `pdf_document` or a call to `render` like Dirk shows you wouldn't get pdf/latex output anyway).  When I try that in RStudio I get the same tlmgr log Dirk shows above.  

It's definitely possible something is up with the USERID that is throwing some kind of permission error, (though the logs you show don't support that).  Have you tried doing `tinytex::install_tinytex()` first yet to see if that gets you going?

**Comment by RERobbins** [comment]
@cboettig My command-line invocation is at the start of this thread.

It's....

`docker run -v /home/MY_USER_NAME_HERE:/home/rstudio -p 8787:8787 -d -e PASSWORD=MY_PASSWORD_HERE -e USERID=1001 rocker/geospatial`

And my example is just the simplest I could create that demonstrates the issue.

I will play around with the command line form you showed.

I will not be surprised to discover that the USERID environment variable is involved in the problem I see.

I will play around and report back.

Thanks!

-- Rich

**Comment by RERobbins** [comment]
The problem appears to relate to invoking docker detached.

When I use: `docker run --rm -ti -p 8787:8787 rocker/geospatial`

I am able to knit my Rmd files to pdf files without difficulty.

However, when I use: `docker run -d -ti -p 8787:8787 rocker/geospatial`

I am unable to knit any Rmd file to pdf.

When I go back to my original docker invocation (see the top of this thread) but stop using -d, things work.  I suppose I can live without running detached, but it has proven very nice.

For test purposes, I used the attached Rmd file (stuffed in a zip).

[test.zip](https://github.com/rocker-org/rocker-versioned2/files/7826027/test.zip)

**Comment by cboettig** [comment]
Ah right, sorry I missed the invocation above.   Hmm, still works fine for me using detached mode (that sounds very weird, never seen detached mode change the behavior!)  

Are you sure you're logging into the newly created container when you run in detached mode?  (i.e. note that in the code above, you would have to first use `docker ps` to check the container id of the detached container on port 8787, and then `docker logs` to see the random password that was auto-generated; I assume that's what you did?  If not you might be logging into a stale container?)  

Definitely a strange case! What docker version do you have? 

(For comparison, I've tested on `Docker version 20.10.7, build 20.10.7-0ubuntu5.1` and 

```
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:37:06 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by RERobbins** [comment]
And now I am finding that things that failed last night appear to work.  I fear I have been wasting your time.  I need to pull this thing apart and really understand what I am looking at before bugging you.  Thank you for your indulgence @cboettig 

By the way, in your examples, you consistently rely on random passwords.  Do you do so because it's good practice or is there a deeper reason?  In my case, this setup is for purely personal use in a secure environment.  It is more convenient for me to use the PASSWORD environment variable (which I have resisted for this particular exercise based on your examples).

A thousand thanks.

-- Rich

**Comment by cboettig** [comment]
glad things are working and no worries -- Rocker is really a community effort, we depend on users for bug reports and all kinds of contributions!

nope, I was just going with random password for no good reason really, just makes the copy-paste example a bit more concise I guess.
