### ISSUE TITLE
Select the RStudio Daily build to install

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#324]
Currently, RStudio daily builds are released on a branch-by-branch basis.

https://dailies.rstudio.com/rstudio/
![image](https://user-images.githubusercontent.com/50911393/148746072-fec01c15-fd2f-4563-8a4d-bde45dd2ba3c.png)

Now, `rocker/rstudio:latest-daily` seems to be installing the latest build of the newest branch (2022.06).
![image](https://user-images.githubusercontent.com/50911393/148748028-2064bde4-a563-4800-b923-9a3001bb4df3.png)

But, it seems that what is downloaded with the fixed link (https://rstudio.org/download/latest/daily/server/bionic/rstudio-server-latest-amd64.deb) to daily build is now the 2022.02 branch (next release version) build.
https://dailies.rstudio.com/links/

How about rewriting the RStudio Server installation script so that it downloads from a fixed link when `latest`, `daily`, or `preview` is specified, and downloads the daily build of other branches when a version is specified (e.g. `2022.06.0-daily-4`)?

**Comment by cboettig** [comment]
:+1:
