### ISSUE TITLE
Switch the CRAN URLs to Calendar-based URLs

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#325]
The CRAN URLs for R4.0.0 and R4.0.1 images do not contain dates, so it is difficult to know what dates the snapshot were taken.

https://github.com/rocker-org/rocker-versioned2/blob/756d2cb0b1e192e5eb21d133926ff8fb793747f2/dockerfiles/r-ver_4.0.0.Dockerfile#L11
https://github.com/rocker-org/rocker-versioned2/blob/756d2cb0b1e192e5eb21d133926ff8fb793747f2/dockerfiles/r-ver_4.0.1.Dockerfile#L11

Since the UI of RStudio Public Package Manager has been changed, we cannot know what day the non-Calendar-based URL was a snapshot of by browsing, but we can check the correspondence with the Calendar-based URL by running the following code.

``` r
pkgs_291 <- readLines("https://packagemanager.rstudio.com/cran/291/src/contrib/PACKAGES")
pkgs_296 <- readLines("https://packagemanager.rstudio.com/cran/296/src/contrib/PACKAGES")

pkgs_20200608 <- readLines("https://packagemanager.rstudio.com/cran/2020-06-08/src/contrib/PACKAGES")
pkgs_20200625 <- readLines("https://packagemanager.rstudio.com/cran/2020-06-25/src/contrib/PACKAGES")

setequal(pkgs_291, pkgs_20200608)
#> [1] TRUE
setequal(pkgs_296, pkgs_20200625)
#> [1] TRUE
```

<sup>Created on 2022-01-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In other words, R4.0.0 is pinned to `2020-06-08` and R4.0.1 is pinned to `2020-06-25` now.
How about replacing the URL with one that includes these dates?

By the way, the release date of R4.0.1 was `2020-06-06`, and the release date of R4.0.2 was `2020-06-22`.
As you can see by checking the date-based URLs, the CRAN mirrors currently set for R4.0.0 and R4.0.1 are after the R4.0.1 and R4.0.2 releases, respectively, which violates the principles of this repository.
Is it possible to change the date of URLs, just like you changed the date of a previous image in #127 ?

https://github.com/rocker-org/rocker-versioned2/commit/da083d4c0181cd396304c413d4996ec264475a31#diff-91d27950d08b6c13b886f621cd468bd42d9ca49326d0740d8b407adbd5caa023L13

I don't think that fixing the patch releases prior to R4.0.5, the last patch release of R4.0, to more appropriate URLs will have much impact.
So if I can get consent, I will submit a PR to correct this.

**Comment by cboettig** [comment]
Excellent, thanks for updating this.  RSPM didn't have the date-based mechanism at the time these were pinned.  Yes, I think we should correct the dates here to conform to the policy, as in #127.  A PR would be great!
