### ISSUE TITLE
Debian snapshots

### ISSUE THREAD

**Issue by kforner** [rocker-org/rocker-versioned2#330]
Hello,
Not an issue: just a remark.

Debian snapshots are very useful to have a reproducible environment: users of a given rocker-based image are guaranteed that a `apt install xxx` will always install the same version, which can be extremely useful in some contexts.

This is no longer possible to use with **rocker-org/rocker-versioned2** images now using **ubuntu**, which does not seem to have an equivalent snapshot system.

I'm sure you had excellent reasons to switch from debian to ubuntu. 
Just adding this information in case you have to decide between debian and ubuntu again.

Thanks for this incredibly useful work!
Karl

**Comment by cboettig** [comment]
Note that Ubuntu based images are pinned to a specific Ubuntu LTS release (currently Ubuntu `focal`), just as the debian-based 3.x series in rocker-versioned is pinned to specific debian releases (`wheezy`, `jessie`, `stretch`, `buster`).  I'm not an expert on the differences actually, maybe you could be a bit more precise?  

e.g. I believe on even on the stable debian releases, it was not the case that `apt install <package>` was precisely the same version each time (i.e. that would imply `apt-get upgrade` never did anything, and specifically that no packages could receive security updates). My understanding is that the debian stable releases, like the ubuntu LTS releases, are 'maintained' for a given window of time, meaning that during that window, the packages do receive patches, but do not receive new feature upgrades.  

For example, Ubuntu `focal` ships with gcc 9.3.0, while the current ubuntu release (21.10) ships with gcc `11.2`.  I believe the ubuntu LTS release version for gcc is stable -- it will never move to gcc 10, but it will continue to receive patches for it's maintained lifetime (a whopping 10 years in the case of Ubuntu focal!  ([typically](https://wiki.debian.org/LTS) for  2 years in the case of `debian`). For example, we can see that `focal` continues to get updated versions of the `ca-certificates` package, which iiuc will allow it to continue to work with modern browser commands as older certificates expire:

```
apt-cache show ca-certificates | grep Version
Version: 20210119~20.04.2
Version: 20190110ubuntu1
```

Debian seems to distinguish between what it calls it's security team and the LTS team (largely volunteers), and Ubuntu's Canonical I believe piggybacks on most of the debian stable maintenance, but I'm not aware of differences in policies.  Can you give an example of where a package has been updated in a ubuntu LTS release but not in a debian LTS release?
I have never been precisely clear how either the Debian or Ubuntu teams decide how to update/patch packages on stable releases vs the adding new versions to later releases, though @eddelbuettel has been doing this for decades at debian and can probably fill us in :-)


As for the motivation for the change, there were a few factors:
- Compatibility with RStudio binary installs over RSPM
- Compatibility with nvdia-cuda Ubuntu-based images (for GPU-accelerated / ML work)
- Longer maintenance window of Ubuntu LTS


HTH!

**Comment by kforner** [comment]
Thanks Carl for that very elaborated reply. 

My context is an environment where I have to control reproducibility over time not only on the main docker image, but on all derived project docker images. Each analysis project can customize the main docker image.
For achieving true reproducibility, you must be able
-  to rebuild the project images
- if different people build a project image, at different times and on different computers, they should get the same image.
This reproducibility should also be able to reproduce bugs.
So if a bug is due somehow by a system package, that gets fixed at one point, you can not investigate nor reproduce it.

Using debian snapshots we could fix a date for the system packages (as RSPM does for R packages) to control that.

I understand what you explained about system packages being updated for patches, and I suppose that's fine. 
We can probably work-around true reproducibility, or compromise it a bit. 

But I still think for rocker/versioned it could make sense to control in a deterministic way the set of system packages.
And I agree that your arguments for ubuntu make perfect sense.

Best,

**Comment by benz0li** [comment]
@kforner You might be interested in

*  [registry.gitlab.b-data.ch/r/r-ver](https://gitlab.b-data.ch/r/r-ver/container_registry)  
*  [registry.gitlab.b-data.ch/rocker/rstudio](https://gitlab.b-data.ch/rocker/rstudio/container_registry)
*  [registry.gitlab.b-data.ch/rocker/tidyverse](https://gitlab.b-data.ch/rocker/tidyverse/container_registry)
*  [registry.gitlab.b-data.ch/rocker/verse](https://gitlab.b-data.ch/rocker/verse/container_registry)
*  [registry.gitlab.b-data.ch/rocker/geospatial](https://gitlab.b-data.ch/rocker/geospatial/container_registry)

then: Based on [rocker-org/rocker-versioned](https://github.com/rocker-org/rocker-versioned) and thus on Debian. Note:

1.  `MRAN` date for _frozen_ image version = [Release date](https://cran.r-project.org/src/base/R-4/) of next R version.
2.  Git version = latest available Git version at `MRAN` date.  
    👉 Copied from [Git source-installation](https://gitlab.b-data.ch/git/gsi/container_registry) image.

Although I have [moved to Jupyter (JupyterHub with JupyterLab + code-server)](https://github.com/rocker-org/rocker-versioned2/pull/295#issuecomment-1008308500) for some time now, I try to keep these images up-to-date on a best effort basis.  
ℹ️ All my [JupyterLab docker images](https://gitlab.b-data.ch/jupyterlab/r) are multi-arch (`linux/amd64`, `linux/arm64/v8`) and Debian-based.

---

[Garbage collection](https://docs.docker.com/registry/garbage-collection/) is run on this registry, i.e. blobs are removed when they are no longer referenced by a manifest.  
👉 Use `tags` to pin these images, as I don't have the space to keep every version (`sha256 digest`) of an image.

**Comment by eitsupi** [comment]
I believe the answers to the questions have been given, so I will close this.
