### ISSUE TITLE
Are there log4j vulnerabilities in rocker?

### ISSUE THREAD

**Issue by rwaaijman** [rocker-org/rocker-versioned2#333]
Hi, 
Just wondering if there are any vulnerabilities when using rocker (also in older R-versions (3.x))?
I read that shiny server doesn't use log4j, but I'm unsure about the rocker docker?
Best regards

**Comment by cboettig** [comment]
I think the way to think about this is primarily through the lens of the linux distribution or whomever is providing the upstream software.  In general, pulling a recently-rebuilt image (note the 3.x images are no longer automatically rebuilt regularly, but most 4.x are) running `apt-get update && apt-get -y upgrade` on an existing container should keep most of the core software updated during the lifetime of their base release.  

The 3.x series are built on specific debian release versions which continue to receive security updates for a defined lifetime (~2 yrs), while the 4.x are built on ubuntu LTS releases (currently 20.04) which is actively maintained by the Canonical to receive such security patches for 10 years.  Of course it is possible to install software from other sources than apt-get from these official repos, and thus add software that is not covered by these security teams (which includes R, R packages, RStudio, and shiny).  So if there was a vulnerability in say, RStudio server or shiny, I imagine it would persist on the versioned images which by default install the same version of those platforms each time (I don't know if RStudio ever patches the sources of old binary versions with respect to security vulnerabilities).

For more detail, see discussion in #330.

I'm not a security expert and happy for input from those with more experience in this arena too.

**Comment by rwaaijman** [comment]
Hi Carl, 
thank you very much for the explanation, very helpful

**Comment by nreith** [comment]
Hi guys,
I see that there are actually a lot of npm vulnerabilities in the final most recent image, especially in subfolders of /opt/shiny-server/node_modules.
Do you have any suggestions for handling these? When I upgrade specific minor/patch versions of some of those, they bring other dependencies and it becomes a game of whack-a-mole.

**Comment by eitsupi** [comment]
@nreith `rocker/shiny` installed the latest shiny-server.
I believe the vulnerability comes from shiny-server, so please take a look at this repository.
https://github.com/rstudio/shiny-server

**Comment by nreith** [comment]
I didn't ultimately find log4j, but if you do come across it, there's an excellent package called reload4j with its sidekick slf4j_log4j that are drop in replacements for the vulnerable ones.

https://github.com/qos-ch/reload4j
https://www.slf4j.org/manual.html

Below is a script I wrote to automate search and destroy of log4j1.x vulnerabilities and so far it has seemed to work. Just requires your own maven xml config, which you can get from the maven repos.

```bash
#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. &>/dev/null && pwd -P)

function setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]
  then
    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
  # Example usage to turn colors on and off.
  #  msg "This is a ${RED}very important${NOFORMAT} message, but not a script output value!"
  #
  # Color conventions for this repo:
  # RED = error message or failure
  # GREEN = success (such as "DONE")
  # BLUE = Information (distro version, etc.)
  # PURPLE = ?
  # CYAN = Labeling steps
  # YELLOW = ?
}

function msg() {
  # Used if you have any messages to communicate from logic
  echo >&2 -e "${1-}"
}

msg "${GREEN}Fixing all log4j 1.x vulnerabilities by replacing with the latest reload4j...${NOFORMAT}"
msg "${GREEN}Also replacing slf4j-log4j with latest slf4j-reload4j for compatibility...${NOFORMAT}"

config_maven() {
    bash ${DIR}/config-maven.sh
}

function fix_log4j() {
    export LATEST_RELOAD4J=$(wget -q -O - https://github.com/qos-ch/reload4j/tags | sed 's/  *//g' | grep '^v_' | sort -n | tail -n 1 | sed 's/^v_//g')
    export LATEST_SLF4J_RELOAD4J=$(wget -q -O - https://github.com/qos-ch/slf4j/tags | sed 's/  *//g' | grep -v "alpha" | grep '^v_1.' | sort -n | tail -n 1 | sed 's/^v_//g')
    echo "Actions taken:" >| report.txt
    echo "--------------" >> report.txt
    for f in $(find / -type f -name "log4j-1.*[0-9].*.jar" | tr '\n' ' '); do
    cd $(dirname $f)
    export SLF4J_LOG4J=$(ls | grep slf4j-log4j)
    mvn install:install-file -Dfile=${f} -DgroupId=ch.qos.reload4j -DartifactId=reload4j -Dversion=${LATEST_RELOAD4J} -Dpackaging=jar
    mvn install:install-file -Dfile=${SLF4J_LOG4J} -DgroupId=org.slf4j -DartifactId=slf4j-reload4j -Dversion=${LATEST_SLF4J_RELOAD4J} -Dpackaging=jar
    cd -
    echo ""
    echo "Replaced  ${f}" >> report.txt
    echo "    with  reload4j-${LATEST_RELOAD4J}" >> report.txt
    echo "and $(dirname ${f})/${SLF4J_LOG4J}" >> report.txt
    echo "    with slf4j-reload4j-${LATEST_SLF4J_RELOAD4J}" >> report.txt
    echo ""
    done
    msg "${CYAN}$(cat report.txt)${NOFORMAT}"
    rm report.txt
}

if command -v mvn
then
    export LEAVE_MVN="true"
fi

config_maven
fix_log4j
if [[ ${LEAVE_MVN} != "true" ]]
then
    apt-get purge -qq maven
fi
msg "${GREEN}DONE${NOFORMAT}"

```
