### ISSUE TITLE
reconsider openblas defaults for parallelization?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-versioned2#34]
We've seen a few bug reports around openblas, e.g. https://github.com/rocker-org/rocker-versioned/issues/123 and https://stat.ethz.ch/pipermail/r-sig-debian/2020-April/003165.html

It's nice to have parallelized BLAS working out of the box, but this may also be creating some gotchas we would rather avoid.  Thoughts / suggestions?

cc @eddelbuettel

**Comment by eddelbuettel** [comment]
That just came to the r-sig-debian yesterday, and I confirmed that on both current Ubuntu (20.04, use rocker/r-ubuntu:20.04) and Debian (testing, use rocker/r-base) things go _very_ pear-shaped once libopenblas-dev is installed as its libopenblas0-pthread seems to _hang_ R.  Very bad. 

I just posted to the debian-science list where some of the ongoing LAPACK/BLAS work is discussed every now and then.

No resolution that I know other than a) not using OpenBLAS or b) manually preferring the non-pthread libopenblas as in `sudo update-alternatives --config libblas.so.3-x86_64-linux-gnu`.

**Comment by cboettig** [comment]
Thanks. Do you think it would be better to use atlas as the default? Are there other open source parallel linear algebra libraries we should consider?

Re preferring the non-pthread version, is there a way to run `update-alternatives` non-interactively (e.g. in our Dockerfile?) I've only ever done that in an interactive terminal session.  

I'm also not actually familiar with the pthread vs non-pthread distinction in openblas.  Currently we're just installing `libopenblas-dev` 

https://github.com/rocker-org/rocker-versioned2/blob/7e065a9d71b8ff2561f7f53c107129246864021e/scripts/install_R_source.sh#L41
and then I think R is picking that up as the default blas, (we build --with-blas but I think that's to enable a user to switch to R's blas iirc? been a while since I looked at that):
https://github.com/rocker-org/rocker-versioned2/blob/7e065a9d71b8ff2561f7f53c107129246864021e/scripts/install_R_source.sh#L119

How can I tell if I have the pthread version?

**Comment by eddelbuettel** [comment]
Let's maybe wait a moment before the dust settles.  There has already been one [rather helpful follow-up on debian-science](https://lists.debian.org/debian-science/2020/04/msg00082.html).  

To recap, building as we build is still the right way to go. It gives us choice between reference blas (slow, safe), Atlas (not a bad choice, not tuned to cpu), and OpenCPU ("usually" good, parallel) and leaves the door open to things like MKL via the script I posted on GH a while back.

Now, within Debian some update/upgrade/refresh of the BLAS has been happening. That we now get the pthread version that hangs us seems to be a temporary glitch in the matrix.  The message by Seb I referenced above that one can use openblas-openmp or openblas-serial.  I have not had time to test.  _That_ would be my suggested route for our recipes.  

Let's test a little and review.  I suggest no immediate changes, but we need to warn user about the current issue with openblas-pthread.

**Comment by eddelbuettel** [comment]
On the `rocker/r-base` image:

```sh
root@333e9cb350b3:/work# apt-cache search libopenblas
libopenblas-base - Optimized BLAS (linear algebra) library (transitional)
libopenblas-dev - Optimized BLAS (linear algebra) library (dev, meta)
libopenblas-openmp-dev - Optimized BLAS (linear algebra) library (dev, openmp)
libopenblas-pthread-dev - Optimized BLAS (linear algebra) library (dev, pthread)
libopenblas-serial-dev - Optimized BLAS (linear algebra) library (dev, serial)
libopenblas0 - Optimized BLAS (linear algebra) library (meta)
libopenblas0-openmp - Optimized BLAS (linear algebra) library (shared lib, openmp)
libopenblas0-pthread - Optimized BLAS (linear algebra) library (shared lib, pthread)
libopenblas0-serial - Optimized BLAS (linear algebra) library (shared lib, serial)
libopenblas64-0 - Optimized BLAS (linear algebra) library (shared lib, 64bit, meta)
libopenblas64-0-openmp - Optimized BLAS (linear algebra) library (shared lib, 64bit, openmp)
libopenblas64-0-pthread - Optimized BLAS (linear algebra) library (shared lib, 64bit, pthread)
libopenblas64-0-serial - Optimized BLAS (linear algebra) library (shared lib, 64bit, serial)
libopenblas64-dev - Optimized BLAS (linear algebra) library (dev, 64bit, meta)
libopenblas64-openmp-dev - Optimized BLAS (linear algebra) library (dev, 64bit, openmp)
libopenblas64-pthread-dev - Optimized BLAS (linear algebra) library (dev, 64bit, pthread)
libopenblas64-serial-dev - Optimized BLAS (linear algebra) library (dev, 64bit, serial)
root@333e9cb350b3:/work# 
```

**Comment by cboettig** [comment]
Thanks Dirk!  We've been sticking with the meta one, `libopenblas-dev` which I believe is choisng `pthread` flavor now by default.  It looks to have put on weight compared to previous versions, but works rather well.

I believe we'll now also have the option of `nvblas` in our GPU / ML stack, so even more choices!

**Comment by eddelbuettel** [comment]
For what it is worth, I upgraded my box from 19.10 to 20.04 last eve and was bitten by this (again).  

`libopenblas-dev` currently brings in `libopenblas-pthread-dev` by default; that can *lock* the R process.  Installing `libopenblas-openmp-dev` _and removing `libopenblas0-pthread` helped me (again).  

I use a standard i7-8700K cpu.

**Comment by cboettig** [comment]
@eddelbuettel ah, thanks for the report.  yeah, I think we should switch to openmp instead here as well...

**Comment by kforner** [comment]
Is it fair to say that it is no longer possible, with the R provided by rocker/verse:4.1.2, to change the Blas implementation to the standard libBlas ?
If I follow instructions from https://www.rocker-project.org/use/other_topics/:
```
sudo update-alternatives --set libblas.so.3-x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/blas/libblas.so.3
$ R -q -e 'sessionInfo()'
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so
```
probably related to:
```
$ ldd libR.so  | grep blas
	libopenblas.so.0 => /lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f4719522000)
```

**Comment by cboettig** [comment]
@kforner did you try first removing `libopenblas0-pthread` as @eddelbuettel has suggested above?

```
sudo remove --purge libopenblas0-pthread
```

and re-running `update-alternatives` works for me.  


(Still interested in opinions on whether we should stick with the ubuntu:20.04 default of openblas0-pthread, switch to openblas-openmp, or something else?)

**Comment by kforner** [comment]
not sure @cboettig : 
```
$ R -q -e 'sessionInfo()' | grep BLAS
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

sudo apt remove --purge libopenblas0-pthread

$ R -q -e 'sessionInfo()' | grep BLAS
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblasp-r0.3.8.so

$ sudo update-alternatives --set libblas.so.3-x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/blas/libblas.so.3

$ R -q -e 'sessionInfo()' | grep BLAS
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblasp-r0.3.8.so
```

so removing libopenblas0-pthread make R switch to libopenblas-openmp-dev, but does not seem to allow to switch to libblas.
And that's understandable since `libR.so` is linked to  `libopenblas.so.0` instead of `libblas.so.3`

My use case is to use the default R implementation, and also to reduce the footprint of the R installation: openblas seems to increase it by at least 250MB.

**Comment by benz0li** [comment]
> openblas seems to increase it by at least 250MB.

Seems to be more like 70 MB:

```bash
$ docker run --rm -ti ubuntu
root@66663d221714:/# apt update && apt install libopenblas-dev
[...]
The following additional packages will be installed:
  libgfortran5 libopenblas-pthread-dev libopenblas0 libopenblas0-pthread
The following NEW packages will be installed:
  libgfortran5 libopenblas-dev libopenblas-pthread-dev libopenblas0 libopenblas0-pthread
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 8308 kB of archives.
After this operation, 68.4 MB of additional disk space will be used.
```

**Comment by kforner** [comment]
```
91.4902 libopenblas0-pthread
54.4727 libopenblas-pthread-dev
```
Actually more like 140MB. I wrongly counted libsuitesparse-dev and libgraphblas3

**Comment by eitsupi** [comment]
@kforner As you may know, you cannot reduce the size of a Docker image if the layer where `libopenblas` is installed is different from the layer where `libopenblas` is uninstalled.
In other words, removing `libopenblas` on `rocker/verse` will not reduce the size of the Docker image.
https://docs.docker.com/storage/storagedriver/#images-and-layers

**Comment by kforner** [comment]
@eitsupi Thank you @eitsupi I know that. I squash the modified image to actually reduce the size.

**Comment by kforner** [comment]
> Wasn't this true before (e.g. in the debian / R 3.x series of rocker/r-ver? and we could still switch to reference blas then, right?

If you use this script: https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_R.sh
It does:
```
./configure --enable-R-shlib \
		   --enable-memory-profiling \
		   --with-readline \
		   --with-blas \
		   --with-lapack \
		   --with-tcltk \
		   --with-recommended-packages
```
which does not include this flag: `--enable-BLAS-shlib` which I suppose create that `libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f8d54e6c000)` in `libR.so`

**Comment by eddelbuettel** [comment]
FWIW the Debian package uses `--with-blas` and `--with-lapack` and ends up with (via `sessionInfo()`) 

```
Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so
```

and on Ubuntu I get almost the same but 0.3.13 for the so version.  I do of course use a different 'build recipe' than this stack so maybe a build-dependency or two differ, but that should be easily testable for a sufficiently motivated person such as Karl :)

**Comment by kforner** [comment]
From https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#Shared-BLAS:
> R offers the option of compiling the BLAS into a dynamic library libRblas stored in R_HOME/lib and linking both R itself and all the add-on packages against that library.
This is the default on all platforms except AIX unless an external BLAS is specified and found: for the latter it can be used by specifying the option --enable-BLAS-shlib, and it can always be disabled via --disable-BLAS-shlib. 

- This is the default 
- UNLESS an external BLAS is specified and found

and:
> You can specify a particular BLAS library via a value for the configuration option --with-blas and not to use an external BLAS library by --without-blas (the default). If --with-blas is given with no =, its value is taken from the environment variable BLAS_LIBS, set for example in config.site. If neither the option nor the environment variable supply a value, a search is made for a suitable[68](https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#FOOT68) BLAS.
> The search includes OpenBLAS, ATLAS and a generic libblas, plus some platform-specific choices (see below).

So this seems to explain everything. I'll test that.

**Comment by cboettig** [comment]
:tada: Yes, thanks @kforner , I think that's what we're looking for.  I'm tempted to add that flag, but I did stumble across this old thread https://stat.ethz.ch/pipermail/r-devel/2008-July/050095.html, which seems to be suggesting that using `--with-lapack` and `--enable-R-shlib` is a bad idea? The  R-admin manual is indeed rather negative about `--with-lapack` https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Shared-BLAS (I note that Dirk's DRD config is as above, with `--with-lapack` and not `--enable-R-shlib`, https://github.com/rocker-org/drd/blob/5efc63aaf48306eedd700c52dd68aa1a63ea3941/Dockerfile#L87-L93



@eddelbuettel any other insights here?

**Comment by eddelbuettel** [comment]
All my build options are public in multiple place and _definitely_ include `--enable-R-shlib`.  The main `debian/rules` for r-base is a bit of convoluted 25-year old mess with these two values we talk about here being 'conditional' but if you want the full invocation from my logfile, on my amd64 it was

```
R_SHELL=/bin/bash				\
        mkdir_p="/bin/mkdir -p"                         \
MKDIR_P="/bin/mkdir -p"                         \
R_TEXI2DVICMD=emulation				\
R_PAPERSIZE=letter				\
R_BROWSER=xdg-open				\
R_BZIPCMD=/bin/bzip2				\
R_GZIPCMD="/bin/gzip -n"			\
PAGER=/usr/bin/pager				\
PERL=/usr/bin/perl				\
JAVA_HOME=/usr/lib/jvm/default-java             \
R_UNZIPCMD=/usr/bin/unzip			\
R_ZIPCMD=/usr/bin/zip				\
R_PRINTCMD=/usr/bin/lpr				\
TAR=/bin/tar					\
LIBnn=lib					\
AWK=/usr/bin/awk                                \
DD=/bin/dd					\
GREP=/bin/grep					\
FGREP="/bin/grep -F"				\
EGREP="/bin/grep -E"				\
SED=/bin/sed					\
GETWD="/bin/pwd"				\
CC=gcc					\
CXX=g++						\
F77=gfortran					\
FC=gfortran					\
CFLAGS="-g -O2 -ffile-prefix-map=/build/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g"				\
CXXFLAGS="-g -O2 -ffile-prefix-map=/build/r-base-4.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g"				\
FFLAGS="-g -O2 -ffile-prefix-map=/build/r-base-4.1.3=. -fstack-protector-strong"				\
FCFLAGS="-g -O2 -ffile-prefix-map=/build/r-base-4.1.3=. -fstack-protector-strong"				\
CPPFLAGS=					\
LDFLAGS="-Wl,-z,relro"				\
FLIBS=						\
rsharedir=/usr/share/R/share			\
rincludedir=/usr/share/R/include		\
rdocdir=/usr/share/R/doc			\
./configure --prefix=/usr			\
	    --with-cairo			\
	    --with-jpeglib			\
	    --with-readline			\
	    --with-tcltk			\
	    --with-system-bzlib			\
	    --with-system-pcre			\
	    --with-system-zlib			\
	    --mandir=/usr/share/man		\
	    --infodir=/usr/share/info		\
	    --datadir=/usr/share/R/share	\
	    --includedir=/usr/share/R/include	\
	    --with-blas		\
	    --with-lapack		\
	    --enable-long-double       \
	    --enable-R-profiling		\
	    --enable-R-shlib			\
	    --enable-memory-profiling		\
	    --without-recommended-packages	\
	    --build x86_64-linux-gnu
configure: WARNING: unrecognized options: --with-system-bzlib, --with-system-pcre, --with-system-zlib
```

as we can see that this is somewhat robust as it doesn't mind me still using a few by now deprecated options :rofl:  

(The above is the 'net' invocation based on various defaults and variables affecting the settings, _e.g._ how the Debian compiler config augments the normal choice etc.)

**Comment by cboettig** [comment]
Thanks @eddelbuettel ! (and sorry for typo above, now corrected, I meant `--with-BLAS-shlib` + with `--with-lapack` is a bad idea, not `--enable-R-shlib`, which is already used here as well.)  Thanks for weighing in on `--enable-BLAS-shlib` too!  Though now I'm still puzzled as to why we're not able to get R to switch to reference blas without this option?

Maybe a separate issue, but I don't really understand why [R admin manual](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Shared-BLAS) is so negative about `--with-lapack`:

> Please do bear in mind that using --with-lapack is ‘definitely not recommended’: it is provided only because it is necessary on some platforms and because some users want to experiment with claimed performance improvements. Reporting problems where it is used unnecessarily will simply irritate the R helpers. 

It seems debian (& rocker-versioned) have used that for a while now and it has worked rather well?

**Comment by kforner** [comment]
@cboettig  I think R installation discourages to use `--with-lapack` period. Meaning independently of using ` --with-BLAS-shlib`

**Comment by cboettig** [comment]
@eddelbuettel well said. I think that resolves my question about the `--with-lapack` "concerns" on R admin. (and apologies since I think that issue is totally independent of the original discussion of `--with-BLAS-shlib`.

I remain confused about what `--with-BLAS-shlib` does and whether it is needed for switching libs.  as noted in examples above, we can switch between openblas flavors it seems, but not between openblas and reference blas without this flag.  (Though I thought we could switch between openblas and reference blas just fine on earlier rocker images or a default install of debian r-base, neither of which compile using `--with-BLAS-shlib`, though I haven't tried that recently.)

**Comment by eitsupi** [comment]
I'm sorry I don't understand the discussion, but perhaps it would be better to reopen this issue or start another new one as we may need to modify the settings?

**Comment by kforner** [comment]
@eitsupi cf https://github.com/rocker-org/rocker-versioned2/issues/390
