### ISSUE TITLE
how to implement "make install-tests"

### ISSUE THREAD

**Issue by bergsmat** [rocker-org/rocker-versioned2#343]
Hi.  Thanks for this valuable tool!  I'm working with rocker/verse:4.1.2 (Ubuntu).  I wish to execute [full post-installation testing](https://cran.r-project.org/doc/manuals/R-admin.html#Testing-a-Unix_002dalike-Installation), which is only possible if ```make install-tests``` was run during installation.  I think it was not.  Easy to add?  Or, is there a way I can manually back may way into an equivalent solution?  Thanks for your thoughts.

**Comment by bergsmat** [comment]
Happy to expand.  I work in a regulated environment (drug development). We start with rocker/verse, then add additional features to create a custom image.  It is of regulatory interest to collect data showing that a container based on this image still has an R instance that operates as expected (really interested in R itself, not the packages for which alternative solutions exist).  In my mind, this is ‘installation qualification’, and the most obvious candidate is the tests supplied by R itself.  However, those tests are inoperable for an image based on rocker/verse, because ```make install-tests``` (optional) was never run (so ```/tests``` does not exist).  Retrofitting the image with a tests directory seems complicated and/or brittle. What would need to happen for the resulting image to have an R installation with the requisite test directory?  Thanks for your interest and thoughts.

**Comment by eitsupi** [comment]
I may not understand your question exactly, but I think you need to rewrite the following part of the script that is installing R and do it from the R installation.
In other words, you can't use images on DockerHub such as `rocker/verse`. I think you need to do it from R installation to `ubuntu:focal`.

https://github.com/rocker-org/rocker-versioned2/blob/cfac661b2871f59b31b8d56b3c6217cd6d521c5b/scripts/install_R_source.sh#L114-L132

**Comment by bergsmat** [comment]
This is helpful, thanks!

**Comment by eitsupi** [comment]
Please refer to the Dockerfiles for script usage, just in case.

https://github.com/rocker-org/rocker-versioned2/blob/cfac661b2871f59b31b8d56b3c6217cd6d521c5b/dockerfiles/r-ver_4.1.3.Dockerfile

**Comment by bergsmat** [comment]
Yes. Works well, thanks.
