### ISSUE TITLE
TeX Live packages on first use and after a year

### ISSUE THREAD

**Issue by cryanking** [rocker-org/rocker-versioned2#349]
When using the verse image and the rmarkdown::render command, even with no latex packages imported by name, it has to install a bunch of packages like amsmath and xcolor. This is quite slow. It also creates a problem when the Tex Live distribution locks after a year; running the old verse image will not be able to download the packages. For example, this is based off rocker/verse:4.0.4 run today.

```
/usr/local/bin/pandoc +RTS -K512m -RTS Data_Analysis_report.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Data_Analysis_report.tex --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --highlight-style tango --pdf-engine pdflatex --variable graphics --variable 'geometry:margin=1in' 
A new version of TeX Live has been released. If you need to install or update any LaTeX packages, you have to upgrade TeX Live.

tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
! LaTeX Error: File `amsmath.sty' not found.
```
For archival purposes, previously I have extended the verse image to have the dockerfile compile an empty report with the same packages that I plan to use, because it was very difficult to get all the dependencies otherwise. I prefer not to load the entire analysis code into the docker image.
```
RUN R -e 'rmarkdown::render("/code/empty_report.Rmd")'
````
but this has also worked with a little trial and error

```
RUN tlmgr option repository ftp://tug.org/historic/systems/texlive/2020/tlnet-final
RUN R -e "tinytex::tlmgr_update()"
RUN R -e "tinytex::tlmgr_install(c('amsmath' , 'latex-amsmath-dev' , 'iftex' , 'kvoptions' , 'ltxcmds' , 'kvsetkeys' , 'etoolbox' , 'xcolor' , 'auxhook' , 'bigintcalc' , 'etexcmds' , 'bitset' , 'gettitlestring' , 'hycolor' , 'hyperref' , 'intcalc' , 'kvdefinekeys' , 'letltxmacro' , 'pdfescape' , 'refcount' , 'rerunfilecheck' , 'stringenc' , 'uniquecounter' , 'zapfding' , 'infwarerr' , 'geometry' , 'booktabs' , 'mdwtools' , 'epstopdf-pkg', 'pdftexcmds' ,  'longtable' , 'array' , 'multirow' , 'wrapfig' , 'float' , 'colortbl' , 'pdflscape' , 'tabu' , 'threeparttable' , 'threeparttablex' , 'ulem' , 'makecell') )"
```

Is there another recommended way to take care of this? Obviously caching the entire TeX Live distribution isn't feasible. Should the `tlmgr option repository` be set in the base image?

**Comment by cboettig** [comment]
thanks for raising this.   The locked-version images ought to be using a version-locked texlive library as well, .e.g, https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/verse_4.0.4.Dockerfile#L8, 

Please check your `CTAN_REPO` env var to confirm.  If  I do a fresh pull of `rocker/verse:4.0.4`, go File->new Rmd->elsevier template, for example (which has heavy latex install deps), these seem to install ok for me on knit.  (though as you say it took like 5 minutes to complete that initial install!)


I do agree about the initial install being slow.  We're always a bit squeezed between folks wanting slimmer images and faster images.  If size isn't an issue, I think Dirk & I would both highly recommend just rolling with `apt-get install texlive` and friends; it's a much more friendly user experience than the tlmgr/tinytex approach for anyone who doesn't enjoy micromanaging their tex environment.

**Comment by eitsupi** [comment]
No updates, so I'm closing. Feel free to open it again if the problem continues.
