### ISSUE TITLE
Closing old repositories

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#350]
Related to #191.

I am wondering if the following repositories could be made public archives.
I believe these repositories used to share documentation with DockerHub, but now that the synchronization settings have stopped, there no longer seems to be a need to maintain these repositories.

- [x] https://github.com/rocker-org/rocker-versioned
- [x] https://github.com/rocker-org/shiny
- [x] https://github.com/rocker-org/geospatial
- [x] https://github.com/rocker-org/ml
- [x] https://github.com/rocker-org/rstudio-daily
- [x] https://github.com/rocker-org/ropensci

Since DockerHub links to these repositories, we sometimes see users wandering into these repositories to create issues (even today!).
Ideally, all DockerHub links should be directed to this repository, and the old repositories should be made public archives so that no new issues can be created.

**Comment by eddelbuettel** [comment]
Good idea!!  We could even 'move them away' to a new org for archival, say `rocker-org-archives` or something.

**Comment by cboettig** [comment]
Great idea.  I'll mark those as `archived` in GitHub which should make them all read-only.

**Comment by eitsupi** [comment]
Since you added me as a member, I would like to do this work.

1. There is still a blank space in [VERSIONS.md](https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md), can I merge https://github.com/rocker-org/rocker-versioned/pull/267 to complete it?
2. Can I pick a few misplaced issues from old repositories and move them to this repository? (Or would it be better to transfer all open issues?)

**Comment by cboettig** [comment]
Thanks @eitsupi , doing both of these as you propose would be great.  I think we will need to un-archive the old repo to make these changes, then we can re-archive it once these things are resolved.

**Comment by eitsupi** [comment]
> I think we will need to un-archive the old repo to make these changes, then we can re-archive it once these things are resolved.

Yes. The work should not take more than a few tens of minutes, so may I temporarily unarchive https://github.com/rocker-org/rocker-versioned and perform the above work?

I would also like to archive `shiny` and `ml` after the issues are moved (There were no open issues in `geospatial`).

**Comment by eitsupi** [comment]
I archived https://github.com/rocker-org/shiny and https://github.com/rocker-org/geospatial.
I think I sent out a large number of notifications as a result of moving a large number of issues. Sorry about that.

**Comment by eitsupi** [comment]
I tried to unarchive https://github.com/rocker-org/rocker-versioned and transfer the issues, but it failed.
This may be due to the fact that it has only been a short time since it was unarchived, so I will try again tomorrow.

**Comment by eitsupi** [comment]
I was able to transfer the issues, so I archived https://github.com/rocker-org/rocker-versioned again.

@cboettig
I couldn't decide if issues in https://github.com/rocker-org/ml should be moved (or if it should be resolved in the future in this repository).
Could you please take a look?
