### ISSUE TITLE
Install older shiny server

### ISSUE THREAD

**Issue by gui-salome** [rocker-org/rocker-versioned2#351]
Hi all! Thanks for creating these images, they are very helpful!

Is it possible to specify the version of shiny in the image?
For example, say I want to use R 4.0.3, but install an older version of Shiny, like v1.2. I could pull `rocker/shiny:4.0.3`, but what would be the version of shiny installed in the image? Is there a way to change it to v1.2?

Thanks for helping!

**Comment by eitsupi** [comment]
> I could pull `rocker/shiny:4.0.3`, but what would be the version of shiny installed in the image?

You can check the contents of the image in the wiki of this repository.

https://github.com/rocker-org/rocker-versioned2/wiki/shiny_ac2125ac13bb

shiny-server version is `1.5.18.979`.

> Is there a way to change it to v1.2?

Please check README.

https://github.com/rocker-org/rocker-versioned2#rocker-scripts

**Comment by gui-salome** [comment]
Thanks for the quick reply! 

Would pulling `rocker/shiny:4.0.3` (which installs the latest version of shiny server), and then running the script `RUN /rocker_scripts/install_shiny_server.sh 1.2.0` correctly "uninstall" the latest version of shiny server, and then install v1.2.0? Or should I instead pull `rocker/r-ver:4.0.3` and build from there?

Thanks  for helping!

**Comment by eitsupi** [comment]
I tried, but it seems that Shiny Server 1.2.0 cannot be installed.

https://github.com/rstudio/shiny-server/releases/tag/v1.2.0
It was released seven years ago, and the URL to download the installer may not exist now.

**Comment by eitsupi** [comment]
I looked at the Dockerfile below and tried the URLs that would have once been valid, but they did not work.
https://github.com/rocker-org/shiny/blob/871837d034da7fdb3bf5c2dd7e261273108ad925/Dockerfile

If you really need Shiny Server 1.2.0, you may need to build it yourself.
(In general, the version of Shiny Server itself is not considered important, and the latest version is always used. So I don't know why you need it)

**Comment by gui-salome** [comment]
@eitsupi thanks for trying it out. I was hoping to use that older version because of this issue: https://community.rstudio.com/t/shiny-v1-3-known-regressions-and-serious-issues/28180
Now that I say it, I realize the issue might be with the `shiny` package instead of the server.
