### ISSUE TITLE
rocker/shiny:latest gives me old version of R 4.0.5

### ISSUE THREAD

**Issue by gexijin** [rocker-org/rocker-versioned2#354]
Thank you for creating and maintaining the shiny docker. We have been relying on it for the last 5 years to run a popular website http://bioinformatics.sdstate.edu/idep/     

But recently we kept getting a puzzling error that may be due to and dated R version. Because on our laptops with latest version of R we do not have that error. 
What I discovered that rocker/shiny:latest gives me R 4.0.5.  
I tried rocker/shiny:4.1.2 and our issue is solved. 
Thanks.

**Comment by eitsupi** [comment]
> I always thought that I will get everything to rebuild from the latest version if I run
> docker build . -t webapp

`--pull` or `--no-cache` option may be what you are looking for.
https://docs.docker.com/engine/reference/commandline/build/#options

As a side note, linter for Dockerfiles may warn you not to use the `latest` tag because it makes it unclear whether you are receiving updates or not, as in this example.

**Comment by eitsupi** [comment]
If we check DockerHub, the digests for `rocker/shiny:latest`, `rocker/shiny:4`, `rocker/shiny:4.1`, and `rocker/shiny:4.1.2` are the same.
This means that currently these tags point to the exact same image.

https://hub.docker.com/r/rocker/shiny/tags

![image](https://user-images.githubusercontent.com/50911393/154826509-12dd67d0-8c8b-418d-b568-a5b6e00832f3.png)

The list of tags and the contents of the images can also be found in the wiki of this repository.
https://github.com/rocker-org/rocker-versioned2/wiki

**Comment by gexijin** [comment]
The -pull option is what I need in my script. Thank you!
