### ISSUE TITLE
Singularity error when using rocker/rstudio for R-4.0.0

### ISSUE THREAD

**Issue by yuifu** [rocker-org/rocker-versioned2#373]
I tried to use rocker/rstudio via Singularity following the instructions on [the Rocker Project official website](https://www.rocker-project.org/use/singularity/), and came across TAG-specific error for `rserver` execution.

## `rocker/rstudio:3.6.3` worked

```
$ singularity pull --name rstudio-3.6.3.simg docker://rocker/rstudio:3.6.3

$ singularity exec rstudio-3.6.3.simg rserver --www-address=`hostname` --www-port=58888
```

## `rocker/rstudio:latest` returns "rserver: not found"
[latest TAG corresponds to R 4.0.0](https://hub.docker.com/layers/rocker/rstudio/latest/images/sha256-7fc30239b3ec49f9b4bdb7d2b0c477dbf9532222fa47a265686f5b9cc537bff7?context=explore) on 2020/05/09

```
$ singularity pull --name rstudio.simg docker://rocker/rstudio:latest

$ singularity exec rstudio.simg rserver --www-address=`hostname` --www-port=58888
/.singularity.d/actions/exec: 21: exec: rserver: not found

$ singularity exec --cleanenv rstudio.simg rserver --www-address=`hostname` --www-port=58888
/.singularity.d/actions/exec: 21: exec: rserver: not found
```

## Question
Is there any way to avoid the above error for R-4.0.0 image?

**Comment by eitsupi** [comment]
Duplicate of #105

I would like to close this issue as a duplicate of #105 for now. (This issue was originally submitted to the wrong repository)
