### ISSUE TITLE
Update versions of OSGEO libs on rocker/geospatial

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/rocker-versioned2#376]
Currently `rocker/geospatial` has the following OSGEO system libraries:

```bash
docker run --rm -it rocker/geospatial /bin/bash
```

Currently that results in this:

```
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.0"        "3.0.4"        "6.3.1"         "true"         "true" 
          PROJ 
       "6.3.1" 
```

PROJ in particular is out of date now and some packages (notably `cartopy`) depend on 8.0.0 or greater. I will try the OSGeo-dev container, that may solve the specific issue I'm hitting.

**Comment by Robinlovelace** [comment]
Update: it seems that even the dev-osgeo tagged version has quite an old version of PROJ: 

```
docker run --rm -it rocker/geospatial:dev-osgeo /bin/bash
root@dcb11c7ca86f:/# R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
       "3.8.1"        "3.2.0"        "7.2.0"        "false"         "true" 
          PROJ 
       "7.2.0"
```

Happy to look into why this is and potentially to try to solve it but wanted to get feedback on level of priority and if this would be welcome upstream. Others know more about the upstream dependencies than me, and how they interact with core r-spatial packages. Heads-up @edzer, @rhijmans, @rsbivand, @paleolimbot and any other developers working on R-OSGeo bridges your thoughts would be v. welcome. Wondering if we need to have docker images with old versions (e.g. a `2019-osgeo` tag) for testing backwards compatibility and if shifting to later versions could cause issues (core packages `sf` and `terra` work with recent versions of OSGeo libraries to the best of my knowledge).

**Comment by eitsupi** [comment]
Those version numbers are hard-coded in `rocker/geospatial:dev-osgeo`'s Dockerfile.

https://github.com/rocker-org/rocker-versioned2/blob/80a339b5f2d0215d370600b373c2315b94886d46/dockerfiles/geospatial-dev-osgeo_4.1.2.Dockerfile#L8-L10

**Comment by Robinlovelace** [comment]
Thanks for the pointer @eitsupi, seems that way of doing it allows flexibility that is not being used. I have created a PR to get a conversation going on this. Thinking: currently the name `dev-osgeo` is misleading: I would expect the dev version to be kept up-to-data. Maybe the current config you shared could be used as the basis of a `stable-osgeo` image or similar?

**Comment by cboettig** [comment]
Thanks @Robinlovelace , I think the next step would be to add the logic to automatically determine the latest release versions, while still allowing users to override that by setting the `*_VERSION` env vars explicitly (similar to versioning elsewhere in the stack for RStudio etc). (Apologies I never got around to figuring that step out!) Interested in taking a stab at that?

I'm not sure about generating a new tag for `stable-osgeo`, I think users who want a stable env rather than latest versions are better off using those packaged in the official ubuntu repos, i.e. vanilla `rocker/geospatial` tags (e.g. which should play more nicely with RSPM binaries etc too I think...)

**Comment by Robinlovelace** [comment]
> Thanks @Robinlovelace , I think the next step would be to add the logic to automatically determine the latest release versions, while still allowing users to override that by setting the `*_VERSION` env vars explicitly (similar to versioning elsewhere in the stack for RStudio etc). (Apologies I never got around to figuring that step out!) Interested in taking a stab at that?

Big thumbs up from me on that. It would be v. useful for the R-spatial community, and potentially others, to have a way to test on the latest versions of OSGeo libraries. After a quick [search](https://www.google.com/search?channel=fs&client=ubuntu&q=install+latest+release+github+dockerfile) and browse through solutions on [GitHub](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8), I think the following would get the latest version of PROJ for example (just tested and it works on my laptop):

```bash
curl https://api.github.com/repos/osgeo/proj/tags | grep "tarball_url" | grep -Eo 'https://[^\"]*' | sed -n '1p' | xargs wget -O - | tar -xz
```

**Comment by Robinlovelace** [comment]
To get just the version number, which seems to be all that's needed in this case, you can do the following:

```
curl --silent "https://api.github.com/repos/osgeo/proj/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
9.0.0
```

Source: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c

**Comment by Robinlovelace** [comment]
Works for GDAL:

```
curl --silent "https://api.github.com/repos/osgeo/gdal/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'
v3.4.1
```

**Comment by Robinlovelace** [comment]
But not geos it seems, any ideas on that?

**Comment by Robinlovelace** [comment]
This is the closest I could get, which gets all tags but in no particular order: 

```
git ls-remote --tags https://github.com/libgeos/geos
```

**Comment by Robinlovelace** [comment]
Looks like this issue may have been fixed upstream with https://github.com/rocker-org/rocker-versioned2/commit/b249a6fad779112ac147f3b163c249177bc16af2 but I still don't see the results here: https://hub.docker.com/r/rocker/geospatial/tags

**Comment by Robinlovelace** [comment]
OK I see these are scheduled, only an hour or so to wait to be able to test: https://github.com/rocker-org/rocker-versioned2/actions/workflows/devel.yml

**Comment by eitsupi** [comment]
@Robinlovelace `rocker/geospatial:dev-osgeo` is usually only built on the first day of each month.
But I manually initiated the build and it will be available in a few hours.

https://github.com/rocker-org/rocker-versioned2/blob/b249a6fad779112ac147f3b163c249177bc16af2/.github/workflows/extra.yml#L1-L6

**Comment by eitsupi** [comment]
Please check this one.
https://github.com/rocker-org/rocker-versioned2/wiki/geospatial-dev-osgeo_1bd2e8834d28

**Comment by Robinlovelace** [comment]
Seems to be working:

```
sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
      "3.10.2"        "3.4.1"        "9.0.0"        "false"         "true" 
          PROJ 
       "9.0.0" 
```

**Comment by Robinlovelace** [comment]
I'm happy for this to be closed now but given talk of auto tagging versions and to allow others to comment will leave open for now. Massive thanks @eitsupi and @cboettig.

**Comment by Robinlovelace** [comment]
Use case: test the code in Geocomputation with R on dev-osgeo images. https://github.com/geocompr/docker/issues/23

**Comment by rsbivand** [comment]
Side note - ideally, GDAL should be built with GEOS, because many drivers use GEOS and behave differently if GEOS is not  available.

**Comment by edzer** [comment]
> many drivers use GEOS

Haven't tried, but I suspect the `query` argument to `st_read`, when given a spatial predicate, also needs it.

**Comment by Robinlovelace** [comment]
> Haven't tried, but I suspect the `query` argument to `st_read`, when given a spatial predicate, also needs it.

Seems that the `query` argument works on the new `rocker/geospatial:dev-osgeo` image resulting from this issues. Are there any other tests that are worth running? I aim to test the geocompr code on this image at some point.

```
docker run --rm -it rocker/geospatial:dev-osgeo /bin/bash
root@46874166cbfe:/# R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(sf)
Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 9.0.0; sf_use_s2() is TRUE
> nc_sql = st_read(system.file("shape/nc.shp", package="sf"),
+                      query = "SELECT NAME, SID74, FIPS FROM \"nc\" WHERE BIR74 > 20000")
Reading query `SELECT NAME, SID74, FIPS FROM "nc" WHERE BIR74 > 20000' from data source `/usr/local/lib/R/site-library/sf/shape/nc.shp' using driver `ESRI Shapefile'
Simple feature collection with 2 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: -81.06555 ymin: 34.82742 xmax: -78.49929 ymax: 35.50912
Geodetic CRS:  NAD27
```

**Comment by Robinlovelace** [comment]
Just realised, that's not a spatial predicate...

**Comment by mdsumner** [comment]
can we layer in the gdal docker itself as an option? I'd like bleeding edge without building from source on AWS (but I'm pretty lost in all this docker stuff, having a deeper look again)

https://github.com/OSGeo/gdal/tree/master/docker

**Comment by mdsumner** [comment]
I think I get it, create the install-from-source script alongside these https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_geospatial_unstable.sh, and create a dockerfile FROM rocker/verse:devel - apologies for the noise

**Comment by cboettig** [comment]
yeah, sorry docs are poor here.

We have 2 devel tags, one of which attempts the PPA route, https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_geospatial_unstable.sh, the other which builds from source https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/dev_osgeo.sh.  Prebuilt images for these are available for each, see: https://github.com/rocker-org/rocker-versioned2/wiki#extra-images, (i.e. `rocker/geospatial:unstable` and `rocker/geospatial:dev-osgeo`, respectively).  Both are build on the latest R version, not on R devel.  Note that in both cases since we're using different versions of the libs than standard ubuntu:20.04, we need to build relevant R packages from source instead of binary.

 
Note that all images built in this stack contain the full [scripts dir](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts) inside `/rocker_scripts`.  In principle, this makes it easy to roll a custom stack, e.g. starting from something like `rocker/rstudio` you can (in a Dockerfile or intractively) just call `/rocker_scripts/install_...` to run a given install script.  In practice this can create weird conflicts -- I've actually had trouble with running either the PPA- script and the dev-osgeo script on an image that already has the standard ubuntu22.04 versions installed (e.g. rocker/geospatial); I end up getting a gdal that just segfaults. 


Last, GDAL 3.5.0 is now in the repo build recipe for `dev-osgeo` tag, but it looks like the image hasn't built since 2022-05-01.  @eitsupi can you remind us which GH-Action does the build for these extra images?  Thanks!

**Comment by cboettig** [comment]
(Ah, looks like it is https://github.com/rocker-org/rocker-versioned2/actions/workflows/extra.yml of course, cron job runs these monthly normally but I've triggered a build now to pull in 3.5.0)

**Comment by mdsumner** [comment]
ah awesome thanks! I've started testing my own changes, hopefully can contribute myself soon enough - as mentioned elsewhere, one thing is the use of cmake for proj and gdal will soon be required

**Comment by Robinlovelace** [comment]
Great to see activity here, keep us posted @mdsumner and thanks all!

**Comment by eitsupi** [comment]
> I've triggered a build now to pull in 3.5.0

@cboettig Maybe you missed updating the Dockerfile?

https://github.com/rocker-org/rocker-versioned2/blob/ba73e4ab96225c466f5fc1d7b9831da591c54c32/dockerfiles/geospatial-dev-osgeo_4.2.0.Dockerfile#L8-L10

I think these versions, like those for other scripts, are controlled by environment variables and should not be hard-coded into the script.

**Comment by cboettig** [comment]
@eitsupi :facepalm: ah right, and those are set by the stack.json files still, right? https://github.com/rocker-org/rocker-versioned2/blob/ba73e4ab96225c466f5fc1d7b9831da591c54c32/stacks/extra.json#L59-L62  

bumped the versions there now, https://github.com/rocker-org/rocker-versioned2/pull/457

**Comment by eitsupi** [comment]
#455 will add logics to automatically detect the latest version of proj, gdal, and geos from GitHub releases or Git tags.
