### ISSUE TITLE
setting userid and groupid ?

### ISSUE THREAD

**Issue by ahdee** [rocker-org/rocker-versioned2#379]
Hi for the older version 3 this command use to be able to set the user UID? 
```
docker run --rm -p 1001:8787 -e PASSWORD=book101 -e USER=ahdee \
-e USERID=611 -e GROUPID=625 rocker/rstudio:3.4.0
```
however on this latest version it only sets the group id correctly.  Is there something else I can do? 
thanks.

**Comment by eitsupi** [comment]
I think that cases with USERID less than 1000 are basically not expected.
What is your reason for wanting to use that UID?

https://github.com/rocker-org/rocker-versioned2/blob/b249a6fad779112ac147f3b163c249177bc16af2/scripts/init_userconf.sh#L39-L40

**Comment by ahdee** [comment]
@eitsupi thanks, I needed this in order to get the permission set correctly for mounted volume, but I  solve the issue, thank you.
