### ISSUE TITLE
Set CRAN url after installing R

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#385]
Currently, the Dockerfile to install R has the following structure.
The `CRAN` environment variable for setting the CRAN mirror is set before R is installed, so the cache for the layer in which R is installed is disabled when the CRAN mirror is changed.

```dockerfile
FROM ubuntu:focal

ENV R_VERSION=4.1.3
ENV TERM=xterm
ENV R_HOME=/usr/local/lib/R
ENV CRAN=https://packagemanager.rstudio.com/cran/__linux__/focal/latest
ENV TZ=Etc/UTC

COPY scripts/install_R.sh /rocker_scripts/install_R.sh

RUN /rocker_scripts/install_R.sh

ENV LANG=en_US.UTF-8

COPY scripts /rocker_scripts
```

In fact, however, the CRAN mirror settings are not used during the R installation; the CRAN mirror settings are only used when installing some R packages that are installed after the R installation.

Therefore, from the viewpoint of cache reuse, I suggest separating the part affected by the environment variable `CRAN` from `install_R.sh` to another script `setup_R.sh` and separating the layers as shown below.
This change allows the layer to be reused in cases where the base image is not changed and only the CRAN URL is changed (when setting the CRAN mirror date when a new version of R is released, or when changing the URL when binaries for `ubuntu:jammy` are made available in RSPM, as expected in R4.2.0).

```dockerfile
FROM ubuntu:focal

ENV R_VERSION=4.1.3
ENV TERM=xterm
ENV R_HOME=/usr/local/lib/R
ENV TZ=Etc/UTC

COPY scripts/install_R.sh /rocker_scripts/install_R.sh

RUN /rocker_scripts/install_R.sh

ENV LANG=en_US.UTF-8
ENV CRAN=https://packagemanager.rstudio.com/cran/__linux__/focal/latest

COPY scripts /rocker_scripts

RUN /rocker_scripts/setup_R.sh
```

To avoid confusion, it may be a good idea to change the name of the script that installs R from source to something like `install_R_source.sh`.

**Comment by cboettig** [comment]
yup, good call regarding cache layer order. I'm supportive of both changes.
