### ISSUE TITLE
Why isn't rocker/ml:devel updated to the latest 'devel' version of R.

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker-versioned2#387]
It seems that the `rocker/ml:devel` image, even though it exists isn't updated to the latest version of R.

Is there any specific reason for this? 

![Screen Shot 2022-03-14 at 11 04 13 AM](https://user-images.githubusercontent.com/2746443/158200404-e6b5f5b3-6a49-43c1-944b-f21a827676e2.png)

**Comment by eitsupi** [comment]
`rocker/ml:devel` is not subject to daily automated builds by GitHub Actions, and can only be pulled from DockerHub if they were built a long time ago.

Only the following images described in the README are built daily with R-devel.

> The `devel` tag is available for `rocker/r-ver`, `rocker/rstudio`, `rocker/tidyverse`, `rocker/verse`.

**Comment by nturaga** [comment]
Thank you for your quick response. 

I'm wondering why it's still running R 4.1.0 though. That seems a little out of date. 

Just looking at the stack mentioned in the [README](https://hub.docker.com/r/rocker/cuda) file there, 

```
-| rocker/cuda
  -| rocker/ml
    -| rocker/ml-verse
```

`rocker/cuda:devel` - doesn't exist.  (https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/cuda_devel.Dockerfile)

I'm trying to find a GPU-based image to use that runs R devel i.e 4.2.0, that's what I'm after.

**Comment by eitsupi** [comment]
`rocker/ml` has existed for some time, while `rocker/cuda` is a relatively recent addition. (#214)
Therefore, when current `rocker/ml:devel` was built, it was not built based on `rocker/cuda:devel`.

> I'm trying to find a GPU-based image to use that runs R devel i.e 4.2.0, that's what I'm after.

Unfortunately, it has never been built from this repository and pushed to DockerHub. (Dockerfile exists, but it is not a build target)

**Comment by cboettig** [comment]
@nturaga,

apologies for the confusing situation regarding the tags on the ML images.  as @eitsupi points out, there's not an active `rocker/ml:devel` tag at this time, though it is something we should consider!

meanwhile, we do try for a modular system, so it should be possible if a little slow, to trigger the R-devel install on any of the ML images, e.g. `docker exec` into a running image (or run with `bash` as the default command), and run

```
R_VERSION=devel /rocker_scripts/install_R.sh
```
