### ISSUE TITLE
Java issues in the rockerdev images

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker-versioned2#39]
On the base rockerdev/rstudio:4.0.0-ubuntu18.04, `rJava` fails to install. There are a couple of problems with this,

1. Missing `default-jdk`: This is the big one, java is missing, or is in the wrong path. So, when I try to find the `java` installation, it doesn't actually find anything. 

```
root@7539219727d7:~# java --version
bash: java: command not found
```

2. libpcre2-dev: When I install `default-jdk` , the headers for libpcre2-dev seem to be missing. And this causes packages like rJava to fail installation.  (notice that there is no `libpcre2-8.so`)

```
root@7539219727d7:/usr/lib/x86_64-linux-gnu# ls -l libpcre2*
lrwxrwxrwx 1 root root     20 Feb 24  2018 libpcre2-16.so.0 -> libpcre2-16.so.0.7.0
-rw-r--r-- 1 root root 485928 Feb 24  2018 libpcre2-16.so.0.7.0
lrwxrwxrwx 1 root root     20 Feb 24  2018 libpcre2-32.so.0 -> libpcre2-32.so.0.7.0
-rw-r--r-- 1 root root 465448 Feb 24  2018 libpcre2-32.so.0.7.0
lrwxrwxrwx 1 root root     19 Feb 24  2018 libpcre2-8.so.0 -> libpcre2-8.so.0.7.0
-rw-r--r-- 1 root root 530984 Feb 24  2018 libpcre2-8.so.0.7.0
lrwxrwxrwx 1 root root     23 Feb 24  2018 libpcre2-posix.so.2 -> libpcre2-posix.so.2.0.0
-rw-r--r-- 1 root root  10336 Feb 24  2018 libpcre2-posix.so.2.0.0
```

3. Another problem I noticed, and I might be missing something is, when I run `R CMD javareconf` it fails to find `javah`, so there will be a missing java headers section. 

I'm providing details below, when I try, `install.packages('rJava')`.

```
checking Java support in R... present:
interpreter : '/usr/bin/java'
archiver    : '/usr/bin/jar'
compiler    : '/usr/bin/javac'
header prep.: ''
cpp flags   : '-I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux'
java libs   : '-L/usr/lib/jvm/java-11-openjdk-amd64/lib/server -ljvm'
checking whether Java run-time works... ./configure: line 3767: /usr/bin/java: No such file or directory
```

**Comment by cboettig** [comment]
@nturaga historically we've added java only at `rocker/verse`, and that should still be true.  Can you try that?  

Also, note that the 4.0.0 is now live and the acting as the `latest` on mainsream `rocker`, i.e. `rocker/verse:4.0.0` == `rocker/verse:latest`, and is now based on ubuntu 20.04.  any reason you are using the ubuntu:18.04 tag?

please re-open if need be!
