### ISSUE TITLE
Cannot connect to the R session on R studio server

### ISSUE THREAD

**Issue by dgmdevelopment** [rocker-org/rocker-versioned2#396]
Using docker on windows host, running container with the latest tidyverse. Container running but but can't open R studio on localhost: 8787   I get error message below.   
![msedge_VSXobBac3A](https://user-images.githubusercontent.com/188736/160737764-ac8d42c6-3d39-4c69-9214-43d0a6b90653.png)
Thanks for the help!

**Comment by eitsupi** [comment]
There is too little information to identify the problem.

What command did you use to run the container?
What logs did you see on the command line?

**Comment by dgmdevelopment** [comment]
Sorry for not providing enough info.  I'm using Windows 11 host, Docker Desktop 4.6.1 (76265), WSL2 backend.  Docker version 20.10.13, build a224086


To run the container I'm using `docker compose up -d` with this docker-compose.yml file:

```version: "3.8"
services:
    rstudio:
    container_name: "rocker-tidyverse"
    image: "rocker/tidyverse:latest"
    restart: "unless-stopped"
    env_file:
      - ./config/rstudio.env
    volumes:
      - //mnt/e/rdata:/home/rstudio
    ports:
      - 8787:8787
```
Log:

```
rocker-tidyverse  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
rocker-tidyverse  | [s6-init] ensuring user provided files have correct perms...exited 0.
rocker-tidyverse  | [fix-attrs.d] applying ownership & permissions fixes...
rocker-tidyverse  | [fix-attrs.d] done.
rocker-tidyverse  | [cont-init.d] executing container initialization scripts...
rocker-tidyverse  | [cont-init.d] 01_set_env: executing... 
rocker-tidyverse  | skipping /var/run/s6/container_environment/HOME
rocker-tidyverse  | skipping /var/run/s6/container_environment/PASSWORD
rocker-tidyverse  | skipping /var/run/s6/container_environment/RSTUDIO_VERSION
rocker-tidyverse  | [cont-init.d] 01_set_env: exited 0.
rocker-tidyverse  | [cont-init.d] 02_userconf: executing... 
rocker-tidyverse  | [cont-init.d] 02_userconf: exited 0.
rocker-tidyverse  | [cont-init.d] done.
rocker-tidyverse  | [services.d] starting services
rocker-tidyverse  | [services.d] done.
```

If I run the simple docker command you posted it does work! I wish to use docker compose so it stores my password in the .env file.  Thank you!

**Comment by eitsupi** [comment]
> ```yml
> volumes:
>   - //mnt/e/rdata:/home/rstudio
> ```

This part is not good.
The home directory should not be bind-mounted in its entirety, since configuration files and other files exist and are added in some cases.
For example, specify a directory like `/home/rstudio/rdata` instead.

**Comment by eitsupi** [comment]
If it has not been resolved, feel free to reopen it.
