### ISSUE TITLE
Encoding problem shiny app on Shiny Server

### ISSUE THREAD

**Issue by rwaaijman** [rocker-org/rocker-versioned2#397]
Dear rockers,
I have some issues with showing specific characters in a dashboard.
An exactly the same dashboard was hosted with shiny-verse 4.0.5 and with shiny-verse 4.1.3.

In the 4.0.5 version this text is shown: beïnvloeden
In the 4.1.3 version this text is shown: be<c3><af>nvloeden
(all files are in UTF-8)

Any clue what it can be? Using docker-compose exec, I checked if the environment encoding and that seems okay (LANG=en_US.UTF-8).

**Comment by eitsupi** [comment]
I edited the Rmd file included in the sample project (`/srv/shiny-server/sample-apps/rmd/index.Rmd`) and it renders fine.

![image](https://user-images.githubusercontent.com/50911393/161271213-ab6ea70a-1b22-46c8-a30b-97bb6af03b3c.png)

Could you provide a reproducible example?

**Comment by rwaaijman** [comment]
Hi eitsupi, thanks for the reply.
It seems that it has to do something with reading UTF-8 files (difference between R4.0 and R 4.1). I have to find out what goes wrong. For now I will close the issue, because it might not be shiny-verse related.

**Comment by rwaaijman** [comment]
Below a minimal example of the error.
When running the shiny dashboard locally using R 4.1.3 on my linux it is working.
However, when running the app with rocker shiny-verse 4.1.3, encoding goes wrong. It seems something to do with source()

attached a zip-file with the scripts:

[app.zip](https://github.com/rocker-org/rocker-versioned2/files/8399385/app.zip)

**Comment by eitsupi** [comment]
The following results were obtained.
On the other hand, when I ran the shiny app on R on `rocker/r-ver:4.1.2`, which is what I usually use, the characters were not garbled, so this seems to be a ShinyServer issue.

## `docker.io/rocker/shiny-verse:4.1.3@sha256:f824865b5099498a0d1785dde1de552939be3eb2940961d920f4c71`

![image](https://user-images.githubusercontent.com/50911393/161372647-4988587f-2d14-4104-974a-f2caffc5e820.png)

## `docker.io/rocker/shiny-verse:4.0.5@sha256:4a1ae5e48d2cc641b12b58fe78e105e6c8e597d2fcfcd1b7ca60503`

![image](https://user-images.githubusercontent.com/50911393/161372796-65924508-3b43-46b3-9609-8444bc6dd85d.png)

**Comment by eitsupi** [comment]
It seems related to rstudio/shiny-server#304

**Comment by rwaaijman** [comment]
Hi eitsupi, thanks for your replies and indeed, new shiny-server version seems to be the problem. I'm going to ask this question to shiny server

**Comment by rwaaijman** [comment]
see issue shiny-server: https://github.com/rstudio/shiny-server/issues/520

**Comment by eitsupi** [comment]
@rwaaijman Do you know which version of Shiny Server does not cause this problem?

**Comment by rwaaijman** [comment]
I checked an older properly working rocker shiny-verse version 3.6.3. 
The shiny-server version in this image is: [2022-04-03T18:04:12.535] [INFO] shiny-server - Shiny Server v1.5.13.944 (Node.js v12.15.0)

**Comment by rwaaijman** [comment]
@eitsupi On an other computer I build 2 months ago a rocker shiny-verse:4.0.5 image. This image contains the newest shiny-server version (1.5.18.979 [node.js v12.22.6]). This one works properly... So it might not be a shiny-server problem? 

Somewhere between 2 months ago and now something has changed which causes this error?

**Comment by eitsupi** [comment]
@rwaaijman What is the digest of that image?
Or, if the commit hash is recorded in the `org.opencontainers.image.revision` annotation, you will be able to see what has changed in the source code to date.

```shell
docker image inspect rocker/shiny-verse:4.0.5
```

**Comment by eitsupi** [comment]
Comparison of the two images below identifies the change made by #313 as the one that caused the problem.

[rocker/shiny@sha256:f3d72ca7c05b38c71b4f610960062e935364c1ff127bc107711ff3decb5362f1](https://github.com/rocker-org/rocker-versioned2/wiki/shiny_bbd36e46fcaf) build from 979d7364f63fa8e7b7307c50bffbb32e8ced71cb
[rocker/shiny@sha256:270cdc63dcc7acb985fe5fe7aa00361d006339270abdda0a4ea45c821af311cd](https://github.com/rocker-org/rocker-versioned2/wiki/shiny_e855b61628d2) build from cca6e18851380133f36f4c64645c06166e0956e3

![image](https://user-images.githubusercontent.com/50911393/161948683-aaf3896e-1df9-4e78-ad58-ae9c26133550.png)

diff of these commits https://github.com/rocker-org/rocker-versioned2/compare/cca6e18851380133f36f4c64645c06166e0956e3...979d7364f63fa8e7b7307c50bffbb32e8ced71cb

**Comment by eitsupi** [comment]
https://github.com/rstudio/shiny-server/issues/304#issuecomment-313785524

The above comment suggests the following:

> If you create the file `/etc/default/locale` and populate it with `LANG="en_US.utf8"` I imagine that will fix it.

So I added the following line to the Dockerfile and the characters are now displayed correctly.

```Dockerfile
RUN echo "LC_ALL=en_US.UTF-8" >>/etc/default/locale
```

@dpprdan You commented on #313 as follows: do you know how to properly set up `/etc/default/locale`?
(I do not understand why you made this comment on #313)

> 3\. `/etc/default/locale` is not set, since it doesn't seem to be necessary.

**Comment by rwaaijman** [comment]
Thanks eitsupi,
Works like a charm!

Shall I close this issue, or shall I leave it open for @dpprdan?

**Comment by benz0li** [comment]
> So I added the following line to the Dockerfile and the characters are now displayed correctly.
> 
> ```dockerfile
> RUN echo "LC_ALL=en_US.UTF-8" >>/etc/default/locale
> ```

@eitsupi Shouldn't `echo "LANG=en_US.UTF-8" >> /etc/default/locale` be sufficient?

@rwaaijman Could you test and confirm that?

**Comment by benz0li** [comment]
> So I added the following line to the Dockerfile and the characters are now displayed correctly.
> 
> ```dockerfile
> RUN echo "LC_ALL=en_US.UTF-8" >>/etc/default/locale
> ```

@eitsupi Shouldn't `echo "LANG=en_US.UTF-8" >> /etc/default/locale` be sufficient?

@rwaaijman Could you test and confirm that?

**Comment by benz0li** [comment]
Regarding

> 2. localedef is used instead of locale-gen (as [recommended](https://github.com/docker-library/docs/tree/master/ubuntu#locales) for the official ubuntu image).

see [Ubuntu Manpage: locale-gen — generates localisation files from templates](https://manpages.ubuntu.com/manpages/focal/man8/locale-gen.8.html):

> **locale-gen** is a program that reads the file **/etc/locale.gen** and invokes **localedef** for the
> chosen  localisation profiles.  Run **locale-gen** after you have modified the **/etc/locale.gen**
> file.

There is nothing wrong with

```bash
sed -i "s/# $LANG/$LANG/g" /etc/locale.gen
locale-gen
update-locale --reset LANG=$LANG
```

for any `$LANG` (locale) listed in `/etc/locale.gen`.

**Comment by dpprdan** [comment]
> @dpprdan You commented on #313 as follows: do you know how to properly set up `/etc/default/locale`? (I do not understand why you made this comment on #313)
> 
> > 3. `/etc/default/locale` is not set, since it doesn't seem to be necessary.

My comment now seems a bit opaque to me as well, but I probably meant that [my tests](https://gitlab.com/dpprdan/rocker_locale/-/jobs/1907131605) indicated that the locale was set properly with an [empty `/etc/default/locale`](https://gitlab.com/dpprdan/rocker_locale/-/jobs/1907131605#L147). But apparently my tests were not sufficient, e.g. when using `su` [as mentioned here](https://github.com/rstudio/shiny-server/issues/304#issuecomment-313785524). 

> @eitsupi Shouldn't `echo "LANG=en_US.UTF-8" >> /etc/default/locale` be sufficient?

Yes, you're right @benz0li, setting `LC_ALL` is [strongly discouraged](https://wiki.debian.org/Locale#Configuration).

> Using LC_ALL is strongly discouraged as it overrides everything. Please use it only when testing and never set it in a startup file. [...] End users should never set `LC_ALL`, at least not permanently. `LC_ALL` is reserved for programs or situations where you need to enforce a specific locale (usually "C") on a temporary basis. One example of this would be reporting error messages on an English-speaking mailing list; you can use `LC_ALL=C your command` to ensure that the errors are in English, and follow all the POSIX norms. 

I'd probably just add `update-locale LANG=en_US.UTF-8` about [here](https://github.com/rocker-org/rocker-versioned2/blob/f3325b2cf88d8899ddcb2f0945aa9f87ad150cd7/scripts/install_R_source.sh#L21) now. `update-locale` "updates  the  `/etc/default/locale`  file  to  reflect   changes   in   system configuration  related  to global locale settings."

BTW, @benz0li, I've used the same passage from the the `locale-gen` man-page [to argue](https://github.com/rocker-org/rocker-versioned2/issues/302#issuecomment-997437630) that `localedef` is sufficient in this case (since we are only generating one locale). Either is fine probably, I just went with `localedef` because it is [recommended](https://github.com/docker-library/docs/tree/master/ubuntu#locales) in the ubuntu docker image docs.

**Comment by rwaaijman** [comment]
@benz0li , yes I can confirm that `echo "LANG=en_US.UTF-8" >> /etc/default/locale` also works

>

**Comment by eitsupi** [comment]
> Shouldn't `echo "LANG=en_US.UTF-8" >> /etc/default/locale` be sufficient?

Thank you for pointing this out. I was confused because I was just testing to set the environment variable `LC_ALL`.

**Comment by eitsupi** [comment]
https://github.com/rocker-org/rocker-versioned2/blob/da471be9a29a74da20bb71fc370769243b5be7c2/scripts/install_R_source.sh#L19-L20

Checking on ubuntu, this section looks fine rewritten as follows.

```shell
LANG=${LANG:-"en_US.UTF-8"}
/usr/sbin/locale-gen --lang "${LANG}"
/usr/sbin/update-locale LANG="${LANG}"
```

This process is already used in the following location.

https://github.com/rocker-org/rocker-versioned2/blob/89d36d2b313add1c45423bc4bac9f537ff29b8dc/scripts/init_userconf.sh#L88-L92

**Comment by rwaaijman** [comment]
thank you very much @eitsupi (and @benz0li )
