### ISSUE TITLE
Implement Makefile-based `latest` tagging

### ISSUE THREAD

**Issue by noamross** [rocker-org/rocker-versioned2#42]
Current approach to `latest` tagging doesn't create bitwise identical images.  Create `latest` images with `docker tag` in the Makefile instead.  Things to consider

- Easiest if we enforce `latest` on whole stacks
- Can/should we still use a field in the stackfiles to designate images as `latest`? Or do we just list `latest` stacks in the Makefile?

**Comment by cboettig** [comment]
@noamross this is done now, yeah?

**Comment by noamross** [comment]
Yes, completed in #47
