### ISSUE TITLE
`rocker/r-ver:4.0.0-ubuntu18.04` can't be built now

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#432]
The changes discussed in #390 do not seem to work on `ubuntu:bionic`.

https://github.com/rocker-org/rocker-versioned2/runs/6126166221?check_suite_focus=true

```log
#12 6.908 update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3 to provide /usr/lib/x86_64-linux-gnu/libblas.so.3 (libblas.so.3-x86_64-linux-gnu) in auto mode
#12 6.911 update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas/liblapack.so.3 to provide /usr/lib/x86_64-linux-gnu/liblapack.so.3 (liblapack.so.3-x86_64-linux-gnu) in auto mode
#12 6.914 Setting up libopenblas-dev:amd64 (0.2.20+ds-4) ...
#12 6.919 update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas/libblas.so to provide /usr/lib/x86_64-linux-gnu/libblas.so (libblas.so-x86_64-linux-gnu) in auto mode
#12 6.921 update-alternatives: using /usr/lib/x86_64-linux-gnu/openblas/liblapack.so to provide /usr/lib/x86_64-linux-gnu/liblapack.so (liblapack.so-x86_64-linux-gnu) in auto mode
#12 6.925 Processing triggers for libc-bin (2.27-3ubuntu1.5) ...
#12 6.955 update-alternatives: error: alternative /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 for libblas.so.3-x86_64-linux-gnu not registered; not setting
#12 ERROR: process "/bin/sh -c /rocker_scripts/setup_R.sh" did not complete successfully: exit code: 2
```

@cboettig @noamross Do you think it is acceptable to end support for running scripts on Ubuntu 18.04 without fixing this issue?
My understanding is that only the R 4.0.0 images have the `ubuntu18.04` flavor because it was just after the Ubuntu 20.04 release at the time and RSPM binaries were not provided for Ubuntu 20.04, etc., so it has outlived its role.

**Comment by cboettig** [comment]
yes, I favor discontinuing Ubuntu 18.04 support.  (though I Think the above is fixable)

Correct, it was only introduced a something of a stop-gap measure for things that didn't have Ubuntu 20.04 compatibility at the time (for RSPM and a few other edge cases in geospatial iirc) and otherwise didn't really fit into the standard release model, and as you know it was never extended to the whole stack either.
