### ISSUE TITLE
Dedicated script for ODBC Oracle connexion ?

### ISSUE THREAD

**Issue by MendelYev** [rocker-org/rocker-versioned2#450]
Hi,
I've been enjoying a lot this repo lastly! Thanks for your huge work!
I usually struggle a bit when it comes to connect rstudio with Oracle database and I wondered if this part could become a dedicated install_script ?

From what I understand, there are actually 3 principle ways to connect R with Oracle but as [RStudio website says](https://db.rstudio.com/databases/oracle/), only ODBC connexion provides DBI interface and avoid bringing Java. So:
- ROracle : seems to be the official way to connect but no update since R 3.5 and dbplyr not fully compatible according to [this page](https://db.rstudio.com/databases/oracle/)
- RJDBC : provides DBI but uses rJava
- odbc : best world (DBI without Java) but a bit difficult to deploy, especially in Ubuntu (Oracle provide only .rpm or .zip)

If you are ok with the idea, I can provide pull request with an install_script including:
- install unixodbc
- install Oracle instantclient Basic
- install Oracle instantclient ODBC
- and some doc on how to parameter ODBC accordingly

**Comment by cboettig** [comment]
unixodbc-dev is already installed in the `tidyverse` images, https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_tidyverse.sh#L29.  

In general I think it would be better for the Oracle client installation to be packaged into a client R package.  Most of the dependencies installed in this stack are installed directly from the official ubuntu repositories or from CRAN-hosted R packages, for which version stable snapshots are available.  This ensures that our recipes continue to build reproducibility well into the future.  Most of these sources also benefit from the scrutiny of  professional security teams.  So I think we should keep the number of installations from alternative sources very limited. Given that the ROracle maintainers haven't bothered to package their software for R 4.x, first released 2 years ago, this doesn't inspire confidence.  I recognize some users still need such functionality, but I think it will have to be handled elsewhere and does not fall to our volunteer team.
