### ISSUE TITLE
would you be okay with a pr to add a few more labels?

### ISSUE THREAD

**Issue by lizelive** [rocker-org/rocker-versioned2#451]
for `docker.io/rocker/ml-verse:4.2.0`

```dockerfile
LABEL \
     azure.ii.language='en-US' \
     azure.ii.support.stage='preview' \
     azure.ii.user='{"mode":"entry_point","name":"USER","uid":"USERID","gid":"GROUPID","root":"ROOT"}' \
     azure.ii.locale='{"tz":"TZ","lang":"LANG"}' \
     azure.ii.endpoints='[{"label":"rstudio","target":8787,"protocol":"http"}]' \
     azure.ii.args='[{"label":"disable-auth","description":"disable authentication for RStudio","type":"boolean","default":"true","environment":"DISABLE_AUTH"}]' \
     org.opencontainers.image.description='a community managed RStudio® server with ml with cuda, python, tidyverse, and devtools' \
     org.opencontainers.image.title='Rocker RStudio® Server ML Verse' \
     org.opencontainers.image.version='4.2.0' \
     org.opencontainers.image.url='https://www.rocker-project.org/'
```

the `org.opencontainers.*` labels are per [oci image annotations spec](https://github.com/opencontainers/image-spec/blob/main/annotations.md)

the `azure.ii.*` labels is standard from Microsoft to auto configure the container for the user.
RStudio has agreed to adopt these labels in the next few days for their [rstudio-workbench image](https://hub.docker.com/r/rstudio/rstudio-workbench).

**Comment by eitsupi** [comment]
Thanks for the suggestion.

But `org.opencontainers.image.description`, `org.opencontainers.image.title`, and `org.opencontainers.image.version` are already defined by docker-bake.json files.

https://github.com/rocker-org/rocker-versioned2/blob/4f634d5b9c0d58131e7b2630cab47e30e00dd095/bakefiles/4.2.0.docker-bake.json#L296-L311

Can you please tell me where the specifications of the `azure.ii.*` annotations?
Also, are there any well-known images that use these annotations?
I searched but could not find them.

**Comment by eitsupi** [comment]
Closing this for now due to lack of information.
