### ISSUE TITLE
GEOS is already cmake- only and GDAL 3.5.0 optionally, from 3.6.0 cmake only

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#458]
Please note that GEOS is already cmake- only, as PROJ. GDAL 3.5.0 optionally, from 3.6.0 cmake only. If revising anyway, maybe make the cmake changes at the same time ?

_Originally posted by @rsbivand in https://github.com/rocker-org/rocker-versioned2/pull/455#discussion_r879578199_

**Comment by eitsupi** [comment]
GDAL 3.6.0 is released.

It is assumed that `rocker/geospatial:dev-osgeo` cannot be built unless the following sections are updated
https://github.com/rocker-org/rocker-versioned2/blob/4f84ba435b4412517ef632c94da537d65346b732/scripts/experimental/install_dev_osgeo.sh#L106-L120

See https://gdal.org/build_hints.html.

cc @cboettig

**Comment by rsbivand** [comment]
Thanks for tracking this. Now all the latest released PROJ, GEOS and GDAL versions are cmake-only. In addition, new drivers needing new external dependencies for GDAL have been introduced, notably blosc compression for the ZARR driver @edzer and others.

**Comment by edzer** [comment]
All pretty straightforward, but [here](https://github.com/r-spatial/sf/blob/main/inst/docker/gdal/Dockerfile#L109-L117) is a Dockefile section that does the `cmake` install.
