### ISSUE TITLE
Rstudio dail build fails

### ISSUE THREAD

**Issue by danwwilson** [rocker-org/rocker-versioned2#46]
I attempted to build an image for RStudio Daily and it throws an error saying that rstudio requires `libpq5`

Example build logs at https://hub.docker.com/repository/registry-1.docker.io/thedatacollective/rstudio_preview/builds/b44e8aee-3c34-42f0-b69c-603507374f75

**Comment by cboettig** [comment]
@danwwilson apologies for the slow reply, this one slipped past me.  I think you have figured it out already in the meantime?  All you should need is to apt-get libpq5.   

As an aside, but any reason why you're using the `18.04` tag?   We are strongly considering aiming to move all 4.0.0 tags to ubuntu:20.04 for simplicity and longevity....

**Comment by eitsupi** [comment]
Seems be closed by 3804e58e7323b35afd5a5d5097d8ebfa6e5ef4c2
