### ISSUE TITLE
How rocker containers connect to the internet

### ISSUE THREAD

**Issue by sino1641** [rocker-org/rocker-versioned2#462]
I am beginner to docker and rocker here. And I want to find out how rocker containers connect to the internet.
For example, I would like to install packages inside a running R-studio server container but it returns there is no internet connection.
I have learned that docker bridge mode can only forward specific ports, like 8787 for R-studio server, but no general http/https ports.
So is there any solutions or workarounds for my situation? Or I can only bind exists R-library from host to container?
Much thanks.

**Comment by eddelbuettel** [comment]
They connect.  We often update containers while running to test or demonstrate, this is also how CI based on containers works.  Check you local setup, you may have it off by default "for safety".  Here under Linux:

Taking a light / small package here and just using the command-line:

```sh
edd@rob:~$ docker run --rm -ti r-base Rscript -e 'install.packages("fortunes")'
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/fortunes_1.5-4.tar.gz'
Content type 'application/x-gzip' length 192938 bytes (188 KB)
==================================================
downloaded 188 KB

* installing *source* package ‘fortunes’ ...
** package ‘fortunes’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (fortunes)

The downloaded source packages are in
        ‘/tmp/RtmpRzA6Pg/downloaded_packages’
edd@rob:~$ 
```

(The example is meaningless as I start a container, 'expand it' with the `fortunes` package ... and then let it exit.  But it demonstrates that _by default_ connectivity is on if the hosts provides it.)

**Comment by sino1641** [comment]
@eddelbuettel Thanks for your reply and testing.
I may figure out how docker network works.
And please forgive any disturbs for my silly question.

**Comment by eddelbuettel** [comment]
It's not a silly question -- it should work, but I can't tell from what you wrote why it doesn't or wouldn't.  You may have to consult a standard docker tutorial for your OS.  Also note that strictly speaking I did _not_ give you an existence proof for our RStudio container as I used `r-base`.  But none of our container will shut off networking.
