### ISSUE TITLE
matplotlib plots crash due to conflicting BLAS versions in numpy

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-versioned2#471]
The pre-compiled binaries for numpy are built against a different BLAS library than the openblas library included on rocker images.  This leads to unexpected errors unless numpy is installed from source, e.g. 

```
pip3 install --no-binary="numpy" numpy --ignore-installed
```

I don't yet know the best work around here, it's difficult as the error is both relatively opaque for users to track down, and there are just oh so many ways users will install and re-install numpy from binary without realizing it in different virtualenvs.  

A start but no means a complete solution would be to at least build numpy from source in the python images.  Open to any better solutions / ideas?  (cc @yuvipanda ?)

**Comment by cboettig** [comment]
Looks like this may impact scikit-learn as well, which binds lapack / blas independently. Simplest solution for now may be to opt out of openblas, e.g. 

```
export ARCH=$(uname -m)
update-alternatives --set "libblas.so.3-${ARCH}-linux-gnu" "/usr/lib/${ARCH}-linux-gnu/blas/libblas.so.3"
update-alternatives --set "liblapack.so.3-${ARCH}-linux-gnu" "/usr/lib/${ARCH}-linux-gnu/lapack/liblapack.so.3"
```

**Comment by eddelbuettel** [comment]
I think you could also just rely on `apt` to only have reference blas (or atlas) rather than openblas installed (if the multithreading is the issue here).

**Comment by cboettig** [comment]
Thanks @eddelbuettel! We've had openblas enabled by default on the `r-ver` stack for a long time to give multithreaded behavior out-of-the-box, though we've had some issues occasionally as you know. 

From what I understand, the segfault here is not due to multithreading per se, but something to do with how openblas uses LP64 suffixes on it's symbols, and whether the numpy wheels from pypi are being built using `CFLAGS=-fvisibility=hidden` -- but whatever that all means is pretty much over my head. (See https://github.com/numpy/numpy/issues/21643 for details and recent changes to numpy build recipes which may address this). 

I don't really understand why the same python binary behaves differently with respect to BLAS libraries when it is called via `reticulate` vs being invoked in pure python, but it seems that is what happens.  This issue is discussed over in https://github.com/rstudio/reticulate/issues/1190.  [t-kalinowski](https://github.com/t-kalinowski) mentions that this issue is caused when R is built "specifically against openblas" rather than "a generic BLAS interface"; I thought we were doing the latter, given that `update-alternatives` works, but maybe we aren't?

**Comment by cboettig** [comment]
@eitsupi do you think it would make sense to put openblas back on by default then in the ubuntu 22.04 images?

**Comment by eitsupi** [comment]
@cboettig Yes, but I am wondering if the bug could recur as long as I don't know why it is not occurring.

**Comment by eitsupi** [comment]
Thank you for the explanation.
It seems like a good idea to update the documentation and scripts to clearly state that workarounds are required for focal-based images.
