### ISSUE TITLE
The wiki home took too long to reder

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#472]
I think it is due to the long list of tags contained in the table, and it seems that the additional tags for GHCR are taking more longer to render as a result.

![image](https://user-images.githubusercontent.com/50911393/171372281-b82ece28-d8ae-4ca0-94ac-7c7bba8ae539.png)

**Comment by eitsupi** [comment]
Strangely enough, it never seems to be unable to render on my fork. I don't know what is causing this......

**Comment by cboettig** [comment]
rendering for me now. might just be cache not refreshed?

**Comment by dpprdan** [comment]
It doesn't render for me now. @eitsupi's fork and https://github.com/jupyter/docker-stacks/wiki render fine.

**Comment by eitsupi** [comment]
Thanks for the feedback.
Time did not solve this for me, so I will try to fix it.

**Comment by eitsupi** [comment]
I am trying to change from a table format to a list format.
