### ISSUE TITLE
chown when specifying username in rstudio container

### ISSUE THREAD

**Issue by ProbablePattern** [rocker-org/rocker-versioned2#489]
Customizing the username produces a long-running (more than 15 minutes, have not waited until the end) chown process before the rstudio server is started. This appears to be related to the volumes added to the container. Keeping the default user "rstudio" does not cause a problem. The workaround is obviously to just keep the default user which is fine for local insecure containers. Enabling authentication, adding a password, and changing the username would be ideal for cloud deployment but this will not be feasible if using large volumes.

Docker on WSL2 on Windows 10
Host username is huser
Container username is duser

Setup up cifs volume then run container with both local volume and network volume

```
docker volume create \
  --driver local \
  --opt type=cifs \
  --opt device=//xxx.xxx.xxx.xxx/Array \
  --opt o=username=huser,password=pswd,uid=1000 \
  --name Array

docker run -d \
    --name Rocker \
    --hostname Rocker \
    --network bridge \
    -e USER=duser \
    -e DISABLE_AUTH=true \
    -p 127.0.0.1:8787:8787 \
    -v /mnt/c/Users/huser/local:/home/duser/local \
    -v Array:/home/duser/array \
    rocker/rstudio:latest
```

I am relatively new to docker so I apologize if this is a docker problem rather than an image problem.

**Comment by eitsupi** [comment]
I would like to do away with the username change mechanism.
A warning message is now displayed when a user name is changed (#490).

If you change the user name, it is recommended that you build a Dockerfile like the following instead of doing it in the init process of `rocker/rstudio`.

```dockerfile
FROM rocker/rstudio:4.2.0
ENV DEFAULT_USER=new_user
RUN usermod -l "$DEFAULT_USER" rstudio \
    && groupmod -n "$DEFAULT_USER" rstudio \
    && usermod -d /home/"$DEFAULT_USER" -m "$DEFAULT_USER"
```

**Comment by eddelbuettel** [comment]
I think we used that feature in the derived container we use with RStudio along with the [PrarieLearn](https://www.prairielearn.org/) test / grade mechanism (where the backend user gets created in an underlying container, and this comes second).  I presume we could live with a warning (which presumably nobody sees in backend mode...)

**Comment by cboettig** [comment]
agree with deprecating this.  Changing UID makes sense (for volume mapping / permissions) but I don't think there's much purpose in renaming the user. Of course users can create additional users with whatever names they desire, which is often handy in education/training contexts.
