### ISSUE TITLE
Unable to set readOnlyRootFilesystem to true in kubernetes cluster

### ISSUE THREAD

**Issue by kaiyuanlim** [rocker-org/rocker-versioned2#491]
### Container image name

rocker/rstudio:4.0.2

### Container image digest

sha256:4ea0b4c4eb3886cb1f9cd19f6575ab6e15812974cc5996f8460fad69b6abe08b

### What operating system are you seeing the problem on?

Linux

### System information

* Running on Ubuntu 20.04 via docker version 20.10.11

### Bug description

* I cannot run Rstudio from rocker in my k8s cluster with readOnlyRootFilesystem set to true.
* I see the following errors when starting the container in the pod:

```
sed: couldn't open temporary file /usr/local/lib/R/etc/sedoR4Ain: Read-only file system
mv: cannot move '/etc/rstudio/disable_auth_rserver.conf' to '/etc/rstudio/rserver.conf': Read-only file system
/var/run/s6/etc/cont-init.d/02_userconf: line 16: /etc/environment: Read-only file system

```

### How to reproduce this bug?

```sh
* Running the image in a k8s cluster with security context set to true.
* I also tried the following in my environment variable


        - name: TMPDIR
          value: /tmp
        - name: DISABLE_AUTH
          value: 'true'
        - name: S6_READ_ONLY_ROOT
          value: '1'
        - name: S6_KEEP_ENV
          value: '1'
```

**Comment by eitsupi** [comment]
How about not set the `DISABLE_AUTH`?
If this is set, the root user will attempt to move the file.

https://github.com/rocker-org/rocker-versioned2/blob/d5e8891f7bebdc9deb12f4785ffcddf485ea0f31/scripts/init_userconf.sh#L14-L17

**Comment by eitsupi** [comment]
Unfortunately, if that were the case you would not be able to use the pre-built images.
I think you need to disable authentication beforehand with an image built with the following Dockerfile.

```dockerfile
FROM rocker/rstudio:4.0.2
RUN mv /etc/rstudio/disable_auth_rserver.conf /etc/rstudio/rserver.conf \
    && echo "USER=rstudio" >>/etc/environment
```

**Comment by kaiyuanlim** [comment]
Seems like the URL is accessible via my ingress now but I now see the following error:

<img width="480" alt="rstudioError" src="https://user-images.githubusercontent.com/78371459/175046625-5f92c84b-ac40-415f-b7cb-b78dddd6f355.png">

**Comment by eitsupi** [comment]
It could be another problem.
If you want to use RStudio Server while limiting permissions, it may be more promising to try `rocker/binder`.
RStudio Server can be started from Jupyter menu.

**Comment by kaiyuanlim** [comment]
Okay, but in general is running Rstudio with readOnlyFileSystem supported?
I know that you guys are using s6, so I had also done the following: https://github.com/just-containers/s6-overlay#read-only-root-filesystem

**Comment by eitsupi** [comment]
My understanding is that is not supported on `rocker/rstudio`.

**Comment by kaiyuanlim** [comment]
Okay, if that is the case, I will close this issue. Thank you
