### ISSUE TITLE
Multiple rstudio images running under Caddy

### ISSUE THREAD

**Issue by alperyilmaz** [rocker-org/rocker-versioned2#496]
### Container image name

rocker/verse:4.2

### Container image digest

rocker/verse@sha256:075f8d7fd904ed69c33a7dbd21b48c1de0925ad796841c79e0892e51a1c1c8e1

### What operating system related to this question?

Linux

### System information

- Docker version: 20.10.17
- docker-compose version: 1.29.2
- Linux kernel: 5.17.5-76051705-generic

### Question

Hi,
I'm using Caddy to serve plumber APIs, shiny apps form separate Docker containers. I was trying to run RStudio instance since I was planning to have separate RStudio instances running separately from separate images. 

I had a problem with RStudio image because of redirects during login process. The problem was mentioned by @noamross in an old Caddy community forum [post](https://caddy.community/t/redirects-for-app-running-as-subfolder-behind-proxy/2816). There's also similar [post](https://caddy.community/t/reverse-proxy-header-down-on-location-header-or-something-equivalent/13157#h-3-the-problem-im-having-6=) in Caddy forum. Both cases suggest redirecting `/rstudio` to `/` which does not work properly and also will not solve "multiple Rstudio instances" case. 

Finally, there's a recently updated *Networking* [page](https://www.rocker-project.org/use/networking) in Rocker documentation which mentions use of Caddy and docker image for RStudio. However, the `proxy` command in that page is not recognized by Caddy, it's probably written for **v1** of Caddy, since [**v2** replaced it](https://caddyserver.com/docs/v2-upgrade#proxy) with `reverse-proxy`. Also, the solution in that page is based on proxying root folder `/` to docker container, which will not work for multiple Docker instances.

So, the solution might be telling the RStudio about the base url it needs to use, then it might be possible to direct instances to specific urls. Is it possible to configure RStudio images  by environment variables or docker run arguments about base url?

**Comment by eitsupi** [comment]
> There's also similar [post](https://caddy.community/t/reverse-proxy-header-down-on-location-header-or-something-equivalent/13157#h-3-the-problem-im-having-6=) in Caddy forum. Both cases suggest redirecting `/rstudio` to `/` which does not work properly and also will not solve "multiple Rstudio instances" case.

Wouldn't this generally be solved by using different subdomains? (e.g. `rstudio1.example.com` and `rstudio2.example.com`)

> So, the solution might be telling the RStudio about the base url it needs to use, then it might be possible to direct instances to specific urls. Is it possible to configure RStudio images by environment variables or docker run arguments about base url?

Please check #388.

**Comment by alperyilmaz** [comment]
thanks @eitsupi , that worked great.
I agree, subdomains might be better option but couldn't make it to work using following lines:
```
rstudio1.{$SERVER_NAME} {
    reverse_proxy rstudio:8787
}
```

however, #388 was godsend, saved me hours of googling, many trials and errors.

**Comment by cboettig** [comment]
@alperyilmaz note that you'll need to give each subdomain a different container name too, e.g. 


```

rstudio1.{$SERVER_NAME} {
  reverse_proxy rstudio1:8787 {
    header_up Host {host}
  }
}

rstudio2.{$SERVER_NAME} {
  reverse_proxy rstudio2:8787 {
    header_up Host {host}
  }
}

```

if you've named the containers `rstudio1` and `rstudio2` respectively.
