### ISSUE TITLE
`-e USER=<new username>` is now deprecated; user permissions issue

### ISSUE THREAD

**Issue by emilmahler** [rocker-org/rocker-versioned2#499]
### Container image name

rocker/rstudio:4.2.1

### System information

- Docker version 19.03.12
- Ubuntu 20.04 LTS (GCP standard VM)

### Question

In the 4.2 (maybe 4.2.1) release of rocker, I now get the following warning:

    Settings by `-e USER=<new username>` is now deprecated and will be removed in the future.
    Please do note use the USER environment variable.

My docker command used to be: `docker run -v /home/my_user:/home/my_user --restart=always -p 8787:8787 -e USER=$USER -e USERID=$UID -e PASSWORD=my_password my_build_geospatial:4.2 &`

When I remove `-e USER=$USER -e USERID=$UID`, the rstudio user does not have access rights to my home folder `my_user`, so the UID doesn't match. How can this be fixed? Here is an example of the permissions issue:

![image](https://user-images.githubusercontent.com/16254022/177488815-5ddd253d-1f88-4570-a2cb-b2def686e9fc.png)

**Comment by eitsupi** [comment]
This command should work.

```sh
docker run -v /home/my_user/subdir:/home/rstudio/subdir --restart=always -p 8787:8787 -e USERID=$UID -e PASSWORD=my_password my_build_geospatial:4.2 
```

Mounting all of a user's home directories is not recommended because of the high possibility of file corruption and incorrect operation.

Please check the reference page.
https://www.rocker-project.org/images/versioned/rstudio.html
