### ISSUE TITLE
Downstream effects from switching the CRAN env var to https://packagemanager.rstudio.com

### ISSUE THREAD

**Issue by lcolladotor** [rocker-org/rocker-versioned2#50]
Hi,

I've noticed that GitHub Actions (GHA) workflows that depend on the rocker docker images have had a bit of a hiccup lately with `remotes::install_dev("pkgdown")` as I reported at https://github.com/r-lib/remotes/issues/501. It seems like the root issue was the recent change at https://github.com/rocker-org/rocker-versioned2/commit/2dcd686abe67040e88ff1317cfc4bc59bb5a7338 which switched the `CRAN` environment variable from `https://cran.r-project.org` to `https://packagemanager.rstudio.com/all/__linux__/bionic/latest` in most cases. Jim Hester at https://github.com/r-lib/remotes/issues/501#issuecomment-630846911 suggests that `options(repos = c(RSPM = "xyz", CRAN = 'abc'))` is the better way to use the RSPM, so would it be ok to:

* revert the `CRAN` environment variable?
* set the `RSPM` environment variable to `https://packagemanager.rstudio.com/all/__linux__/bionic/latest/` (like you had done already)?

I ignore if there were other reasons why you changed `CRAN`, but if you want, I can send a PR that does these 2 changes.

Best,
Leo

**Comment by lcolladotor** [comment]
Hi,

Given that resolving this issue (in appearance) seemed straight forward, I just sent a PR with the suggested code changes.

Best,
Leo

**Comment by cboettig** [comment]
@lcolladotor given discussion in #51 I think we can close this?

**Comment by lcolladotor** [comment]
Yes, based on the promise of adding support for `remotes::install_dev()` in the RSPM noted at https://github.com/rocker-org/rocker-versioned2/pull/51#issuecomment-634694250. Plus the `remotes::install_github()` temporary workaround.

Thanks again for looking into this.
