### ISSUE TITLE
r-ver has python3 installed ... should it?

### ISSUE THREAD

**Issue by mmuurr** [rocker-org/rocker-versioned2#507]
### Container image name

rocker/r-ver:4.0.3

### Container image digest

rocker/r-ver@sha256:c058532fe0273a5cb37898966a85b7df21e228b68158d4bcffb59fe5ec7b7767

### What operating system are you seeing the problem on?

macOS

### Bug description

`rocker/r-ver:4.0.3` seems to have python3 already installed, but when walking through the Dockerfiles and stack JSON files, it looks to me like that's unintended. I only discovered this when trying to install python3 myself on top of this image and found a version mismatch. More evidence suggesting this is unintended:
1. `ubuntu:focal` (`r-ver`'s base layer) does _not_ have python3 installed.
2. The repo's README says, "Adds cuda and Python to 'r-ver'" (suggesting Python) is not expected to be part of `r-ver`.

Perhaps this is intended?

### How to reproduce this bug?

```sh
docker run -it --rm rocker/r-ver:4.0.3 python3 --version
```

**Comment by eitsupi** [comment]
I think this is a documentation issue.
`rocker/r-ver` seems to install python3 at the following location (devscripts).

https://github.com/rocker-org/rocker-versioned2/blob/bfecf9e8a492a7ac31ff18109fce7e32f4a23723/scripts/install_R_source.sh#L34-L37

https://packages.ubuntu.com/en/bionic/devscripts

But I don't understand why devscripts is here and what is really needed.

**Comment by benz0li** [comment]
@eitsupi Cross reference: https://github.com/rocker-org/rocker-versioned/issues/166

**Comment by eitsupi** [comment]
@benz0li Thanks for sharing that. I am convinced.

**Comment by benz0li** [comment]
Added here: https://github.com/rocker-org/rocker-versioned2/commit/7e065a9d71b8ff2561f7f53c107129246864021e

**Comment by eitsupi** [comment]
Tracking this discussion, I see that `rocker/drd` doesn't like the devscripts dependencies (like python3) and only extracts `checkbashisms` and includes it in the source code.

https://github.com/rocker-org/rocker-versioned/pull/167#issuecomment-549041154
https://github.com/rocker-org/drd/blob/06ab465832ab7c77335d16f9e934d03bdb0493c4/checkbashisms

I suppose we could do the same thing here.

**Comment by eddelbuettel** [comment]
I had very much forgotten about that but yes -- I noticed that to run `checkbashishm` I didn't need all the other parts, and the script itself was both small and stable (as in: no or few changes in recent years) so I guess I just 'vendored' it.

**Comment by eitsupi** [comment]
I have created a new issue #510 about the installation of devscripts.
