### ISSUE TITLE
Remove `devscripts` installation from install R scripts to reduce container size

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#510]
Tracking this discussion, I see that `rocker/drd` doesn't like the devscripts dependencies (like python3) and only extracts `checkbashisms` and includes it in the source code.

https://github.com/rocker-org/rocker-versioned/pull/167#issuecomment-549041154
https://github.com/rocker-org/drd/blob/06ab465832ab7c77335d16f9e934d03bdb0493c4/checkbashisms

I suppose we could do the same thing here.

_Originally posted by @eitsupi in https://github.com/rocker-org/rocker-versioned2/issues/507#issuecomment-1190315281_

**Comment by cboettig** [comment]
yeah good idea

**Comment by cboettig** [comment]
Right, I guess maybe there are some concerns with this not coming from the official ubuntu repo, not sure if that has any chance of interacting with version issues or whatnot.  I do recall `devscripts` is kinda big, but then I think some of the other deps there might be used implicitly in later images too, so this could have downstream impacts on the stack?  Maybe more evaluation is needed here.

**Comment by eitsupi** [comment]
Yeah, I think we need to update the test to at least make sure `rocker_scripts` can run.

**Comment by eitsupi** [comment]
> Right, I guess maybe there are some concerns with this not coming from the official ubuntu repo

I think we can temporarily install the `devscripts` as `$BUILDDEPS`, copy the `checkbashisms` file (`/usr/bin/checkbashisms`) locally (to `/usr/local/bin/checkbashisms`, like `rocker/drd`), and then remove `devscripts` as `$BUILDDEPS`.
Let's try this.

https://github.com/rocker-org/rocker-versioned2/blob/3edae7e2a3ba4a418e9f5aa551800c031faeb265/scripts/install_R_source.sh#L60-L91
