### ISSUE TITLE
persistence of home directory

### ISSUE THREAD

**Issue by geoHeil** [rocker-org/rocker-versioned2#514]

**Comment by eitsupi** [comment]
> `/workspace` is a path below the "home" directory and thus not in the user's space, and requires root access.

I do not think this information is accurate.
If we bind-mount `/workspace` directory that does not exist in the image, the directory will be owned by the same UID as on the Docker host, so for example, if we bind-mount a user's directory with UID 1000 to `/workspace`, the directory will be owned by the same UID as on the container, the `rstudio` user.

**Comment by cboettig** [comment]
yes thanks.
