### ISSUE TITLE
Git 2.18 or newer request, motivated from GitHub action workflows

### ISSUE THREAD

**Issue by lcolladotor** [rocker-org/rocker-versioned2#52]
Hi,

This is a feature request and not a bug report.

GitHub Actions has two types of behavior depending on the version of `git` available with version 2.18 being the breaking point. Ubuntu 18.04 official supports `git` version 2.17.1 (through `apt-get`) but it's possible to compile a newer `git` version on it. I'm using the Bioconductor docker images based on Rocker 4.0 for Ubuntu 18.04 on GitHub Action workflow checks. It takes ~3 minutes to compile a newer version of `git`, but well, maybe you would consider adding a newer version of `git` on your Rocker images if you think that this is request that would help others (maybe even yourselves if you use Rocker images with GHA).

## Details

https://github.com/actions/checkout has two versions (`v1` and `v2`). `v2` is the one recommended by `r-lib/actions` with reasons highlighted at https://github.com/r-lib/actions/issues/50. As noted at https://github.com/actions/checkout#checkout-v2 and reported in issues like https://github.com/actions/checkout/issues/238, `actions/checkout@v2` does not clone a git repo unless the `git` version is 2.18 or newer. Without a working local clone, you can't run commands like `pkgdown::deploy_to_branch()` or other code that relies on having a working git clone. By adapting https://www.digitalocean.com/community/tutorials/how-to-install-git-on-ubuntu-18-04 I was able to compile `git` 2.26.2 (latest stable release) as shown at https://github.com/lcolladotor/biocthis/blob/master/actions/check-bioc.yml#L117-L130. That is:

```bash
sudo apt-get update -y
sudo apt install make libssl-dev libghc-zlib-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip -y
wget https://github.com/git/git/archive/v2.26.2.zip -O git.zip
unzip git.zip
cd git-*
make prefix=/usr all
sudo make prefix=/usr install
cd -
git --version
```

If you think that installing `git` 2.18 or newer is of interest, I can try to send a PR with the above code, though I'm not 100% sure which file(s) it would need to live at.

Of course, I also understand that you might want to keep the installed software restricted to `apt-get` and avoid compiling if possible (that was what Bioconductor decided regarding their images). Ultimately, I can use the docker images inherited from Rocker without issues (~3 minutes is not much given the generous time limits provided by GitHub Actions system for open source software).

Best,
Leo

**Comment by eddelbuettel** [comment]
Thanks for the post.  Allow to propose an alternative.

The cleanest way to deal with one-off requirements like this, I find, is to provide locally used packages (for Ubuntu) in a PPA.

Here you don't even need to concern yourself with packaging.  Take the existing (newer) Debian `git` package, upload it to a PPA, use it.  That same pattern has served me extremely well for many years for direct use (when I wanted something not yet in Ubuntu), continuous integration (to let Travis CI have), Rocker builds, ...  

Otherwise, I would suggest not to push "old" base layes (18.04 is no longer current) with "newest" apps a little problematic---and experience has shown that it can indeed lead to hickups.  We are allowing ourselves a newer R because, well, this is an R-focussed project.  I am not sure I'd recommend generalising it for all use case just because of a local deployment which is better controlled by the local user---you in this.

**Comment by noamross** [comment]
I'm not sure we want to move to unpinning software versions from those available in the stable Ubuntu repositories. A question to understand your use-case, though: How onerous would it to be to use your own image, built off the rocker image, with updated git? We'd like to make it so people can customize images from Docker easily rather than us keep adding more flavors.  If this is a common use-case, we could add potentially add `scripts/install_git_from_source.sh`.

**Comment by lcolladotor** [comment]
Thanks for the info Dirk! I don't really use Ubuntu so some of the concepts you described are new to me.

## PPA

I see at https://askubuntu.com/questions/71510/how-do-i-create-a-ppa that PPA stands for _Personal Package Archive_ and there are steps there listed, particularly at https://askubuntu.com/a/71516, on how to do so. 

## Searching a git latest release PPA

For getting the newer Debian `git` package, I ended up at https://launchpad.net/~git-core/+archive/ubuntu/candidate where I see that there is an entry for git 2.26.2 for Ubuntu 18.04. 

<img width="740" alt="Screen Shot 2020-05-19 at 3 51 20 PM" src="https://user-images.githubusercontent.com/2288213/82371683-9802bc80-99e8-11ea-9ab9-26932e9baabf.png">

Hm... so, to actually use it, hm. Ok, under "Adding this PPA to your system" I see that this code should do it:

```bash
sudo add-apt-repository ppa:git-core/candidate
sudo apt-get update
```

<img width="477" alt="Screen Shot 2020-05-19 at 3 54 05 PM" src="https://user-images.githubusercontent.com/2288213/82371905-fa5bbd00-99e8-11ea-8d61-3db8e24a7566.png">

## Using the latest git release PPA

This took me the longest, partially because I was testing locally with an older (pre R 4.0) Bioconductor-devel docker image (from when Rocker was based on Debian instead of Ubuntu 18.04). I see from Google that Debian is a different Linux :O (aye, beginner over here).

I was finally able to install the latest stable `git` release using `apt-get` and the above PPA with:

```bash
## to be able to install software properties
sudo apt-get update -y
## to be able to use add-apt-repository
sudo apt-get install software-properties-common -y
## to use stable releases of git that are already in a PPA at
## https://launchpad.net/~git-core/+archive/ubuntu/candidate
sudo add-apt-repository ppa:git-core/candidate -y
## Update
sudo apt-get update -y
## Upgrade git and other tools
sudo apt-get upgrade -y
```

which I just tested on GitHub Actions through https://github.com/lcolladotor/biocthis/commit/4e81b3d09e41527225fb742cac1c5b33791a86d4. I see at https://github.com/lcolladotor/biocthis/runs/691635667?check_suite_focus=true#step:3:373 that it only took 22 seconds =) so this is much faster than my previous 3 min compiling `git` from source solution. Thanks Dirk! ^_^



## Making this more general

I understand that making this solution more general is not really either recommended or even necessary. 

Regarding the idea of a docker image that I build myself on top of the Bioconductor docker image (which expands the Rocker image), well, based on my limited understanding this would involve re-making the image every week (Bioconductor rebuilds their images on Fridays) and given that it's now only 22 seconds to install `git`, I don't think that it's worth the effort. Though I saw that you are also playing with building Rocker images using GHA, and I guess that you might set a cron job that way (I've read that you can do so with GHA, I have no actual experience doing so). 

As for how general this use case will be, well, in my own case, I want to use the Bioconductor docker images for all my R packages at https://lcolladotor.github.io/pkgs/ and that's what I'm encouraging at `biocthis`. But the main `r-lib/actions` GHA workflow doesn't use docker https://github.com/r-lib/actions/blob/master/examples/check-standard.yaml and their example docker GHA doesn't use `github/checkout@v2` https://github.com/r-lib/actions/blob/master/examples/docker.yaml (v1 doesn't have the git version issue, but it has other problems). Maybe others will run into this `git` version issue for `github/checkout@v2` when using Rocker docker images and at point, hopefully the above code will be useful to them.

Given all the above, I'm closing this issue. Thanks again for your help!

Best,
Leo

**Comment by eddelbuettel** [comment]
Good move on finding an existing PPA with the updated software you need -- that it is a pretty common too, and I am glad (and impressed) ;-) you worked it out so fast.

**Comment by lcolladotor** [comment]
Thank you Dirk =) ^_^
