### ISSUE TITLE
cannot open URL in check --as-cran

### ISSUE THREAD

**Issue by raul-ortega** [rocker-org/rocker-versioned2#532]
### Container image name

rocker/tidyverse

### Container image digest

rocker/tidyverse@sha256:cbf4f03e1dc840b3b7dfcec775b2bfbff4848d77015265ed5adf6ee2ec4eda56

### What operating system are you seeing the problem on?

Linux

### System information

Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:53 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Bug description

* checking CRAN incoming feasibility ...Warning in url(sprintf("%s/%s", cran, path), open = "rb") :
  cannot open URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/Meta/current.rds': HTTP status was '404 Not Found'
Error in url(sprintf("%s/%s", cran, path), open = "rb") : 
  cannot open the connection to 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/Meta/current.rds'
Execution halted

### How to reproduce this bug?

```sh
# run container
docker run -ti rocker/tidyverse /bin/bash
```

Once in the container prompt:

```sh
# instal dependencies
apt-get update
apt-get install -y --no-install-recommends libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git libv8-dev
apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc

# install R packages
R -e 'install.packages(c("covr", "testthat", "spelling"));'
R -e 'install.packages(c("circlize", "xml2", "httr", "circlize", "RColorBrewer", "R6"));'

# clone repository avidaR
git clone https://gitlab.com/fortunalab/avidaR.git

# build package
R CMD build avidaR/ --no-build-vignettes --no-manual ../avidaR.zip

# check as CRAN
R CMD check --as-cran --no-manual avidaR_1.1.3.tar.gz
```

**Comment by eitsupi** [comment]
That image is not a real CRAN by default, but RStudio Public Package Manager is set as the CRAN mirror.
You can switch which CRAN mirror to use with the following command:

```sh
echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >>"${R_HOME}/etc/Rprofile.site"
```

https://rocker-project.org/images/versioned/r-ver.html#switch-the-default-cran-mirror

**Comment by raul-ortega** [comment]
Dear @eitsupi

It works great! Thanks so much.

**Comment by cboettig** [comment]
Just a footnote that switching to a standard CRAN mirror will mean that installs are always built from source, whereas RStudio package manager provides linux binaries.  Source builds can in some cases take much much longer.

**Comment by eddelbuettel** [comment]
Just another footnote that there is a CRAN-alike (complete) repo with full binaries and full dependency resolution (an improvement over RSPM) building on top of the RSPM binaries and freeing you from having to compile.  It works like CRAN 'so everything in current version' and has no timemachine-feature. See https://eddelbuettel.github.io/r2u/

**Comment by ChristineStawitz-NOAA** [comment]
Thanks for pointing me towards this issue @eitsupi . I confirmed `devtools::check()` works if I run the `options(repo=c(CRAN = "https://cloud.r-project.org"))` directly in the R terminal after opening the codespace. However, if I switch the default CRAN mirror in the Dockerfile as outlined in [section 4.1](https://rocker-project.org/images/versioned/r-ver.html#switch-the-default-cran-mirror) of the documentation, I still get the error when I open the codespace and run `devtools::check()` This is an image that is used only for package development, so I would like the switch to be part of the prebuild. Please let me know if I'm missing something in the setup. Thanks!

**Comment by eitsupi** [comment]
@ChristineStawitz-NOAA Looking at the file you linked to from rocker-org/devcontainer-features#156 I don't think it uses a Dockerfile.
https://github.com/NOAA-FIMS/FIMS/blob/e1b5631be58e275452c8b299e4680e662d238233/.devcontainer/devcontainer.json#L6

In any case, note that the CRAN mirror must be changed after the package installation is complete.
I think you can do this right after container creation by writing something like the following in the `postCreateCommand` of devcontainer.json.

```json
"postCreateCommand": "sudo echo 'options(repos = c(CRAN = \"https://cloud.r-project.org\"))' >>\"${R_HOME}/etc/Rprofile.site\""
```

**Comment by ChristineStawitz-NOAA** [comment]
Thanks! I tried the postCreateCommand option you suggested and also: 
`	"postCreateCommand": "R -q -e 'options(repos = c(CRAN = 'https://cloud.r-project.org'))'",` but they did not work.

We also have a package that causes an error because it requires a source install. Is there a way to do that within the packages feature, or should we use `postCreateCommand` there also?

Thanks!

**Comment by eitsupi** [comment]
@ChristineStawitz-NOAA Could you please create other issues with reproducible examples and detailed error description since it is irrelevant to the original issue?

**Comment by eitsupi** [comment]
ref #608
