### ISSUE TITLE
Compilation of Quarto document to PDF fails with XeLaTeX

### ISSUE THREAD

**Issue by rgaiacs** [rocker-org/rocker-versioned2#536]
### Container image name

rocker/verse:4.2

### Container image digest

rocker/verse@sha256:70b28cc0719b2ffd3ae377bc6788ca7253b8c9286a3a2eebb714c73585f42ed2

### What operating system are you seeing the problem on?

Linux

### System information

- `Linux 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022`
- Docker version 20.10.17, build 100c701
- Docker Compose version v2.6.0

### Bug description

```
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
finding package for amsmath.sty
> 2 packages to install
> installing amsmath (1 of 2)
> installing latex-amsmath-dev (2 of 2)
  This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)
   restricted \write18 enabled.
  
  kpathsea: Running mktexfmt xelatex.fmt
  mktexfmt [ERROR]: -user mode but path setup is -sys type, bailing out.
  I can't find the format file `xelatex.fmt'!
  

compilation failed- missing packages (automatic installation failed)
```

### How to reproduce this bug?

1. Create a new Quarto document with

```md
---
format:
  pdf:
    documentclass: article
    geometry:
    - margin=20mm
    papersize: a4
---
```

2. Render the document.

**Comment by eitsupi** [comment]
Could you please provide a detailed bug description?
It looks to me like you just pasted the log in its entirety, not the bug description.

BTW, I don't think this is a bug in this image because I was able to successfully generate a pdf from the following qmd file.

```qmd
---
format:
  pdf:
    documentclass: article
    geometry:
    - margin=20mm
    papersize: a4
---

it's a test.
```
