### ISSUE TITLE
Azure flags numerous high severity security vulnerabilities for Ubuntu

### ISSUE THREAD

**Issue by barryhoughton** [rocker-org/rocker-versioned2#549]
### Container image name

rocker/r-ver:latest

### What operating system are you seeing the problem on?

Linux

### System information

Azure

### Bug description

Azure has identified a number of high severity security issues due to the base image of Ubuntu being used.

Is there a timescale for when the base image will be updated to Ubuntu 22.04 LTS?

Kind regards,
Barry

**Comment by eitsupi** [comment]
Hello. Thanks for reporting it.
But that sounds pretty weird since `ubuntu:focal` is still supported and gets frequent security updates.

The switch to `ubuntu:jammy` is scheduled to start from R4.2.2 (#282), but I'm wondering if updating to jammy will solve your problem.

**Comment by barryhoughton** [comment]
Ah ok, my misunderstanding!

It turns out that I was using r-ver:4.1.2 as my base image, which was built about 3 months ago, so doesn't contain the fixes that have since been added to ubuntu:focal.

I'll update to using r-ver:latest and hopefully that will fix my issue.

**Comment by eddelbuettel** [comment]
Yes we generally follow the distro which itself follows the CVEs.  So if you stay current you should be fine.

**Comment by barryhoughton** [comment]
Great, thanks for confirming!
