### ISSUE TITLE
Script install_shiny_server.sh when using custom SHINY_SERVER_VERSION 1.5.19.995 refers to https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.19.995-amd64.deb which gives 404

### ISSUE THREAD

**Issue by mskyttner** [rocker-org/rocker-versioned2#550]
### Container image name

rocker/ml-verse:4.2.1

### Container image digest

rocker/ml-verse@sha256:c793fb4b5a3da479b81e9429e565d1f3fa5d6a221786c4dfbcf0deec764d07d3

### What operating system are you seeing the problem on?

Linux

### System information

Docker version 20.10.19, build d85ef84                                          
Kernel 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Bug description

It may be related to setting the SHINY_SERVER_VERSION to 1.5.19.995, causing https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_shiny_server.sh#L38 to attempt to download from `ubuntu-14.04` directory which does not have this file:

#0 28.17 https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.19.995-amd64.deb:
#0 28.17 2022-10-18 09:35:51 ERROR 404: Not Found.

### How to reproduce this bug?

```sh
Use a Dockerfile with


FROM rocker/ml-verse:4.2.1
ENV SHINY_SERVER_VERSION 1.5.19.995
RUN /rocker_scripts/install_shiny_server.sh
```

**Comment by eitsupi** [comment]
Thanks for catching this!
Could you send a PR for fixing it?

**Comment by mskyttner** [comment]
Do you prefer hardcoding the value in the script to "18.04" or using a variable like UBUNTU_VERSION like this?

```bash
#!/bin/bash
set -e

SHINY_SERVER_VERSION=${1:-${SHINY_SERVER_VERSION:-latest}}
UBUNTU_VERSION=${1:-${UBUNTU_VERSION:-18.04}}

## build ARGs
NCPUS=${NCPUS:--1}

# a function to install apt packages only if they are not installed
function apt_install() {
    if ! dpkg -s "$@" >/dev/null 2>&1; then
        if [ "$(find /var/lib/apt/lists/* | wc -l)" = "0" ]; then
            apt-get update
        fi
        apt-get install -y --no-install-recommends "$@"
    fi
}

apt_install \
    sudo \
    gdebi-core \
    libcurl4-openssl-dev \
    libcairo2-dev \
    libxt-dev \
    xtail \
    wget

# Run dependency scripts
/rocker_scripts/install_s6init.sh
/rocker_scripts/install_pandoc.sh

# Install Shiny server

if [ "$SHINY_SERVER_VERSION" = "latest" ]; then
    SHINY_SERVER_VERSION=$(wget -qO- https://download3.rstudio.org/ubuntu-${UBUNTU_VERSION}/x86_64/VERSION)
fi

wget --no-verbose "https://download3.rstudio.org/ubuntu-${UBUNTU_VERSION}/x86_64/shiny-server-${SHINY_SERVER_VERSION}-amd64.deb" -O ss-latest.deb
gdebi -n ss-latest.deb
rm ss-latest.deb

# Get R packages
install2.r --error --skipinstalled -n "$NCPUS" shiny rmarkdown

# Set up directories and permissions
if [ -x "$(command -v rstudio-server)" ]; then
    DEFAULT_USER=${DEFAULT_USER:-rstudio}
    adduser "${DEFAULT_USER}" shiny
fi

cp -R /usr/local/lib/R/site-library/shiny/examples/* /srv/shiny-server/
chown shiny:shiny /var/lib/shiny-server
mkdir -p /var/log/shiny-server
chown shiny:shiny /var/log/shiny-server

# create init scripts
mkdir -p /etc/services.d/shiny-server
cat <<"EOF" >/etc/services.d/shiny-server/run
#!/usr/bin/with-contenv bash
## load /etc/environment vars first:
for line in $( cat /etc/environment ) ; do export $line > /dev/null; done
if [ "$APPLICATION_LOGS_TO_STDOUT" != "false" ]; then
    exec xtail /var/log/shiny-server/ &
fi
exec shiny-server 2>&1
EOF
chmod +x /etc/services.d/shiny-server/run

# install init script
cp /rocker_scripts/init_set_env.sh /etc/cont-init.d/01_set_env

# Clean up
rm -rf /var/lib/apt/lists/*
rm -rf /tmp/downloaded_packages

## Strip binary installed lybraries from RSPM
## https://github.com/rocker-org/rocker-versioned2/issues/340
strip /usr/local/lib/R/site-library/*/libs/*.so

```

**Comment by eitsupi** [comment]
Given that it is not related to the version of Ubuntu on which it is running, I don't think it is worth having it as a variable.

Actually, the images in this repository only install the latest version of Shiny Server, so hard-coding would not be a problem.

It is ok too for trying two URLs in succession, as shown below, I think.

https://github.com/rocker-org/rocker-versioned2/blob/afb562b1948620d5e03d8bab27b8391e0ea799af/scripts/install_rstudio.sh#L63-L64

**Comment by mskyttner** [comment]
Ok, will take a stab at that change in a while.

**Comment by mskyttner** [comment]
I'm not sure how to best discover where to download the "latest stable" binary, other than scraping the web page? Maybe hardcoding to "18.04" will be simplest and work well for a while. 

There seems to be at least download{1,2,3}.rstudio.org which serve up the binaries from S3 buckets. Not sure if the latest stuff always is put on the third one. 

A flaky script to scrape for the latest version from the web page:

```r
shiny_server_latest_download <- function(
    flavor = c("ubuntu", "redhat-centos", "suse"),
    quiet = TRUE) {
  
  variant <- match.arg(flavor)
  url <- sprintf("https://www.rstudio.com/products/shiny/download-server/%s/", variant)
  if (!quiet) message("Scraping ", url, " for shiny server download location")

  location <- 
    httr::content(httr::GET(url)) %>%
    xml2::xml_find_all("//pre") %>% 
    xml2::xml_text() %>%
    .[grep("https://download\\d+.*", .)] %>%
    gsub(".*?(https://.*?)\\n.*$", "\\1", .)
  
  version <- gsub(".*?(\\d+.\\d+.\\d+.\\d+).*", "\\1", location)
  setNames(location, version)
  
}
#shiny_server_latest_download()
#shiny_server_latest_download("redhat")
#shiny_server_latest_download("suse")
``` 

```r
> shiny_server_latest_download()
                                                                           1.5.19.995 
"https://download3.rstudio.org/ubuntu-18.04/x86_64/shiny-server-1.5.19.995-amd64.deb" 

> shiny_server_latest_download("redhat")
                                                                       1.5.19.995 
"https://download3.rstudio.org/centos7/x86_64/shiny-server-1.5.19.995-x86_64.rpm" 

> shiny_server_latest_download("suse")
                                                                       1.5.19.995 
"https://download3.rstudio.org/centos7/x86_64/shiny-server-1.5.19.995-x86_64.rpm" 
```
There are minor versions that are more recent than the recommended version at the web page, a 1.5.19.996 version available but not suggested for download in the webpage.

**Comment by eitsupi** [comment]
> There are minor versions that are more recent than the recommended version at the web page, a 1.5.19.996 version available but not suggested for download in the webpage. So the VERSION file differs from what the web page suggests:

I had noticed that too, but I don't see a problem with continuing to refer to these files.
