### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by noamross** [rocker-org/rocker-versioned2#57]
-  [ ] READMEs in `rocker-versioned`, `shiny`, and `geospatial` and `binder`
 -  [ ] github issue templates and possibly CONTRIBUTING directing people to appropriate repositories.

Include:
- Key differences between pre-4.0.0 and post 4.0.0 images
- Shiny install workflow and supervisor
- Use of scripts to install modules
- RSPM
- ?? @cboettig

**Comment by cboettig** [comment]
List looks good.  

I suppose the upstream part about how Dockerfiles are generated from `stacks` is more of a developer issue that can be addressed separately.  (Could be a good blog post topic?)

What about comments on the appropriate use of scripts?  (e.g. most scripts are written to be compatible across bionic and focal, but I think we should launch with the position that we only "support" `focal` (?).   Likewise, most scripts can be mixed-matched, but we need more testing on that.  but these are more developer issues.    

Likewise, some mention of the `ml` image / CUDA stack would be premature still?

I think we can avoid any discussion of "new tags" at this point.  We just have the `4.0.0 == latest` tag for the most part.  There's a few special tags in `geospatial` that pertain to `bionic` (i.e. ubuntu18.04 and ubuntu18.04-unstable) but moving to `focal` for `geospatial:4.0.0` means that it gets modern Proj / Geos / gdal 'for free'.  


There's a handful of very minor/subtle issues:

-  `verse` adds the `ppa:cran/travis` PPA on `bionic` to avoid some special lib cases there, but we're not aiming at bionic builds anyway.  The tinytex installation is tweaked slightly (some tweaking in the recipe was required for Ubuntu, it's also made slightly lighter, should have what you need to build manuals, and should avoid warnings), but these should be quite invisible :crossed_fingers: . 

- you added support for switching to RStudio preview or daily with env vars, though we don't ship images with that selected.

- you cleaned up some of the stuff related to pandoc, and modular scripts have made sure the separate shiny / shiny-verse stacks match the rstudio stacks.  

- there's more alignment between binder and ml, though we never officially launched a stable ml image anyway.  (getting close though I think)

**Comment by cboettig** [comment]
noted in README
