### ISSUE TITLE
Clean up /opt directory in geospatial

### ISSUE THREAD

**Issue by rdenham** [rocker-org/rocker-versioned2#571]
The rocker/geospatial:4.2.2 image seems to have a fair bit of leftover build files in `/opt/grib2`,

```sh
singularity exec docker://rocker/geospatial:4.2.2 du -sh /opt/grib2
INFO:    Using cached SIF image
179M    /opt/grib2
```

```sh
singularity exec docker://rocker/geospatial:4.2.2 ls -l  /opt/grib2/|grep .gz
INFO:    Using cached SIF image
-rw-r--r--  1 root root  8406357 Sep 26  2013 gctpc20a.tgz
-rw-r--r--  1 root root  1166082 Jul  6  2018 jasper-1.900.1-14ubuntu3.2.debian.tgz
-rw-r--r--  1 root root  3119620 Oct 19  2017 libaec-1.0.2.tar.gz
-rw-r--r--  1 root root  1118350 Mar 29  2022 libpng-1.2.59.tar.gz
-rw-r--r--  1 root root 11572512 Jun 28  2012 netcdf-3.6.3.tar.gz
-rw-r--r--  1 root root  2233229 Aug 23  2021 openjpeg-2.4.0.tar.gz
-rw-r--r--  1 root root   785279 Jun 22  2012 proj-4.8.0.tar.gz
-rw-r--r--  1 root root  1490071 Mar 29  2022 zlib-1.2.12.tar.gz
```

I don't *think* these are needed after the build, so perhaps they could be cleaned up. Looks like they are installed via 
[scripts/install_wgrib2.sh](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_wgrib2.sh)

Perhaps there could be a bit of clean up in that script to remove unnecessary build files.

**Comment by cboettig** [comment]
indeed, good catch.  A PR would be welcome!

(it may also be worth deprecating that script entirely, I've found that recent GDAL versions from OSGEO handle grib files just fine already...)

**Comment by rdenham** [comment]
Thanks @cboettig I'll crate a PR and update this issue

**Comment by rdenham** [comment]
See this PR #576 

I tested reading of grib file using gdalinfo, and also `terra::rast` and seems fine.

There may be others who rely on `wgrib` but I wasn't sure how to identify those to check if they would be affected.

**Comment by eitsupi** [comment]
Reopen as it has not been resolved for focal based images.
