### ISSUE TITLE
Consistency with the name of repository and the version of R

### ISSUE THREAD

**Issue by atusy** [rocker-org/rocker-versioned2#59]
Hi. Is this a repository that will curate R 4.x.x, and will R 5.x.x be in the `rocker-versioned3`?
If so, I'd suggest the name of this repository be `rocker-versioned4` to improve the consistency with the version of R.
For example, [tidyverse/googlesheets4](https://github.com/tidyverse/googlesheets4) indicates it is using the API version 4.

**Comment by eddelbuettel** [comment]
No, this is simply the second iteration of r-versioned.

**Comment by atusy** [comment]
Thanks. If the consistency won't matter, that is fine for me.

**Comment by cboettig** [comment]
@atusy thanks, like Dirk says, this is more about a changing build architecture (auto-generated Dockerfiles) than a change in R version.  We may merge this back into `rocker-versioned` repo once it's stable
