### ISSUE TITLE
Github Repo using Dockerfile pulling from binder image version 4.2.2 does not launch properly on mybinder.org

### ISSUE THREAD

**Issue by annakrystalli** [rocker-org/rocker-versioned2#601]
### Container image name

rocker/binder:4.2.2

### What operating system are you seeing the problem on?

Linux

### System information

mybinder.org

### Bug description

Github Repo using Dockerfile pulling from version 4.2.2 does not launch properly on mybinder.org

### How to reproduce this bug?

This link with Dockerfile based on binder:4.2.2 does not launch successfully on mybinder.org: <https://mybinder.org/v2/gh/annakrystalli/holepunch-compendium/b741a6b?urlpath=rstudio>

This link with Dockerfile based on binder:4.2.0 launches successfully: <https://mybinder.org/v2/gh/annakrystalli/holepunch-compendium/5b76763?urlpath=rstudio>

Repo/branch in question: https://github.com/annakrystalli/holepunch-compendium/tree/docker

```sh
```

**Comment by eitsupi** [comment]
I think this is duplicate of #505

**Comment by annakrystalli** [comment]
It refers to a different version (4.2.2). Just wanted to make sure you are aware of it.

**Comment by eitsupi** [comment]
> It refers to a different version (4.2.2). Just wanted to make sure you are aware of it.

I am aware of it. I think this problem has just never been fixed since #505.
