### ISSUE TITLE
Updating CRAN location in postCreateCommand of devcontainer.json not working

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [rocker-org/rocker-versioned2#608]
### Container image name

rocker/r-ver:4.2

### What operating system are you seeing the problem on?

Linux

### Bug description

We need to change the library location using `options(repos = c(CRAN = \"https://cloud.r-project.org\"))`
to run `devtools::check()` on a package that depends on Template Model Builder, but this [line ](https://github.com/ChristineStawitz-NOAA/setCRAN/blob/2fe9a7935d8cdef840c4b66df876fbbc5baf2410/.devcontainer/devcontainer.json#L25) in the devcontainer.json does not include it in the prebuild

The minimal steps to reproduce are creating an empty R package, adding [TMB ](https://cran.r-project.org/web/packages/TMB/index.html) to its Imports and linkingTo fields, and then opening a codespace and trying to run `devtools::check()` in the R terminal

### How to reproduce this bug?

```r
devtools::check()
```

**Comment by eitsupi** [comment]
Please configure like that:

```json
{
	"image": "ghcr.io/rocker-org/devcontainer/r-ver:4",
	"postCreateCommand": "echo 'options(repos = c(CRAN = \"https://cloud.r-project.org\"))' | sudo sh -c 'cat - >>\"${R_HOME}/etc/Rprofile.site\"'"
}
```

I will mention this later in the documentation.
