### ISSUE TITLE
R-patched 'wget' gets the file 'R-rc' 

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker-versioned2#61]
The download and untar of the `R-patched.tar.gz` ends results in a folder called `R-rc`. 

https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_R.sh#L106

The `cd R-${R_VERSION}` fails because it's looking for `R-patched`, but needs `R-rc`.

**Comment by eddelbuettel** [comment]
Yes. That always bites the few days a release is cut.  I think I navigate around that in one of the containers where I build from source:  

https://github.com/rocker-org/drp/blob/76788d25cf52c0ef1259fc35359afc74bcb8eaea/Dockerfile#L66-L71

**Comment by nturaga** [comment]
This is helpful! Thanks @eddelbuettel.

**Comment by nturaga** [comment]
Just a follow up @eddelbuettel , Can we add something like this in the `install_R.sh` script as well? https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_R.sh#L106

**Comment by cboettig** [comment]
Well somehow I'm way behind here, apologies!  yeah, adding logic to deal with this would be welcome. thanks

**Comment by eitsupi** [comment]
Fixed by #386

It should work now because it uses wildcard when exec the `cd` command.
https://github.com/rocker-org/rocker-versioned2/blob/cfac661b2871f59b31b8d56b3c6217cd6d521c5b/scripts/install_R_source.sh#L111-L112
