### ISSUE TITLE
column arrows missing

### ISSUE THREAD

**Issue by ssb-jnk** [rocker-org/rocker-versioned2#611]
Hi, recently a user in my firm noticed the arrow icons are missing when viewing a large dataset, notice the squares looking like iphones. I am running rocker/r-ver:4.2.2
<img width="507" alt="image" src="https://user-images.githubusercontent.com/27926676/225046467-4888c12e-ec92-457d-9f16-a0eb098b32a4.png">

Example code to replicate the problem

```
data <- matrix(rnorm(50 * 50), nrow = 50, ncol = 50)
View(data[1:50, 1:50])
```
 
Console errs:
gridviewer.html:8 GET https://myserver:8787/grid_resource/closest_polyfill.js net::ERR_ABORTED 404 (Not Found)
icons.css:1 GET https://myserver:8787/fonts/icomoon.woff?tkyb2q net::ERR_ABORTED 404 (Not Found)

**Comment by eitsupi** [comment]
Could you describe the problem in more detail? Perhaps a problem with RStudio IDE?
If so, I think you need to report it in https://github.com/rstudio/rstudio, not here.

Since `rocker/r-ver:4.2.2` does not include RStudio IDE or something like that, I don't know what you are seeing.

**Comment by eitsupi** [comment]
It seems to be a issue of RStudio IDE, so I'm closing it.
