### ISSUE TITLE
Strategy for Docker Hub withdrawing free Open Source organizations

### ISSUE THREAD

**Issue by yrro** [rocker-org/rocker-versioned2#615]
### Container image name

rocker/r-ver

### Question

I wondered if you'd given any thought to how to deal with Docker Hub closing down Open Source organizations:

https://blog.alexellis.io/docker-is-deleting-open-source-images/

e.g., moving to `docker.io/library/r-ver`, moving to another container registry, etc...

**Comment by eitsupi** [comment]
Note, by the way, that images from this repository have been pushed to the GHCR for a year (#456).

**Comment by mg4579** [comment]
[https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)

With this new FAQ, which repos supported by the Rocker Community will be affected? Looking into it r-base seems to be ok, but it is and also is not an image maintained by Rocker.

**Comment by eddelbuettel** [comment]
(r-base is their build, rocker/r-base is ours.  Botht use the same Dockerfile.  We maintain it in their repo via PRs)

**Comment by yrro** [comment]
That's good news. I was always confused about the difference between `docker.io/library/r-base` and `docker.io/rocker/r-base` - now I understand the difference.

**Comment by eitsupi** [comment]
I believe this has been resolved by the DockerHub policy change and rocker-org becoming Sponsored OSS.
