### ISSUE TITLE
When do RSPM freezes happen?

### ISSUE THREAD

**Issue by jimjam-slam** [rocker-org/rocker-versioned2#619]
### Container image name

ghcr.io/rocker-org/devcontainer/r-ver:4.2

### Container image digest

ghcr.io/rocker-org/devcontainer/r-ver@sha256:13a4c1f57a2155bc4f5bae032c87fd7fa22918d6419b749fab3aae0120d80d6a

### What operating system related to this question?

macOS

### System information

- Docker version 4.17.0

### Question

The [Rocker docs](https://rocker-project.org/images/versioned/r-ver.html) say that `r-ver`:

> - Set[s] [the Posit Public Package Manager (RStudio Package Manager, RSPM)](https://packagemanager.rstudio.com/) as default CRAN mirror. For the amd64 platform, RSPM serves compiled Linux binaries of R packages and greatly speeds up package installs.
> - Non-latest R version images installs all R packages from a fixed snapshot of CRAN mirror at a given date. This setting ensures that the same version of the R package is installed no matter when the installation is performed.

I'm trying to understand exactly when`r-ver` images switch from using RSPM latest to using a fixed snapshot. I'm using`r-ver:4.2` in a dev container at the moment, and R 4.2.2 reports `options('repos')` to be `"https://packagemanager.posit.co/cran/latest"`.

R 4.2.3 is now out as of a week ago. Does `r-ver:4.2` continue to track whatever the latest is until R 4.3 comes out (and so continues to use latest)? It doesn't look like it's moved to R 4.2.3 yet, but I also haven't deleted and re-pulled the built image in the last week.

If I specify an `r-ver` image that uses a full version tag (eg. `r-ver:4.2.2`), will that use a fixed snapshot even if that version happens to be the latest one, or would I still need to wait for a new version of R to release?

Ideally I'd like to use `r-ver` as a development container with the confidence that my R package versions won't change either (a) while I'm developing or (b) after I ship. Should I manually override the CRAN mirror to ensure that?

Thanks!

**Comment by eitsupi** [comment]
The `Rprofile.site` is only updated immediately after R installation, so if that R version was the latest when the image was built, the image will continue to use the `latest` mirror.

See this page for more information about versions details.
https://github.com/rocker-org/rocker-versioned2/wiki/Versions

> Does `r-ver:4.2` continue to track whatever the latest is until R 4.3 comes out (and so continues to use latest)?

Yes.

> It doesn't look like it's moved to R 4.2.3 yet

It has been already based on R 4.2.3
https://github.com/rocker-org/devcontainer-images/wiki/r-ver_4.2_97db99920795

> If I specify an `r-ver` image that uses a full version tag (eg. `r-ver:4.2.2`), will that use a fixed snapshot even if that version happens to be the latest one

No.

> would I still need to wait for a new version of R to release?

Yes.

> Ideally I'd like to use `r-ver` as a development container with the confidence that my R package versions won't change either (a) while I'm developing or (b) after I ship. Should I manually override the CRAN mirror to ensure that?

Yes.

There are several ways to do this other than using the `options` function.

- The `pak` package has the ability to install R packages with RSPM dates.
- The use of the `renv` package may be worth considering.

**Comment by jimjam-slam** [comment]
Thanks very much for the clarifications, @eitsupi! Is it possible for me to write something in my `devcontainer.json` like:

```json
"features": {
    "ghcr.io/rocker-org/devcontainer-features/r-packages:1": {
      "packages": "github::rstudio/renv,tidyverse,here,httpgd",
      "additionalRepositories": "https://packagemanager.posit.co/cran/2023-01-29"
  }
}
```

Would this override `https://packagemanager.posit.co/cran/latest`?

**Comment by jimjam-slam** [comment]
Or, alternatively, setting an environment variable in `devcontainer.json`?

```json
"containerEnv": {
    "PKG_CRAN_MIRROR": "https://packagemanager.posit.co/cran/2023-01-29"
}
```

**Comment by jimjam-slam** [comment]
Ahh yeah, that's definitely important—I want these containers to be runnable on both architectures.

So it seems like instead of using an `image` in my `devcontainer.json`, I'd use "build": { "dockerfile": "Dockerfile" }` to point to the Dockerfile you're describing (to download the same image and then run the script). I'd pass the checkpoint to `setup_R.sh` in the Dockerfile. And then I'd go on to use the `r-packages` feature as usual. Does that sound right?

Thanks!

**Comment by eitsupi** [comment]
Yes, your understanding is correct.
See if that works.
