### ISSUE TITLE
MRAN usage in rocker-versioned2

### ISSUE THREAD

**Issue by nbbn** [rocker-org/rocker-versioned2#62]
Hi Guys, I try to use your image from dockerHub: `rocker/r-ver`.
However, I see that from R4.0 you don't set MRAN repo as env variable in /etc/environment, and as default repo there is `CRAN="https://cran.r-project.org"`.
Can you tell me what is the reason for that?
I think setting MRAN snapshot as default repo is an good idea for reproducibility.

**Comment by behrica** [comment]
Yes, same question from me.
I think we lost a quite important feature of the "version stable" docker images,
namely that they guaranty to download always the same cran packages.

**Comment by bdcookla** [comment]
Although it may be slightly less than ideal, I've handled this situation like this:

```Dockerfile
FROM rocker/r-ver:4.0.2
ARG RSPM_CHECKPOINT=latest

RUN sed -i "s/latest/${RSPM_CHECKPOINT}/g" /usr/local/lib/R/etc/Rprofile.site
```

I look up the most recent checkpoint number and set it via `--build-arg` (e.g., `--build-arg=301`).

**Comment by briandconnelly** [comment]
☝️ to fix my example above, `--build-arg RSPM_CHECKPOINT=301`.

**Comment by cboettig** [comment]
We now set the RSPM checkpoint in the old images (currently, the 4.0.0 and 4.0.1 tags) while `latest` / 4.0.2 floats on the `latest` RSPM.  Using RSPM checkpoints essentially supersedes the previous use of MRAN. 

 Apologies we were a bit slow in getting 4.0.0 locked to a stable snapshot after 4.0.1 came out; things have been moving fast and the world has been a bit unsually crazy recently.  Let us know if anything doesn't look right still!  In principle the old rule should still hold, that for any older version, things are version stable by default!
