### ISSUE TITLE
rocker/binder not opening Rstudio in Jupyter?

### ISSUE THREAD

**Issue by giabaio** [rocker-org/rocker-versioned2#621]
Hi all --- I may be missing something obvious (or simply be slightly out of my depth), so apologies if this has a trivial explanation/solution...

But: up until a while ago (I *think* that's preceding the recent upgrade of [Jupyter to Notebook 7](https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html), I was able to build a local docker container based on `rocker/binder` and then run it through a browser opening an `Rstudio` instance, something like
```
docker run --rm -it [OTHER OPTIONS] my-container
```
For a while now, this operation fails. I can still use `mybinder` to run the container via GitHub, but the launching it locally and aiming to go on the `Rstudio` browser fails. I can point my browser to the application (typically that's `http://127.0.0.1:8888/tree`) but there's no option for me to launch `Rstudio` --- in fact, there's an option to run `R`, but it fails, giving a message like this:
![image](https://user-images.githubusercontent.com/8723145/227947902-152cb62c-8850-4a76-86cb-30b5cd2eaf84.png)

I also get a message 
```
UPDATE Read [the migration plan](https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html) to Notebook 7 to learn about the new features and the actions to take if you are using extensions - Please note that updating to Notebook 7 might break some of your extensions.
```
which links to a page that seems to suggest that Jupyter 7 will break things spectacularly... 

Like I said, it may be that I don't know enough about Jupyter and there's in fact a very easy way around it, but I wonder whether others have encountered this and/or it is in fact an impossibility to run `Rstudio` from `rocker/binder`, locally, now?

Thanks for your help!

**Comment by eitsupi** [comment]
Thank you for reporting this!
I can reproduce this.

I have checked that this problem can be worked around by using JupyterLab as described in the documentation.

```sh
docker run --rm -ti -p 8888:8888 rocker/binder sh -c "jupyter lab --ip 0.0.0.0 --no-browser"
```

https://rocker-project.org/images/versioned/binder.html

@cboettig I think we need to change the default command to JupyterLab, is there any reason to stick with JupyterNotebook?

**Comment by giabaio** [comment]
Thank you --- in the meantime, I did figure that using JupyterLab would work around the issue, as would using `rocker/rstudio`, rather than `rocker/binder` as the "engine" for this!
