### ISSUE TITLE
ENV CRAN stops installing Bioc pkg using BiocManager::install

### ISSUE THREAD

**Issue by nfancy** [rocker-org/rocker-versioned2#627]
### Container image name

rocker/rstudio:4.2.3

### What operating system are you seeing the problem on?

Linux

### System information

Docker version 20.10.11, build dea9396
Ubuntu 20.04.3 LTS

### Bug description

Hi, I am trying to build an image using docker on a local linux machine. However, when I am trying to install Bioconductor pkgs using BiocManager::install, the default repo is being replaced by the ENV var `ENV CRAN=https://packagemanager.posit.co/cran/__linux__/jammy/latest` from the base image and fails to install the pkgs. It is stuck at the last stage indefinitely. 

```
Step 5/11 : COPY ./misc/requirements-bioc.R .
 ---> 601d0cc025bb
Step 6/11 : RUN Rscript -e 'requireNamespace("BiocManager"); BiocManager::install(ask=F);' && Rscript requirements-bioc.R && rm -rf /tmp/downloaded_packages && install2.r -e -r http://cran.rstudio.com/ ClassDiscovery
 ---> Running in fe45ed5ae0cd
Loading required namespace: BiocManager
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest
Warning: unable to access index for repository https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib:
  cannot open URL 'https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib/PACKAGES'
Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.3 (2023-03-15)
Installing package(s) 'BiocVersion'

```

My question is is there any way to either 1) override the ENV var (I tried to add ENV in my docker file with a cran repo URL but it is still the same), 2) removing or bypassing this var. 

Note that I needed to add the cran repo using -r in the install2.r `-r http://cran.rstudio.com/`. But adding the URL in BiocManager::install() does not help. I added my Dockerfile and the requirements-bioc.R

Thanks.

### How to reproduce this bug?

```sh
Dockerfile

FROM rocker/rstudio:4.2.3

RUN apt-get update \
	&& apt-get install -y --no-install-recommends apt-utils \
	&& apt-get install -y --no-install-recommends \
	python3 \
	python3-setuptools \
	python3-dev \
	python3-pip \
	libcurl4-openssl-dev \
	libcairo2-dev \
	libfreetype6-dev \
	libpng-dev \
	libtiff5-dev \
	libjpeg-dev \
	libxt-dev \
	libharfbuzz-dev \
	libfribidi-dev \
	## Basic deps
	gcc \
	gdb \
	libxml2-dev \
	libz-dev \
	liblzma-dev \
	libbz2-dev \
	libgit2-dev \
	## sys deps from bioc_full
	pkg-config \
	fortran77-compiler \
	byacc \
	automake \
	curl \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* 

RUN install2.r -e -r http://cran.rstudio.com/ \
BiocManager \
&& rm -rf /tmp/downloaded_packages

## Install Bioconductor packages
COPY ./misc/requirements-bioc.R .

RUN Rscript -e 'requireNamespace("BiocManager"); BiocManager::install(ask=F);' \
&& Rscript requirements-bioc.R \
&& rm -rf /tmp/downloaded_packages 
```

requirements-bioc.R

```
bioc_pkgs<-c(
  'AnnotationDbi',
  'basilisk',
  'Biobase'
)

requireNamespace("BiocManager")
BiocManager::install(bioc_pkgs, ask=F)

```
```

**Comment by cboettig** [comment]
Thanks, looks like this might be  a temporary network error?  The error message says it cannot resolve the package list at https://packagemanager.posit.co/cran/__linux__/jammy/latest/src/contrib/PACKAGES .  It resolves for me at present, can you confirm it is reachable from your machine, and is not blocked by a local firewall or such?

**Comment by eitsupi** [comment]
> My question is is there any way to either 1) override the ENV var (I tried to add ENV in my docker file with a cran repo URL but it is still the same), 2) removing or bypassing this var.

Please check the document.
https://rocker-project.org/images/versioned/r-ver.html#switch-the-default-cran-mirror

```dockerfile
FROM rocker/r-ver:4
RUN echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >>"${R_HOME}/etc/Rprofile.site"
```

**Comment by nfancy** [comment]
Thanks a lot. This trick worked.
