### ISSUE TITLE
RStudio preferences

### ISSUE THREAD

**Issue by danwwilson** [rocker-org/rocker-versioned2#63]
With the RStudio 1.3.x being released and making use of the `rstudio-prefs.json` file, it may be necessary to adjust how the rstudio script handles reproducibility.

I've recently built a container (taking the lead from your amazing work) and experienced some issues when making use of the new `json` file setup for preferences.

The issue comes from this piece of code in the `install-studio.sh` script 

```
## Rocker's default RStudio settings, for better reproducibility
mkdir -p /home/rstudio/.rstudio/monitored/user-settings \
  && echo 'alwaysSaveHistory="0" \
          \nloadRData="0" \
          \nsaveAction="0"' \
          > /home/rstudio/.rstudio/monitored/user-settings/user-settings \
  && chown -R rstudio:rstudio /home/rstudio/.rstudio
```
It seems these settings cause conflict when a `json` settings file is present. I was experiencing the case that the settings that would load in the container would be set to save history, set to ask about saving RData and set to load RData.

When I removed the above mentioned code in favour of just the `json` file, the preferences I'd set in the file worked.

**Comment by cboettig** [comment]
Thanks, agreed!  PR welcome on this, or @noamross @RobJY might get to this one before I do?
