### ISSUE TITLE
New rocker:shiny image issue

### ISSUE THREAD

**Issue by therealtjb** [rocker-org/rocker-versioned2#640]
Seems like i am having an issue with newest version of rocker:shiny when building an image

Warning: Error in library: there is no package called 'tidyverse'

Same docker file was able to build an image earlier in week and now struggling. Reading online - seems like this is an issue that occurs at times with new version becomes available on rocker

**Comment by eitsupi** [comment]
Hi, can you provide complete information according to the issue template?
(You may close this issue and create a new one in this repository)

I don't know what you see as the problem as there is no tidyverse package installed in `rocker/shiny`.
