### ISSUE TITLE
Could not connect to RSession - Unable to connect to Service(1) on ubuntu18.0.4

### ISSUE THREAD

**Issue by guoyuh** [rocker-org/rocker-versioned2#659]
### Container image name

rocker/rstudio:4.1.0

### Container image digest

rocker/rstudio:4.1.0@sha256:27f4994c5502ce93bd76d4eaec1b8d333ef4182e64493929468452d17b963d35

### What operating system related to this question?

Linux

### System information

Docker version:
       Version:           20.10.14

### Question

i run a container like folow:
![image](https://github.com/rocker-org/rocker-versioned2/assets/35966205/1ff177a3-4807-4512-955c-72171818a4cb)

then，Log in to RStudio in the browser and I get ：
![image](https://github.com/rocker-org/rocker-versioned2/assets/35966205/5b2ff207-2a21-430c-8938-7c0fc6a7e950)

I haven't been able to log in to RStudio so far. How can I resolve this issue

**Comment by benz0li** [comment]
> It is not recommended to bind-mount whole home directory on the container (`/home/rstudio`); RStudio Server may not work properly.

See https://rocker-project.org/images/versioned/rstudio.html#editing-work-on-rstudio-server

**Comment by eitsupi** [comment]
@benz0li Thanks for answering this!
