### ISSUE TITLE
where is rocker/binder:4.0.1 ?

### ISSUE THREAD

**Issue by julou** [rocker-org/rocker-versioned2#67]
Hello, I'm trying to get started with binder for R projects which use `renv`.
Since I'm doing a dry run, I went for a recent version of R, namely 4.0.1. Unfortunately, I can't find the corresponding image (I now realise that 4.0.0 and 4.0.2 images do exist, so maybe I'm simply cursed ;)
Thank you in advance for your guidance.

**Comment by julou** [comment]
In addition there is a bug with rocker/binder:4.0.x images, cf https://github.com/jupyterhub/jupyter-rsession-proxy/issues/92

**Comment by julou** [comment]
it doesn't seem that this bug report (jupyterhub/jupyter-rsession-proxy#92) rose a lot of attention 😅
I'm not even sure where this should be posted at best, and can imagined that this is already fixed but not deployed yet on dockerhub.
Help in getting a working instance of R-4.0 using Binder would be greatly appreciated (in particular @cboettig it seems that you deployed these versions). Thank you in advance.

**Comment by cboettig** [comment]
should be there now.
