### ISSUE TITLE
Setup conda

### ISSUE THREAD

**Issue by royfrancis** [rocker-org/rocker-versioned2#674]
Is there a ready solution to include conda in any of the images? Just wanted to make sure I didn't miss it. Thinking of the most lightweight option with multithreading: [mambaforge](https://github.com/conda-forge/miniforge) and an installer script perhaps based on [this](https://github.com/conda-forge/miniforge-images/blob/master/ubuntu/Dockerfile).

**Comment by eitsupi** [comment]
Here is a script for the Dev Container Feature.
If you copy and exec this, it should work.
https://github.com/rocker-org/devcontainer-features/blob/54829966edca06bd81e58a38ad28b57a993fd6e5/src/miniforge/install.sh

**Comment by royfrancis** [comment]
Perfect! Exactly what I was looking for. Thanks! Will this be included in `rocker_scripts/` in future?

**Comment by eitsupi** [comment]
> Perfect! Exactly what I was looking for. Thanks! Will this be included in `rocker_scripts/` in future?

No, rocker_scripts is only for use within this repository, but I believe the Dev Container Features can be used in a broader use case.
So I don't think we dare to bring it here.
