### ISSUE TITLE
Debugging c++ code within R does not work with rocker/r-ver:devel

### ISSUE THREAD

**Issue by senbaikang** [rocker-org/rocker-versioned2#680]
### Container image name

rocker/r-ver:devel, rocker/rstudio:devel

### What operating system are you seeing the problem on?

Linux

### System information

- singularity version 3.8.5

### Bug description

I am trying to debug some c++ code within R using `$R_HOME/bin/exec/R`. Whenever I use image `rocker/r-ver:devel` or `rocker/rstudio:devel`, I encounter this error:
```
error while loading shared libraries: libR.so: cannot open shared object file: No such file or directory
```
but I can see that `libR.so` is present in `$R_HOME/lib`.

However, if I use image `rocker/r-devel`, I can run `$R_HOME/bin/exec/R` without errors.

**Comment by senbaikang** [comment]
Hi Dirk, thank you for your reply.

By the way, Is there an image of rstudio built upon `rocker/r-devel` by any chance?

**Comment by eitsupi** [comment]
This issue may related to Singularity?

**Comment by senbaikang** [comment]
I indeed built a singularity image from the docker image, but I am not sure if it is caused by singularity. Anyway, I solved it eventally by installing r-dev directly using `apt`. Thank you for following up!

**Comment by eddelbuettel** [comment]
I think we can close this.
