### ISSUE TITLE
rstudio:4.0.2-ubuntu18.04 ?

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker-versioned2#69]
Hi @cboettig 

Is the rstudio:4.0.2 - ubuntu18.04 image going to be made available? I can't seem to find it in the stack of Dockerfiles.

Best,

Nitesh

**Comment by eddelbuettel** [comment]
Can you migrate the BioC stack to 20.04 which, as you know, is the current LTS?

**Comment by nturaga** [comment]
Hi @eddelbuettel The bioconductor build system is currently on 18.04 and it would require significant effort to migrate our build system to 20.04 at the moment. This is the reason we chose to use 18.04 in the first place so that there is more symmetry between the bioconductor_docker image and the bioconductor build system.
