### ISSUE TITLE
Rstudio server crash - potential memory issues

### ISSUE THREAD

**Issue by k3yavi** [rocker-org/rocker-versioned2#702]
Hi team,

First of all, thank you for this fantastic tool; it has been a tremendous resource to run Rstudio on my Mac Studio w/ M2 chip (128G RAM). Unfortunately, the R studio session crashes as soon as the memory requirements of the session go around 4-5 Gigs, even though I have exposed around 100G to the docker container. This is not a R package-specific issue as I have replicated this across multiple R packages. Is there a specific rocker/docker configuration that I still need to include?

This is my current Docker configs:
```
FROM rocker/rstudio:4.3.0

WORKDIR /Volumes/Analyses/

RUN apt-get clean all && \
        apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y \
                libhdf5-dev \
                libcurl4-gnutls-dev \
                libssl-dev \
                libfontconfig1-dev \
                libharfbuzz-dev \
                libfribidi-dev \
                libfreetype6-dev \
                libtiff5-dev \
                libjpeg-dev \
                libxml2-dev \
                libpng-dev \
                libxt-dev \
                zlib1g-dev \
                libbz2-dev \
                liblzma-dev \
                libglpk40 \
                libgit2-dev \
                libudunits2-dev \
                libcairo2-dev \
                libgdal-dev \
                libmagick++-dev \
                cmake \
                patch \
        && apt-get clean all && \
        apt-get purge && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --chown=rstudio:rstudio rstudio/rstudio-prefs.json /home/rstudio/.config/rstudio
COPY --chown=rstudio:rstudio rstudio/.Rprofile /home/rstudio/
```

* Issue Template

- Container image name: 
rocker/rstudio:4.3.0

- What operating system are you seeing the problem on?
McOS

- System information
Docker version 24.0.5, build ced0996
McOS 13.5 (22G74)

- Bug Description
the R studio session crashes as soon as the memory requirements of the session go around 4-5 Gigs, even though I have exposed around 100G to the docker container. This is not a R package-specific issue as I have replicated this across multiple R packages. Is there a specific rocker/docker configuration that I still need to include?

**Comment by eitsupi** [comment]
Please fill the issue template.

And I wonder you use the arm64 platform image.

**Comment by cboettig** [comment]
also on Mac, Docker runs in a VM that limits the available RAM (or at least it used to), see https://stackoverflow.com/a/44533437/258662.

**Comment by k3yavi** [comment]
Hi @eitsupi , I've updated the issue with the information mentioned in the template.

@cboettig thanks a lot, that fixes it.
