### ISSUE TITLE
Error saving RScript File: No such file or directory

### ISSUE THREAD

**Issue by cr2007** [rocker-org/rocker-versioned2#705]
### Container image name

rocker/rstudio

### Container image digest

rocker/rstudio@sha256:edc52f831222113d727635e84c1d5467dfd5ccb9451b212152e845a50b536553

### What operating system are you seeing the problem on?

Windows

### System information

Docker Desktop running on Windows, using Dev Containers in VS Code.

### Bug description

When I try to save the RScript file after creating and adding values, I get this error:

![image](https://github.com/rocker-org/rocker-versioned2/assets/73425927/a097abd3-8cad-4f91-a6eb-7aefa27a0377)

I am not sure why I am unable to save the file, or any other changes made to it.
It's not even appearing in the file list.

### How to reproduce this bug?

```sh
1. Create a new RScript file
2. Run commands
3. Ctrl + S (or click the GUI Buttons to save)
4. Give the file a name
5. Error appears
```

**Comment by eitsupi** [comment]
> Docker Desktop running on Windows, using Dev Containers in VS Code.

What does this mean? How are you starting RStudio Server?

I recommend checking <https://github.com/rocker-org/devcontainer-templates/tree/main/src/r-ver>.

**Comment by cr2007** [comment]
I setup the container via VS Code

And then start the server by running `/init` in the terminal
Once done, I open the server in [`localhost:8787`](http://localhost:8787) and run it all

I did have a look at that, will check it out now that you suggested.

**Comment by eitsupi** [comment]
> I setup the container via VS Code

Please upload the configuration files.

**Comment by eitsupi** [comment]
One thing that came to mind is whether you are working on a Linux file system (WSL2).

Various problems occur when bind mounting a Windows file system.

**Comment by cr2007** [comment]
I'm not sure about the details

I basically do the basic Dockerfile setup with a `devcontainer.json`
And then use the Dev Containers VS Code extension to rebuild the container.

I am using Docker Desktop, with a WSL2 backend

**Comment by eitsupi** [comment]
I see.
Don't use it that way, please use the rstudio-server Dev Container Feature instead.

**Comment by cr2007** [comment]
Currently, this is how I've set it up

```dockerfile
# .devcontainer/Dockerfile

FROM ghcr.io/rocker-org/devcontainer/r-ver:4

# COPY #/workspaces/Lab1 /home/rstudio/workspace

# Set loging password (course code)
ENV PASSWORD=f20sa

# CMD [ "/init" ]
```

And the devcontainer.json
```json
// .devcontainer/devcontainer.json\

{
    "name": "R Container",      // Name of the container
    "dockerFile": "Dockerfile", // Directs to the Dockerfile in the same directory
    "customizations": {
        "vscode": {
            // Installs the R extension and other extensions
            "extensions": [
                "REditorSupport.r",
                "eamodio.gitlens",
                "mhutchie.git-graph",
                "analytic-signal.preview-pdf"
                // "tomoki1207.pdf"
            ]
        }
    },
    // Adds the r-apt feature to the container
    "features": {
        "ghcr.io/rocker-org/devcontainer-features/r-apt:0": {},
        "ghcr.io/rocker-org/devcontainer-features/rstudio-server:0": {}
    },
    "forwardPorts": [8787],
    "portsAttributes": {
        "8787": {
            "label": "RStudio IDE"
        }
    },
    "containerEnv": {
        "PASSWORD": "f20sa"
    },
    // Copies all the data files to the RStudio directory
    "postStartCommand": "cp -r ./* /home/rstudio/"
}
```

Is there any changes in the configurations you suggest?

**Comment by cr2007** [comment]
[like]  Ramaprasad, CSK reacted to your message:
________________________________

**Comment by eitsupi** [comment]
I don't think I can comment because I don't know what you meant by the part you added.
I recommend not adding anything to the examples in the README.

Also, I think the topic is off-topic, so if you have any problems, please check the relevant repositories.
