### ISSUE TITLE
ERROR: R_HOME ('/usr/local/lib/R') not found

### ISSUE THREAD

**Issue by Liripo** [rocker-org/rocker-versioned2#710]
### Container image name

rocker/tidyverse:latest

### Container image digest

rocker/tidyverse@sha256:097f6efb4a4a9aa802ded64bdd427ffed00aee42d32f596716ad303eb8484010

### System information

- podman version 2.2.1
- CentOS Linux release 7.9.2009 (Core)

### Question

Hello:
![image](https://github.com/rocker-org/rocker-versioned2/assets/54770415/c1663071-8a60-4f2a-891a-54fb42ce8593)

I has an error using podman.

**Comment by eitsupi** [comment]
Interesting, how about

- Using the `rstudio` user (with something like `podman run --user rstudio`)?
- Using `rocker/r-ver` instead of `rocker/tidyverse`?

**Comment by Liripo** [comment]
![image](https://github.com/rocker-org/rocker-versioned2/assets/54770415/8289b404-b26a-4ed5-9be3-c2053237af00)
![image](https://github.com/rocker-org/rocker-versioned2/assets/54770415/d0db15b8-09dc-42e3-ad12-49634c0fe4cf)
still the same.

**Comment by eitsupi** [comment]
Could you check `ls -la /usr/local/lib` on bash?

**Comment by Liripo** [comment]
![image](https://github.com/rocker-org/rocker-versioned2/assets/54770415/30237407-be52-417e-8dba-445c8eddeb82)

**Comment by Liripo** [comment]
I can use it in windowns 11 (wsl2). 
![image](https://github.com/rocker-org/rocker-versioned2/assets/54770415/b8cb985c-1e97-4160-bf6f-d659180970a3)

**Comment by eitsupi** [comment]
Thanks.
Maybe it's a bug of podman?
I don't understand what's going on...

**Comment by guchenbo** [comment]
<img width="341" alt="image" src="https://github.com/rocker-org/rocker-versioned2/assets/5044026/e8a5c8df-964b-4f91-8132-3e8044ba033d">
shell -x connot work on ubuntu:jammy but ok on ubuntu:focal
