### ISSUE TITLE
Ubuntu 4.0.2 image?

### ISSUE THREAD

**Issue by reisner** [rocker-org/rocker-versioned2#72]
Is it possible to get the ubuntu 4.0.0 R image (4.0.0-ubuntu18.04 upgraded to 4.0.2? In particular, Rcpp doesnt play nice with 4.0.0 (more info here https://github.com/RcppCore/Rcpp/issues/1105 )

**Comment by eddelbuettel** [comment]
That is actually misinformation as you can tell from a) looking the Rcpp check page at CRAN, or b) the mailing list or here.  I just closed #1105.

We also just answered everything about 18.02 _yesterday_ in this thread:  #69 and #70.  It would be nice if folks tried just a little harder to search.  See the discussion there for a working "proof" of 4.0.2, 18.04 and Rcpp (even in the context of RSPM).

**Comment by reisner** [comment]
@eddelbuettel Why is this misinformation? You said yourself that R needs to be > v4.0.0 and i'm merely asking for what you suggested.

**Comment by eddelbuettel** [comment]
Sorry, I stand corrected.  Rcpp will not play nicely with R 4.0.0 for no fault of Rcpp's.  (Coming off the seminar I rushed but then again you didn't help opening multiple issue and missing #69 and #70 here.  So we both could have done one better.  Call it even.)  Next time will be perfect...
