### ISSUE TITLE
Improving the understanding of dependencies

### ISSUE THREAD

**Issue by SamGG** [rocker-org/rocker-versioned2#726]
### What operating system related to this question?

Linux

### Question

Hi,
Thanks for your work in easing the use of the R environment.

As a noob, I don't understand all the dependencies in this repo, especially the naming, but I think I found my way. Nevertheles, I think it could be helpful to have such a summary:

- shiny-verse = shiny + tidyverse = (r+shiny) + tidyverse

- tidyverse = rstudio + tidyverse = (r+rstudio+pandoc+quarto) + tidyverse

- verse = ...

In the end, quarto requires an explicit installation for use in shiny or shiny-verse, IIUC, what I am going to test.

Best.

**Comment by cboettig** [comment]
we could do better on this!  

There's a table to this effect on the project website: https://rocker-project.org/images/#the-versioned-stack

Initially the stack was purely linear: r-ver, rstudio, tidyverse, verse, geospatial.  

(traditionally, 'verse' meant additional publishing-related things on tidyverse, largely latex/rmarkdown related, but has always served as a bit of a catch-all for 'extras' without a clear home.  other names are more intuitive).  

We've made the stack more modular, allowing users to re-mix docker containers with any of these building blocks as defined by https://github.com/rocker-org/rocker-versioned2/tree/master/scripts, and we use this mechanism to make other flavors, including the `cuda`/`ml`/`ml-verse` stack and the `shiny` / `shiny-verse` stack (where the 'verse' prefix is used somewhat loosely there, see Dockerfiles for details).  

We're an entirely community-driven, community-maintained project, PRs on the website or README or other docs locations are more than welcome!!

**Comment by SamGG** [comment]
Thanks for your feedback and the links.
I finally ended up with adding quarto installation to the shiny verse image, which works smoothly for our goal.
Those scripts are really great as they permit a fine customization.

**Comment by SamGG** [comment]
> There's a table to this effect on the project website: https://rocker-project.org/images/#the-versioned-stack

This is definitively what I was looking for. I will try to understand why I didn't reach it while browsing through the website.
