### ISSUE TITLE
fix error in install_verse.sh

### ISSUE THREAD

**Issue by ykopylov** [rocker-org/rocker-versioned2#73]
Hi, recently I found simple misprint in **install_verse.sh** file on the line 55:
`        && ap-get remove -y systemd` ---->>> '        && apt-get remove -y systemd'

**Comment by eddelbuettel** [comment]
Correct, link is 

https://github.com/rocker-org/rocker-versioned2/blob/02a64959b61ce78e96680d0044b2ce51683da7dd/scripts/install_verse.sh#L55

Thanks for catching.  @cboettig or @noamross will surely fix shortly!

**Comment by ykopylov** [comment]
Thank you!

**Comment by eddelbuettel** [comment]
Don't close it is not yet fixed!
