### ISSUE TITLE
openssh-client is missing to Create SSH Keys in RStudio

### ISSUE THREAD

**Issue by ulf1** [rocker-org/rocker-versioned2#732]

**Comment by eitsupi** [comment]
Could you elaborate on the issue? I assume you can install `openssh-client` yourself, is this a problem?

**Comment by ulf1** [comment]
> Could you elaborate on the issue? I assume you can install `openssh-client` yourself, is this a problem?

That was the issue. Thanks

**Comment by eitsupi** [comment]
Happy to hear that. Closing.
