### ISSUE TITLE
Rstudio server support

### ISSUE THREAD

**Issue by jvanlunenburg** [rocker-org/rocker-versioned2#74]
Hello,

edit: nevermind, I just noticed this is an rstudio server image. Strange that the readme doesn't mention it.

Would you recommend using a Rocker image to build an Rstudio Server image? Or is there an existing repository you'd recommend?  

Thank you

**Comment by cboettig** [comment]
Yes, `rocker/rstudio` provides RStudio (server).  Rocker's r-ver stack has always included RStudio in images after `r-ver`.  Apologies if the README is unclear.
