### ISSUE TITLE
Feature Request: Add a NoLD container + Rstudio

### ISSUE THREAD

**Issue by vnijs** [rocker-org/rocker-versioned2#76]
I am (hopefully) finishing up some NoLD issues that CRAN identified that I believe originated in XGBoost (https://github.com/dmlc/xgboost/issues/5935). Testing was a bit of a pain so I ended up creating my own image for testing (link below). This image is a lot larger than needed for most users I would expect so something based on Rocker with Rstudio server would be much easier to work with.

https://github.com/vnijs/NoLD
https://hub.docker.com/r/rhub/debian-gcc-devel-nold/dockerfile

**Comment by eitsupi** [comment]
https://github.com/r-hub/rhub-linux-builders may help you.
