### ISSUE TITLE
install_julia.sh doesn't install the latest version of Julia

### ISSUE THREAD

**Issue by Hua-Zhou** [rocker-org/rocker-versioned2#763]
This potential bug doesn't affect pre-built images. It only affects users who want to call the script `install_julia.sh` to install the latest version of Julia in the Docker image.

If a user doesn't specify the environment variable `JULIA_VERSION`, the current script `install_julia.sh` will always install Julia v1.9.4, even though the latest stable version of Julia is 1.10.1 now. 

Changing this [line](https://github.com/rocker-org/rocker-versioned2/blob/7a2a65a498c2bdac90192c7c081fbfd7f86e775a/scripts/install_julia.sh#L40)
`latest_version <- sort(versions[is_stable], decreasing = TRUE)[1]`
to
`latest_version <- as.character(sort(numeric_version(versions[is_stable]), decreasing = TRUE)[1])`
should fix the issue.

**Comment by eitsupi** [comment]
Thanks for the report. Would you be interested in submitting a pull request?

I think this script should ideally be rewritten to use juliaup, but haven't worked on that because I was wondering if there is a user need.

**Comment by Hua-Zhou** [comment]
+1 for "juliaup"-ify the script. My use case: I teach courses in a biostatistics department in different languages: R, Python, and Julia. It'll be nice to have an image with the full JUPYTER (Julia+Python+R) stack. I used to build from the [math-server-docker](https://github.com/felipenoris/math-server-docker), but that's CentOS-based and the build process is unbearably long.
