### ISSUE TITLE
R session crashes when reach certain ram 

### ISSUE THREAD

**Issue by Flu09** [rocker-org/rocker-versioned2#769]
Hello,   I am using slurm to launch rocker-studio and it crashes when it reaches 500GB although I have a lot of memory allocated for the server. is there a limit ?, if yes, how to modify it? i am pulling an image as I have no knowledge to build one. If i need to modify the limit how to do that?

**Comment by eitsupi** [comment]
I'm sorry but it's not clear to me how your question relates to this project, I think questions about RStudio Server can be asked there <https://community.rstudio.com/>.

**Comment by eddelbuettel** [comment]
Also note that the operating system kernel may imposed constraints, as do the launching shells (and see `man ulimit` for setting values to influence this).  Lastly, as a former `slurm` user, you may also need to look into what each process launched is allowed in terms of resources.  The last two letters of `slurm` stand for **r**esource **m**anager. One of these is what you are likely up against.

**Comment by Flu09** [comment]
thank you
