### ISSUE TITLE
RStudio Image on version 4.0.0 doesn't work until 3.6.3 is pulled and run in a container.

### ISSUE THREAD

**Issue by kevwkli** [rocker-org/rocker-versioned2#77]
Hey,

I ran into an issue where I was working with a fresh copy of rocker/tidyverse:4.0.0 and it failed to start, and it would just show the loading screen (with options to restart/quit), but it would never load the app. When we pulled rocker/tidyverse:3.6.3 and ran it, then tried to run rocker/tidyverse:4.0.0 it suddenly worked.

I'm working in an environment where we will need to pull fresh frequently, and I would prefer to not need to pull an older version of the image before it works.

docker version: 19.03.12

**Comment by cboettig** [comment]
It's possible you are running up against #78 ?  You haven't given us much information about what you are doing so it is hard to diagnose your issue. re-open with more details here if necessary.
