### ISSUE TITLE
AGPL (fst) in verse images

### ISSUE THREAD

**Issue by stephenturner** [rocker-org/rocker-versioned2#770]
### Container image name

rocker/tidyverse:4.3.2

### Container image digest

rocker/tidyverse@sha256:7ca07187e0ab554e31e1172c5cda7e4989effe9d565391f94dc7bfae78217312

### System information

- Docker version 4.27.2 (137060)
- MacOS 14.3

### Question

Hello. I'm using tidyverse, shiny-verse, verse, etc., as base images, and a fossa scan pointed out that I have an AGPL dependency. Looks like the culprit is fst (https://cran.r-project.org/web/packages/fst/LICENSE).

```
docker run --rm rocker/tidyverse:4.3.2 Rscript -e 'pkgs<-installed.packages();agpli<-rownames(pkgs)|>sapply(packageDescription, fields="License")|>grep("AGPL", x=_);pkgs[agpli]'
[1] "fst"
```

I'm not sure which of the packages in the tidyverse install script this is coming from. I don't think it's pulled in with just installing tidyverse.

**Comment by eddelbuettel** [comment]
I do not think the Rocker Project makes any assurances about licenses besides using properly vetted Open Source software as admitted to CRAN.

Coming here and stating AGPL is bad is also ... a bit weird.  Are you aware what license RStudio (the IDE) is under ?

**Comment by stephenturner** [comment]
Fair point. Thanks for the quick response.

**Comment by eddelbuettel** [comment]
Also out of curiousity where/why do you run 'fossa scan' (a TIL for me) given that "we all know" CRAN is quite diligent about that?

(There is these three fields in what `tools::CRAN_package_db()` returns too:

```r
> colnames(db)[9:11]
[1] "License"               "License_is_FOSS"       "License_restricts_use"
> 
```

and for what it is worth CRAN see this as unrestricted:

```r
> db[ db[,"Package"] == "fst", 9:11]
                   License License_is_FOSS License_restricts_use
6184 AGPL-3 | file LICENSE            <NA>                  <NA>
> 
```

ie no different than to pick, say, `dplyr`:

```r
> db[ db[,"Package"] == "dplyr", 9:11]
                License License_is_FOSS License_restricts_use
4363 MIT + file LICENSE            <NA>                  <NA>
> 
```

All that said we are no lawyers.  You are quite to check if _your usage_ imposes any restrictions on what _you_ can do.  We only give free software and our labor integrating it away for free to you.

**Comment by eitsupi** [comment]
> I'm not sure which of the packages in the tidyverse install script this is coming from. I don't think it's pulled in with just installing tidyverse.

For me, it's clear if searching in GitHub.

https://github.com/rocker-org/rocker-versioned2/blob/2db571dc64e401936ee14f64e454eaaba4f3d16f/scripts/install_tidyverse.sh#L57
