### ISSUE TITLE
cannot produce pdf from Rmd file

### ISSUE THREAD

**Issue by gpasa** [rocker-org/rocker-versioned2#772]
### Container image name

rocker/verse:latest

### Container image digest

[     {         "Id": "sha256:fd553ed661adf4c274d8dc351f3c44c99ff900d39328f0a2092b2a34be98238e",         "RepoTags": [             "rocker/verse:latest"         ],         "RepoDigests": [             "rocker/verse@sha256:a49bbc458bd9e5ddcf90d08501af73406592e72c895e0894767f8a45c8acd42d"         ],         "Parent": "",         "Comment": "buildkit.dockerfile.v0",         "Created": "2024-03-13T13:59:25.910938395Z",         "Container": "",         "ContainerConfig": {             "Hostname": "",             "Domainname": "",             "User": "",             "AttachStdin": false,             "AttachStdout": false,             "AttachStderr": false,             "Tty": false,             "OpenStdin": false,             "StdinOnce": false,             "Env": null,             "Cmd": null,             "Image": "",             "Volumes": null,             "WorkingDir": "",             "Entrypoint": null,             "OnBuild": null,             "Labels": null         },         "DockerVersion": "",         "Author": "",         "Config": {             "Hostname": "",             "Domainname": "",             "User": "",             "AttachStdin": false,             "AttachStdout": false,             "AttachStderr": false,             "ExposedPorts": {                 "8787/tcp": {}             },             "Tty": false,             "OpenStdin": false,             "StdinOnce": false,             "Env": [                 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/bin/linux",                 "R_VERSION=4.3.3",                 "R_HOME=/usr/local/lib/R",                 "TZ=Etc/UTC",                 "CRAN=https://p3m.dev/cran/__linux__/jammy/latest",                 "LANG=en_US.UTF-8",                 "S6_VERSION=v2.1.0.2",                 "RSTUDIO_VERSION=2023.12.0+369",                 "DEFAULT_USER=rstudio",                 "PANDOC_VERSION=default",                 "QUARTO_VERSION=default",                 "CTAN_REPO=https://mirror.ctan.org/systems/texlive/tlnet"             ],             "Cmd": [                 "/init"             ],             "ArgsEscaped": true,             "Image": "",             "Volumes": null,             "WorkingDir": "",             "Entrypoint": null,             "OnBuild": null,             "Labels": {                 "org.opencontainers.image.authors": "Carl Boettiger <cboettig@ropensci.org>",                 "org.opencontainers.image.base.name": "docker.io/rocker/tidyverse:4.3.3",                 "org.opencontainers.image.description": "Adds tex & related publishing packages to version-locked tidyverse image.",                 "org.opencontainers.image.licenses": "GPL-2.0-or-later",                 "org.opencontainers.image.ref.name": "ubuntu",                 "org.opencontainers.image.revision": "04a01090f57c1bab45ac9201ee69f2596f217db2",                 "org.opencontainers.image.source": "https://github.com/rocker-org/rocker-versioned2",                 "org.opencontainers.image.title": "rocker/verse",                 "org.opencontainers.image.vendor": "Rocker Project",                 "org.opencontainers.image.version": "R-4.3.3"             }         },         "Architecture": "amd64",         "Os": "linux",         "Size": 3574833305,         "GraphDriver": {             "Data": {                 "LowerDir": "/var/lib/docker/overlay2/77fdb631e00570b1a36650994258fc146121aad059c771c9dda7d20a963cfb8c/diff:/var/lib/docker/overlay2/246e45c03fbfb1118cc10037b59275dab585ca7d99f40c1a9d44afb6735e1e49/diff:/var/lib/docker/overlay2/84c0960f95c96627198322b950bbce50505d8fe96945978f600b0deca3b3cfbe/diff:/var/lib/docker/overlay2/c9ef987652d43700f9af49d935f31dd5d2c60e8a1eb2d5c89c639e429f1410d2/diff:/var/lib/docker/overlay2/dab555387d70c21eb1a29fdffdff01ff43bc3c1b3841683dd75b2e479c024212/diff:/var/lib/docker/overlay2/7f2b47b3c4bf43d886397035d66b30b080bb61ae7b6b6dcebc27160c43c433f4/diff:/var/lib/docker/overlay2/02dbeb143e9d86b8f927e33abb74cff67a0ff6c0d0a454a8867c5a6e1fcced27/diff:/var/lib/docker/overlay2/3caf7255d0972104e0bc5a227255e10004f4357f13373dcfc351f11c3fa7925b/diff:/var/lib/docker/overlay2/25289e2a9abe11b778901f3bdfb92afb5284793b215070a7648dcc6b8a2fddea/diff",                 "MergedDir": "/var/lib/docker/overlay2/e3817f91fa9bf2fb0bc7eaed9e838b688026c477d284e56c60b806190918d74e/merged",                 "UpperDir": "/var/lib/docker/overlay2/e3817f91fa9bf2fb0bc7eaed9e838b688026c477d284e56c60b806190918d74e/diff",                 "WorkDir": "/var/lib/docker/overlay2/e3817f91fa9bf2fb0bc7eaed9e838b688026c477d284e56c60b806190918d74e/work"             },             "Name": "overlay2"         },         "RootFS": {             "Type": "layers",             "Layers": [                 "sha256:5498e8c22f6996f25ef193ee58617d5b37e2a96decf22e72de13c3b34e147591",                 "sha256:a7925f4ea9e1d4ae8f7bb68342e1870d73ca40ddd32ebd113f87e9aa435d4c51",                 "sha256:8f5a87f20131903ebbfe6f2037f836146f713d3dc68dcb3243d1fa88b61282d8",                 "sha256:321837ce5aec04627e7366d7d5504672c4c9db204d5dabdcd1cd26148c0ae0ce",                 "sha256:07117bdb5a5c4bc185d4a90e67f71ab5344cd5a5ce0d51fefb0c18b62b438708",                 "sha256:c86449ee7105dcda6e39072961b5c3add4222d71994c5972b2986540fa3b748e",                 "sha256:6500fbfb7b1c3f565350d4f96554fed9c6be253b5450788a5aa379e29e95b0cf",                 "sha256:16d63f9d3f6365d86a82ea072fb349390af8c3dfb96b41ebcf6ce8b676046a98",                 "sha256:ba9120e4c1488d66802c203ef2f4a2d06cb90546c41a9417e2403cba4a1808be",                 "sha256:1dd3605ff7d34cdb32d7695163ef8ef4062670c65164c93b8a23fd8642d6b5fe"             ]         },         "Metadata": {             "LastTagTime": "0001-01-01T00:00:00Z"         }     } ]

### What operating system are you seeing the problem on?

macOS

### Bug description

While producing a pdf from an Rmd using knitr I get the following error

tlmgr: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
! LaTeX Error: File `booktabs.sty' not found.

! Emergency stop.
<read *> 

Error: LaTeX failed to compile learning.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See learning.log for more info.
In addition: Warning message:
In system2("tlmgr", args, ...) :
  running command ''tlmgr' search --file --global '/booktabs.sty'' had status 1
Execution halted

### How to reproduce this bug?

```sh
inside Rstudio try to generate a pdf with tables (I guess)
```

**Comment by eitsupi** [comment]
Please pull the latest image.
