### ISSUE TITLE
highlight breaking changes from r-ver:4.2.2 where OS is now running on ubuntu 22.04

### ISSUE THREAD

**Issue by PaulinCharliquart** [rocker-org/rocker-versioned2#774]
### Container image name

rocker

### Question

hi,

First thanks for this useful project :)

Can we highlight in the doc, the breaking change from `r-ver:4.2.2`  where OS is now running on ubuntu 22.04 ?

thanks
Paulin

**Comment by eitsupi** [comment]
I believe that the README and other documents are sufficiently documented about the base image.
Also, the actual version can be found here.
https://github.com/rocker-org/rocker-versioned2/wiki/Versions

**Comment by PaulinCharliquart** [comment]
Yes you are right. Wiki has enough info.
Thanks!

**Comment by PaulinCharliquart** [comment]
Yes you are right. Wiki has enough info.
Thanks!
