### ISSUE TITLE
rstudio: mounting read-only directory

### ISSUE THREAD

**Issue by nick-youngblut** [rocker-org/rocker-versioned2#777]
### Container image name

rocker/rstudio:4.3.1

### What operating system related to this question?

Linux

### System information

- Docker version 24.0.6, build ed223bc
- Ubuntu 22.04.3

### Question

I would like to mount my working directory and also a NAS directory mounted on the VM that I'm using (`/mnt/NAS/`). 

My docker run command:

```bash
docker run -d --rm -it \
  -e PASSWORD="${PASSWORD}" \
  -e ROOT=true \
  -p 9801:8787 \
  -e USERID=$(id -u) \
  -e GROUPID=$(id -g) \
  -v `pwd`:/home/rstudio/workspace \
  -v /mnt/NAS/LabDevices/NGS-210-21:/home/rstudio/NGS-210-21 \
  rocker/rstudio:4.3.1
```

When I include `-v /mnt/NAS/LabDevices/NGS-210-21:/home/rstudio/NGS-210-21`, the `init` command seems to fail (but no error message written to the console), and I cannot access the Rstudio login screen; however, I can access the login if that NAS mount point is not included. 

I can mount `/mnt/NAS/LabDevices/NGS-210-21` for other docker containers, so this appears specific to the setup of `init` in `rocker/rstudio:4.3.1`. I don't see any docs on dealing with mounting read-only directories `rocker/rstudio`. 

Any ideas on what the problem is?

**Comment by eitsupi** [comment]
Maybe <https://rocker-project.org/images/versioned/rstudio.html#userid-and-groupid>?

> The UID and GID of the default non-root user can be changed as follows:
> 
> ```sh
> docker run --rm -ti -e USERID=1001 -e GROUPID=1001 -p 8787:8787 rocker/rstudio
> ```
>
> Warning
> If these are set, ownership of the /home/rstudio directory in the container is updated by the root user. This will also overwrite the ownership of any files that are bind-mounted under the /home/rstudio directory.

**Comment by nick-youngblut** [comment]
@eitsupi how is that different from:

```
  -e USERID=$(id -u) \
  -e GROUPID=$(id -g) \
```

...which I'm already using?

**Comment by eitsupi** [comment]
There is no difference. I think that by setting them, additional behavior is occurring, causing a malfunction. Perhaps that means you shouldn't mount the bind under the home directory.

**Comment by benz0li** [comment]
@nick-youngblut How about using `/mnt` in the container, too? 

ℹ️ [Filesystem Hierarchy Standard > 3. The Root Filesystem > 3.12. /mnt : Mount point for a temporarily mounted filesystem](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s12.html)

What is the reason for explicitly mounting within `/home/rstudio`?

**Comment by nick-youngblut** [comment]
@benz0li that solution works. Thanks!

> What is the reason for explicitly mounting within

For users with less computational skills, presenting all mounted directories in `/home/rstudio` is easier for them than `/mnt`, which is not (easily) shown in the Rstudio file browser.

**Comment by eddelbuettel** [comment]
@nick-youngblut I think this has come up many times here before, so please feel free to search past issues.  When one runs RStudio it keeps state below $HOME which is in conflict with mounting that directory read-only.

**Comment by benz0li** [comment]
> For users with less computational skills, presenting all mounted directories in `/home/rstudio` is easier for them than `/mnt`, which is not (easily) shown in the Rstudio file browser.

@nick-youngblut You could conditionally symlink `~/mnt` to `/mnt` by adding something like

```bash
if [ "$(ls -A /mnt 2>/dev/null)" != "" ]; then
    runuser -u "${USER}" -g "$(id "${USER}" -g -n)" -- ln -snf /mnt "${USERHOME}"/mnt
fi
```

in [`scripts/init_userconf.sh`](https://github.com/rocker-org/rocker-versioned2/blob/cfe88aa25654edf9cbf620b478e9357887525f7a/scripts/init_userconf.sh).
