### ISSUE TITLE
rocker/shiny:4.0.2 can't start with user set to shiny

### ISSUE THREAD

**Issue by rasmusab** [rocker-org/rocker-versioned2#81]
According to [the readme for the rocker/shiny image](https://github.com/rocker-org/shiny/#warnings) it should be possible to start a contained with `--user shiny`. But when I try this with the latest release (`rocker/shiny:4.0.2`)...

```
bash> docker run --user shiny -p 3838:3838 --rm rocker/shiny:4.0.2
```

... the container doesn't start and I get the following error:

```
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

**Is it now recommended to run as root instead or is there now some other way to run as the shiny user?**

Running with `--user root` works as expected:

```
bash> docker run --user root -p 3838:3838 --rm rocker/shiny:4.0.2
```
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services

*** warning - no files are being watched ***
[services.d] done.
[2020-09-10T06:59:34.982] [INFO] shiny-server - Shiny Server v1.5.14.948 (Node.js v12.18.0)
[2020-09-10T06:59:34.986] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2020-09-10T06:59:35.034] [WARN] shiny-server - Running as root unnecessarily is a security risk! You could be running more securely as non-root.
[2020-09-10T06:59:35.041] [INFO] shiny-server - Starting listener on http://[::]:3838
```

### System info ###

This was done on a 2018 Macbook pro running MacOs Mojave (10.14.6) and Docker Desktop (2.3.0.4).

**Comment by KasperSkytte** [comment]
Having the same problem. I don't like the security implications of running services as root. And why is this necessary for hosting shiny apps?

**Comment by KasperSkytte** [comment]
Perhaps related, why is the `shiny` user running with uid/gid 999 and not 1000 or more?

**Comment by eitsupi** [comment]
This looks like an s6-overlay limitation. But, the latest version of S6 seems to be run by non-root users.
https://github.com/just-containers/s6-overlay#notes

I have confirmed that Shiny Server works with the following command.

```shell
$ docker run --rm -p 3838:3838 --user shiny -e S6_READ_ONLY_ROOT=1 rocker/shiny:4.1.1
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/shiny-server/run: Operation not permitted
exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by KasperSkytte** [comment]
@eitsupi Thanks. I see you still get an error from s6-init about the same permission issue, but now it returns exit code 0 and continues. Would that create other problems even though shiny-server starts correctly? Just tried that with a few of the more recent versions of R to narrow it down, seems like it's not an issue from `4.0.3` and onwards:

## `4.0.2`
```
$ docker run --rm -p 3838:3838 --user shiny -e S6_READ_ONLY_ROOT=1 rocker/shiny:4.0.2
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

## `4.0.3`
```
$ docker run --rm -p 3838:3838 --user shiny -e S6_READ_ONLY_ROOT=1 rocker/shiny:4.0.3
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/shiny-server/run: Operation not permitted
exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.

*** warning - no files are being watched ***
[2021-09-22T11:00:08.920] [INFO] shiny-server - Shiny Server v1.5.17.965 (Node.js v12.22.3)
[2021-09-22T11:00:08.922] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2021-09-22T11:00:08.960] [INFO] shiny-server - Starting listener on http://[::]:3838
```

**Comment by eitsupi** [comment]
I'm not familiar with s6-overlay, but it looks fine as I've been able to fix the permissions and finally start the service after the error occurred.

This feature cannot be used with `rocker/shiny:4.0.2` because the version of s6-overlay included in is old.
The version is specified on the Dockerfiles. 

https://github.com/rocker-org/rocker-versioned2/blob/d734a85bc8ef761797049eff9b4fccfa948f61e7/dockerfiles/shiny_4.0.2.Dockerfile#L8

https://github.com/rocker-org/rocker-versioned2/blob/d734a85bc8ef761797049eff9b4fccfa948f61e7/dockerfiles/shiny_4.0.3.Dockerfile#L8

@cboettig I think it's worth making the s6 version included in all images 2.1.0.2 or higher. Do you have any concerns?

**Comment by KasperSkytte** [comment]
Seems like the result is exactly the same whether I set `S6_READ_ONLY_ROOT=1` or not. Just has to be R `4.0.3` or later, due to the S6 version

**Comment by eitsupi** [comment]
Yeah, I misread the document! It seems that there is no need for options specific to execution as a non-root user.

```shell
$ docker run --rm -p 3838:3838 --user shiny rocker/shiny:4.1.1
```

**Comment by KasperSkytte** [comment]
Now another issue, but easily fixed. When accessing a shiny-app I get the following (running container as user `shiny`):

```
When accessing an app through the shiny-server I now get this error: 
[2021-09-22T11:27:57.528] [ERROR] shiny-server - User bookmark state directory creation failed: /var/lib/shiny-server/bookmarks/shiny
[2021-09-22T11:27:57.529] [WARN] shiny-server - ENOENT: no such file or directory, stat '/var/lib/shiny-server/bookmarks/shiny'
[2021-09-22T11:27:57.529] [INFO] shiny-server - Error getting worker: Error: The application exited during initialization.
```

Adding `RUN mkdir -p /var/lib/shiny-server/bookmarks/shiny` to the `Dockerfile` fixed it.

**Comment by cboettig** [comment]
@eitsupi nope, I'm fine bumping the S6 version.
