### ISSUE TITLE
Is install_tidyverse.sh broken?

### ISSUE THREAD

**Issue by harmongray** [rocker-org/rocker-versioned2#816]
### Container image name

rocker/rstudio:4.0.0

### Container image digest

rocker/rstudio:4.0.0@sha256:74d1ecbef956b65afab5d4f286bfeb3ce8ad2b9c7b417d98d9ab86983a

### System information

- OS: Debian 12 on x86_64 Linux 6.1.0-20-amd64
- Docker version 26.12, build 211e74b

### Question

I'm trying to use the predefined installation script modules in Docker. My Dockerfile currently fails at the second step:

```Dockerfile
FROM rocker/rstudio:4.0.0
RUN /rocker_scripts/install_tidyverse.sh
```

Looks like most of the core dependencies are failing:

```Bash
90.61 Reading package lists...
90.62 Building dependency tree...
90.62 Reading state information...
90.62 Package libssh2-1-dev is not available, but is referred to by another package.
90.62 This may mean that the package is missing, has been obsoleted, or
90.62 is only available from another source
90.62
90.62 E: Unable to locate package libxml2-dev
90.62 E: Unable to locate package libcairo2-dev
90.62 E: Unable to locate package libgit2-dev
90.62 E: Unable to locate package default-libmysqlclient-dev
90.62 E: Unable to locate package libpq-dev
90.62 E: Unable to locate package libsasl2-dev
90.62 E: Unable to locate package libsqlite3-dev
90.62 E: Package 'libssh2-1-dev' has no installation candidate
90.62 E: Unable to locate package libxtst6
90.62 E: Unable to locate package libharfbuzz-dev
90.62 E: Unable to locate package libfribidi-dev
90.62 E: Unable to locate package libfreetype6-dev
90.62 E: Unable to locate package libpng-dev
90.62 E: Unable to locate package libtiff5-dev
90.62 E: Unable to locate package unixodbc-dev
...

ERROR: failed to solve: process "/bin/sh -c /rocker_scripts/install_tidyverse.sh" did not complete successfully: exitcode: 100
```

I apologize if I'm just having a bit of PEBKAC moment, but can anyone give me some insight into whether this is a real issue or or or I am truly missing something?

Edit: I've tested this with `rocker/rstudio:4.4.0` down to `4.0.0` and the results don't vary. I'm just trying to use the method listed on the rocker-versioned2 readme.

**Comment by eitsupi** [comment]
What happens when you try the following?
Anyway, it would be worth checking if this is specific to that image or if it reproduces in alubuntu with the base image.

```dockerfile
FROM docker.io/library/ubuntu:jammy
RUN apt-get update && apt-get install libssh2-1-dev
```

**Comment by harmongray** [comment]
Hi! Thanks so much for responding - I was just about to post the source of the issue. Like I suspected: the problem in fact existed between the keyboard and the computer.

I'm using a Tailscale setup to run Rstudio remotely and access it on my local machine on the Tailscale VPN. Tailscale uses a custom DNS configuration (100.100.100.100) to do its magic, and as a result, makes `apt update` non-functional. Docker will inherit this - and I haven't been able to make `systemd-resolved` resolve the issue for me.

I'm still messing around with it, but the idea is to edit `/etc/resolv.conf` to use `8.8.8.8`, install the dependencies (which now works), and then add the previous Tailscale config back into `resolve.conf` to ensure I can access it on my local machine.

While I'm not sure of the best way to go about fixing it without manually messing with the configurations, but I can at least narrow it down to this specific cause and get Rstudio running with tidyverse as I desire.

**Comment by eitsupi** [comment]
> I'm still messing around with it, but the idea is to edit `/etc/resolv.conf` to use `8.8.8.8`, install the dependencies (which now works), and then add the previous Tailscale config back into `resolve.conf` to ensure I can access it on my local machine.

I think it would be better to ask that question to the Tailscale community.
There doesn't seem to be anything we can do here, so I will close.
