### ISSUE TITLE
Question/Feature request: Is there a way to tell install2.R to download packages in parallel?

### ISSUE THREAD

**Issue by winni2k** [rocker-org/rocker-versioned2#82]
Currently it takes me 140 seconds to download all the packages necessary for `treespace`. I think this would speed up my builds substantially? Is there something else I should be doing?

**Comment by eddelbuettel** [comment]
I thought about that too a few times and I do not think so as we simply dispatch to `install.packages()` which is serial.

Two suggestions though:
- if you are worried about build time, download is unlikely to be the binding constraint and I (_e.g._ for Travis or GH Actions) prefer to use precompiled packages; see my [recent blog post on BSPM vs RSPM](http://dirk.eddelbuettel.com/blog/2020/08/26#029_introducing_bspm). I plan to use that more for _e.g._ other container and CI
- look into `pak` by RStudio which explicitly downloads in parallel (I have not tried it)

**Comment by winni2k** [comment]
Thanks for the advice. I tried using `pak`, but that was unable to download some tars from the rstudio CRAN mirror. BSPM doesn't seem to work with the docker image I am using (`rocker/shiny-verse:4.0.2`).

In my case, `treespace` can be installed through `apt`, and that ends up being faster and simpler (using the `rocker/r-base:4.0.2`) image.

**Comment by eddelbuettel** [comment]
BSPM is very new. I have to setup some things myself for example CI use etc pp.  To deploy it you would / could / should start from its container which are set up:  `rocker/r-bspm:{18.04,20.04,testing}` depending on which Ubuntu or Debian flavour you want to build on.

**Comment by winni2k** [comment]
Nice! I'll try BSPM again then when I need a package that I can't get through apt.
