### ISSUE TITLE
s6-chown: fatal: unable to chown /var/run/s6/

### ISSUE THREAD

**Issue by csliangy** [rocker-org/rocker-versioned2#821]
### Container image name

rocker/shiny:4.4.0

### What operating system are you seeing the problem on?

Linux

### System information

- Docker version 24.0.5
- WSL version 0.2.1

### Bug description

In Dockerfile, use any non-root user, for example, add the following line: 
"USER shiny"

And the below error message will be observed: 

```
 [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
 s6-chown: fatal: unable to chown /var/run/s6/etc/cont-init.d/01_set_env: Operation not permitted
 s6-chmod: fatal: unable to change mode of /var/run/s6/etc/cont-init.d/01_set_env: Operation not permitted
 s6-chown: fatal: unable to chown /var/run/s6/etc/services.d/shiny-server/run: Operation not permitted
```

### How to reproduce this bug?

```sh
Create the following Dockerfile and run the container service:

------------------------------
FROM rocker/shiny:4.4.0

USER shiny

EXPOSE 3838

CMD ["/init"]
```

**Comment by eitsupi** [comment]
Could you please elaborate on what the problem?
I remember that this error message was an expected behavior and did not affect shiny-server's operation.

**Comment by epi-liang** [comment]
> Could you please elaborate on what the problem? I remember that this error message was an expected behavior and did not affect shiny-server's operation.

Yes, Shiny can run as expected. Just would like to know what is the impact of the s6 permission and can we safely ignore it?

**Comment by eitsupi** [comment]
> Just would like to know what is the impact of the s6 permission and can we safely ignore it?

I think what is happening is exactly what the message says. If not being able to chown those files is not a problem for you, why not just ignore these?
