### ISSUE TITLE
Github Copilot has been disabled by the administrator: Allow user to change?

### ISSUE THREAD

**Issue by ColinConwell** [rocker-org/rocker-versioned2#826]
### Container image name

rocker/ml_verse:latest

### What operating system related to this question?

Ubuntu 22.04.3 LTS

### Question

In Tools > Global Options... > CoPilot, it says:

GitHub CoPilot integration has been disabled by the administrator?

Is this a setting that can be easily changed?

It would be a major advantage to allow the user to sign-in and use CoPilot in rocker distributons.

Thanks in advance!

**Comment by eitsupi** [comment]
See <https://docs.posit.co/ide/user/ide/guide/tools/copilot.html#setup>

> With RStudio Server and Posit Workbench, GitHub Copilot must first be explicitly enabled by a system administrator. This can be done by adding the line:
>
> ```
> copilot-enabled=1
> ```
>
> to `/etc/rstudio/rsession.conf`.

I assume you can add this.
I don't see any possibility to enable this by default in this repository.

**Comment by ColinConwell** [comment]
A quick follow-up that this issue from RStudio suggests this is on RStudio's side:
https://github.com/rstudio/rstudio/issues/13612

Apparently, this setting can be overridden on the server by adding:
```copilot-enabled=1``` to ```rsession.conf```

Is that file constructed somewhere in the Dockerfile? or something that is easy to edit?

**Comment by eitsupi** [comment]
> Is that file constructed somewhere in the Dockerfile? or something that is easy to edit?

I don't think there's anything special here. It's just a default.

**Comment by benz0li** [comment]
@ColinConwell You may be interested in b-data's/my [JupyterLab R docker stack](https://github.com/b-data/jupyterlab-r-docker-stack):

1. [Provides RStudio Server OSE](https://github.com/b-data/jupyterlab-r-docker-stack/issues/4#issuecomment-2119888938) (images with R versions ≥ 4.4.0)
2. Has `copilot-enabled=1` set in [`etc/rstudio/rsession.conf`](https://github.com/b-data/jupyterlab-r-docker-stack/blob/117f315ec70b9c378b8d3b7c0d89ea6556e2f860/base/conf/rstudio/etc/rstudio/rsession.conf)
