### ISSUE TITLE
Add additional user

### ISSUE THREAD

**Issue by faisalmustafa** [rocker-org/rocker-versioned2#827]
### What operating system related to this question?

macOS

### Question

Hi,

I successfully run rstudio server  in docker using the following command on a silicon Mac.

docker run -d --name rstudio -v $HOME:/home/`whoami` -e PASSWORD=secret -p 8787:8787 rocker/rstudio

Is there a way to create more user to be able to start more than one session at the same time?

Thanks a lot for your help.

**Comment by eddelbuettel** [comment]
That is now Docker works. It is constrained by the user _but by the use port 8787_.  You can in fact run numerous instances of this but for the following ones you need to redirect their (inner, inside) port 8787 to ports, say, 8788, 8789, .. and so on the outside and connect the browser (on the outside) to those ports.

There should be a few tutorials around you may find with a bit of googling.  [Here is one answer](https://askubuntu.com/questions/1397652/run-two-instances-of-rstudio-server-via-docker), it also recommends separating the browsers (one normal, one private).  If you access from another computer than won't be an issue.

**Comment by faisalmustafa** [comment]
Thank you @eddelbuettel. That is extremely useful.
