### ISSUE TITLE
Issue installing alakazam

### ISSUE THREAD

**Issue by ramirobarrantes** [rocker-org/rocker-versioned2#833]
Not sure if this is the best place to ask ,but I have a simple docker recipe that uses rocker rstudio:

```
FROM rocker/rstudio:4.4

RUN install2.r -e rmarkdown ggplot2 kableExtra dplyr readxl stringr reshape2 httr BiocManager parallel

RUN R -e 'BiocManager::install(ask = F)'
RUN R -e 'BiocManager::install(c("biomaRt","XVector","Biostrings","GenomicAlignments","DECIPHER",ask = F))'

RUN install2.r -e alakazam

```

But when I try to build it: 

`docker build -t moonshot . --no-cache
`
It breaks in the last step, alakazam, it says:

`    ERROR: dependencies ‘Biostrings’, ‘GenomicAlignments’ are not available for package ‘alakazam’`

Any suggestions?

**Comment by eddelbuettel** [comment]
That usually means that your attempted installation was _unsuccessful_ so that loading of the (hence _not_ installed) library fails.  You will have to debug why it failed.

As an aside, rocker's [r2u](https://eddelbuettel.github.io/r2u/) has these as _binaries_ for Ubuntu and in a Docker container.

**Comment by ramirobarrantes** [comment]
Got it! As easy as not using the install2.r but rather good old fashioned install.packages()!!!

```
# Base R image
FROM rocker/rstudio:4.4

MAINTAINER Ramiro Barrantes <ramiro.barrantes@med.uvm.edu>

RUN install2.r -e rmarkdown ggplot2 kableExtra dplyr readxl stringr reshape2 httr BiocManager parallel

RUN R -e 'BiocManager::install(ask = F)'
RUN R -e 'BiocManager::install(c("biomaRt","XVector","Biostrings","GenomicAlignments","DECIPHER",ask = F))'

RUN R -e "install.packages('alakazam',dependencies=TRUE, repos='http://cran.rstudio.com/')"
```
