### ISSUE TITLE
Debian or Ubuntu ?!?

### ISSUE THREAD

**Issue by kcawley** [rocker-org/rocker-versioned2#85]
I am trying to sort out some OS-side dependencies for my Docker container, which uses both R and fortran code. From looking at the Docker files (FROM debian:testing) and documentation (https://github.com/rocker-org/rocker/wiki) it appears that these are based on Debian. However, the following command makes it clear that the containers are actually built on Ubuntu. Could you clarify which operating system should be used for the r-ver containers? I need to choose my fortran library differently based on which OS is being used.

docker run --entrypoint sh -it rocker/r-ver:4.0.2

Ubuntu 20.04 LTS \n \l

**Comment by cboettig** [comment]
@kcawley I think you're looking for https://github.com/rocker-org/rocker-versioned2#notes-on-new-architecture-for-r--400
As it says there, 4.x `r-ver`-based images moved from debian to ubuntu, for the reasons given there.  Older r-ver images remain unchanged (on debian-stable) and the official `r-base` image also remains unchanged (on debian-testing)
