### ISSUE TITLE
Why does the install_python.sh install script not provide `python` command?

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/rocker-versioned2#860]
### Container image name

rocker/geospatial

### What operating system related to this question?

Linux

### Question

I tried installing Python inside a Rocker container but found that the command

```
python
```

failed. See the test Dockerfile here: https://github.com/geocompx/docker/blob/8bdde78a1d9efcd66f194f37de74a5d5ed686649/rocker-r-py-julia/Dockerfile

And the cross-language project we're looking to support with an Docker container: https://github.com/Robinlovelace/cross_language_projects

**Comment by eddelbuettel** [comment]
Can you please try and see if `python3` works?  It is one of those backwards-compatibility things: until you install package `python-is-python3` the link to `python` may not exist.

**Comment by Robinlovelace** [comment]
> Can you please try and see if `python3` works? It is one of those backwards-compatibility things: until you install package `python-is-python3` the link to `python` may not exist.

Yes `python3` works.

**Comment by eddelbuettel** [comment]
So we have a possible bug report here that we should also install `python-is-python3` to cover this wart.

**Comment by eitsupi** [comment]
Perhaps the question has been answered, so may I close this?

I think users can install them if they need to.
There is no end to the debate about Python version selection, so I am skeptical of the idea that we should install anything other than the minimum required from the start.

If you really need it, I recommend that you install the version of your choice with [uv](https://github.com/astral-sh/uv) at the time of your choice.

**Comment by eitsupi** [comment]
There seems to be no particular comment, so I'll close it.

**Comment by cboettig** [comment]
I think these days python pushes us to create a venv for all installs, which `install_python.sh` already does, and places that on the PATH.  Creating a venv creates a `/opt/venv/bin` directory, which includes the symlinks for all this (i.e. python is python3.10 is python3 is python, and likewise the bindings for pip is pip3, etc).  This helps ensure users install python packages in the venv and don't break system packages.  


We can confirm:

```
docker run --rm -ti rocker/binder which python
/opt/venv/bin/python
```

so `python` does exist and importantly is the venv python (which is a symlink to the system python3).  

@Robinlovelace if you're not seeing this, it sounds like there may be some kind of PATH issue that also means you aren't accessing the venv but the /usr/python, which isn't ideal....    But I think we need more context to debug.

**Comment by cboettig** [comment]
Also more explicitly on the symlinks:

```
docker run --rm -ti rocker/binder ls -l /opt/venv/bin | grep python
-rwxr-xr-x 1 root staff  229 Sep 24 14:25 ipython
-rwxr-xr-x 1 root staff  229 Sep 24 14:25 ipython3
lrwxrwxrwx 1 root staff    7 Sep 24 14:25 python -> python3
lrwxrwxrwx 1 root staff   16 Sep 24 14:25 python3 -> /usr/bin/python3
lrwxrwxrwx 1 root staff    7 Sep 24 14:25 python3.10 -> python3
```

(aside but also note the staff permissions, a user in the staff group can write to the venv)

**Comment by Robinlovelace** [comment]
Thanks for the detailed response Carl, will aim to have a look and follow-up, may in a new issue on our issue tracker. Agreed, from what you said it seems that the things you do in `install_python.sh` should work well for our use case.

**Comment by Robinlovelace** [comment]
Hi guys and @cboettig in particular, sorry for going on about this but I'm *still* hitting issues with Python version. Current set-up is as [follows](https://github.com/geocompx/docker/blob/master/rocker-rpy/Dockerfile#L3-L15):

```
# Use Python already provisioned by the base image virtualenv (/opt/venv).
# Do not reinstall Python; ensure the venv python is preferred and 'python' exists.
RUN /rocker_scripts/install_python.sh


# Prefer the venv python and put its bin on PATH so reticulate picks it up.
ENV RETICULATE_PYTHON=/opt/venv/bin/python
ENV PATH=/opt/venv/bin:${PATH}


# Override the python symlink to use the venv Python (not system Python)
RUN ln -sf /opt/venv/bin/python /usr/bin/python


# Optionally install project requirements into the existing venv if desired:
RUN /opt/venv/bin/pip install -r https://github.com/geocompx/geocompy/raw/refs/heads/main/requirements.txt
```

The issue is that although `python --version` and `python pip` work fine in the default terminal, for some reason Quarto insists on choosing the system installation at `/usr/bin/python`

Reproducible example, click here: https://github.com/codespaces/new/itsleeds/tds?quickstart=1 and then try running the following test.qmd

    ```python
    x = 1
    ```

I have no idea how to configure Quarto to default to the correct version at `/opt/venv/bin/python` having read the Quarto docs: https://quarto.org/docs/computations/python.html#kernel-selection

**Comment by Robinlovelace** [comment]
Related issue: https://github.com/geocompx/docker/issues/107

Question: have you thought about starting with one of the Python docker containers and adding R on top?

I'm thinking of creating a `pythonr` image building on https://github.com/geocompx/docker/blob/master/python/Dockerfile but don't want to reinvent the wheel.

**Comment by eitsupi** [comment]
Again, use uv.

In my opinion that script is outdated and should be removed.

**Comment by Robinlovelace** [comment]
> Again, please use uv.

Great suggestion, will give it a spin. Should that also tackle the issues associated with multiple Python installations being available on the system and Quarto auto-picking the 'wrong' one?

**Comment by Robinlovelace** [comment]
Have opened a new issue here to track this experiment, happy to try to contribute a `python:` based image into this repo if that would be welcome.

**Comment by eitsupi** [comment]
I'm sorry, but I believe your posts are outside the scope of this repository. I am not your consultant.

I will not reply here any further, and I will remove `install_python.sh` in the future.

**Comment by cboettig** [comment]
Currently doing most geospatial  R + python stuff over in the Jupyterhub based containers, `rocker/binder` and `rocker/ml` .  `python` is of course available by default there and Jupyter provides a nice way to have options for different IDEs (e.g. jupyterlab, vscode, or rstudio interface).  These images use bspm so R binaries are pretty fast to install and system library dependencies should be auto-resolved.  

`rocker/binder` has the R spatial stack similar to `rocker/geospatial` (just as it did previously). https://github.com/rocker-org/binder

`rocker/cudal-spatial` has more python spatial packages, including things like cuda-accelerated cu-spatial https://github.com/rocker-org/ml

**Comment by Robinlovelace** [comment]
> I'm sorry, but I believe your posts are outside the scope of this repository. I am not your consultant.

I'm sorry if you find these messages annoy but there is no need for belittling statements like that. This is an open forum where we're all trying to learn and help each other, as far as I can tell. Thank you for your responses for far in any case and for the clarifications 🙏
