### ISSUE TITLE
Quarto version outdated

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/rocker-versioned2#861]
### Container image name

rocker/verse

### Container image digest

b29175c94220a8a27e0f701da8f04ef02d5372caf896c7fdbd4e66c59a4dad0d

### What operating system are you seeing the problem on?

Linux

### Bug description

```
quarto --version
1.4.555
```

This is too old to be used in popular IDEs such as VS Code: 

![image](https://github.com/user-attachments/assets/69a18371-c8e4-4ed3-b026-163b47b37bb5)

### How to reproduce this bug?

```sh
docker run -it rocker/verse bash
```
```

**Comment by Robinlovelace** [comment]
See issue reported, and fixed, downstream in geocompx/docker: https://github.com/geocompx/docker/issues/73

**Comment by Robinlovelace** [comment]
I tried to find where the default version or associated logic is stored but failed, e.g. with this search: repo:rocker-org/rocker-versioned2 1.4.555

Relevant line:

https://github.com/rocker-org/rocker-versioned2/blob/92aa18e44ceb43c62f666b659cb43412f59122de/scripts/install_quarto.sh#L17

Many thanks for making the install scripts take bash arguments, just realised that, used gratefully in the downstream fix: https://github.com/geocompx/docker/commit/f34ab5f13f7e64c580e22b6500a86c38e8846719

**Comment by eitsupi** [comment]
This is expected behavior for the version of Quarto bundled with RStudio.
If you want to install the latest version, specify “latest” and you should be able to do so.

**Comment by Robinlovelace** [comment]
Oh OK, thanks for the clarification. I assumed the latest version of RStudio would also need a later version. Sorry for the spam.

**Comment by eitsupi** [comment]
Never mind.
The strategy here is to keep Quarto CLI fixed and consistent in behavior, so it is just set to use the version bundled with RStudio.
