### ISSUE TITLE
Documentation: UID of user `rstudio` is now `1001`

### ISSUE THREAD

**Issue by cleemansen** [rocker-org/rocker-versioned2#875]
Hello, I upgraded from `rocker/geospatial:4.3.2` to `rocker/geospatial:4.4.2`. I noticed that the **UID** of the user `rstudio` is now `1001` and not anymore `1000`.

The documentation [managing users in docker](https://github.com/rocker-org/rocker/wiki/managing-users-in-docker) still mentions UID `1000` (should be: `1001`).

For reference (truncated):

```
rocker-org/rocker#7 [ 3/14] RUN getent passwd
rocker-org/rocker#7 0.148 root:x:0:0:root:/root:/bin/bash
rocker-org/rocker#7 0.148 ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
rocker-org/rocker#7 0.148 rstudio-server:x:997:997::/home/rstudio-server:/bin/sh
rocker-org/rocker#7 0.148 rstudio:x:1001:1001::/home/rstudio:/bin/bash
rocker-org/rocker#7 DONE 0.2s

```

**Comment by eitsupi** [comment]
Please use the the issue template.

If you are using the latest images, this problem should be resolved. See #871.

**Comment by eitsupi** [comment]
Don't worry about it. The problem was just fixed about 12 hours ago and I apologize for the confusion.
