### ISSUE TITLE
New image for Bayesian analysis?

### ISSUE THREAD

**Issue by jmgirard** [rocker-org/rocker-versioned2#876]
### What operating system related to this question?

Linux

### Question

I made a dockerfile and image for Bayesian analysis in R using Stan. Is there any possibility of getting this integrated into rocker officially?

https://github.com/jmgirard/rocker-bayes
https://hub.docker.com/r/jmgirard/rocker-bayes

**Comment by eddelbuettel** [comment]
Hi @jmgirard In general we cannot possibly consider a 'domain-specific container' for every domain that is active around R (see e.g. the several dozen CRAN Task Views).   Rather, the general idea is to provide good foundational layers upon which others can build their specialisations.  Just as you did here -- so I would encourage you to look after this container.  I hope this makes sense.

(As aside, also consider the rocker/r2u base layer and see e.g. [this demo](https://github.com/eddelbuettel/images/blob/master/2023-12-03/r2u_tidyverse_rstan_brms_33secs_2023-12-03_07-26.gif) of adding `rstan`, `brms` and `tidyverse` in thirtythree seconds -- in one command.)

**Comment by jmgirard** [comment]
That makes sense. Would you consider adding a page of links to such projects, so that at least people could see what's out there from a centralized location? Also, if r2u can support rstudio server, I would definitely switch to it.

**Comment by eddelbuettel** [comment]
Yes a page linking to derived projects would make sense.  Not sure what the best form would be -- a wiki page?  A small repo with a README containing links?  @eitsupi and @cboettig :  Any preferences or additional thoughts?

As for 'r2u plus rstudio': now we have recursion just like above.  Someone who wants to use rstudio (desktop or server) with r2u should layer it on top of rocker/r2u. My needs are met with the base layer.

**Comment by eitsupi** [comment]
Maybe this page?
https://rocker-project.org/images/external.html

**Comment by eddelbuettel** [comment]
As I said in my last comment there, this ought to be possible. rocker/r2u is Ubuntu, the provided .deb files install on Ubunu (in fact, on the machine I am typing this I have `rstudio`, `rstudio-server`, `positron`, `quarto` all installed from the PPA described / created [here](https://github.com/eddelbuettel/ppa-rstudio)).  So if one steps back there are three steps: [^1]

- start from rocker/r2u
- install the rstudio deb
- liberally borrow from rocker/rstudio whatever setup steps are needed along with the rstudio deb

AFAICT the issue you reference started on the wrong as it tried to invert the process and shoehorn r2u on top of the existing rocker/rstudio container which is not a great idea.  There are are some subtle differences, and thosse have been discussesd at length elsewhere.  But we should probably take that discussion over to the r2u repo rather than this.

[^1]: And as always, maybe I am overlooking something but this seems like a valid roadmap to me.

**Comment by eitsupi** [comment]
Thank you both. This doesn't seem to be an issue of this repo, so closing.

**Comment by jmgirard** [comment]
> As I said in my last comment there, this ought to be possible. rocker/r2u is Ubuntu, the provided .deb files install on Ubuntu (in fact, on the machine I am typing this I have `rstudio`, `rstudio-server`, `positron`, `quarto` all installed from the PPA described / created [here](https://github.com/eddelbuettel/ppa-rstudio)). So if one steps back there are three steps: [1](#user-content-fn-1-01526598163aa4da6a77601b1027dabd)
> 
> * start from rocker/r2u
> * install the rstudio deb (possibly a 'stable' release rather than a nightly but either should work)
> * liberally borrow from rocker/rstudio whatever setup steps are needed along with the rstudio deb
> 
> AFAICT the issue you reference started on the wrong as it tried to invert the process and shoehorn r2u on top of the existing rocker/rstudio container which is not a great idea. There are are some subtle differences, and those have been discussesd at length elsewhere. But we should probably take that discussion over to the r2u repo rather than this.
> 
> ## Footnotes
> 1. And as always, maybe I am overlooking something but this seems like a valid roadmap to me. [↩](#user-content-fnref-1-01526598163aa4da6a77601b1027dabd)

Just to close the loop here: I was able to get what you suggested to work: https://github.com/jmgirard/rstudio2u

**Comment by eddelbuettel** [comment]
Nice. I should probably document that over at the r2u site. You may be the "first derivative project".  So congratulations!

**Comment by jmgirard** [comment]
> Nice. I should probably document that over at the r2u site. You may be the "first derivative project". So congratulations!

It wasn't too hard. The main things were getting D-Hub on and the rstudio user the correct permissions.

**Comment by eddelbuettel** [comment]
Yes we also do it for an image internal to the [PrairieLearn testing/grading system](https://us.prairielearn.com/pl) but that is a little specialised (needs a PL user and then the rstudio user, I wasn't involved in the tweaking) but as it is all on top of Ubuntu it ... just works.

**Comment by eddelbuettel** [comment]
@jmgirard I added a new paragraph to the README (and hence website).  This is neat!
