### ISSUE TITLE
texlive-dummy not working

### ISSUE THREAD

**Issue by shug0131** [rocker-org/rocker-versioned2#883]
### Container image name

rocker/verse:latest

### What operating system related to this question?

Linux

### Question

Line 79 in /scripts/install_verse.sh

   wget "https://travis-bin.yihui.name/texlive-local.deb"

Is failing.  The web site is not in existence. 

Poking around I find https://github.com/yihui/travis-bin   suggests it is archived. 

I'm not clear why this step rather than just

apt-get install texlive

is used?  It mentions a "dummy" texlive, but not clear to me what this means or an alternative.

**Comment by benz0li** [comment]
Cross references:

* https://github.com/yihui/travis-bin/commit/687592b3f2e8e9aff322c2ac168295180e0ac39a#commitcomment-109192334
* https://github.com/b-data/jupyterlab-r-docker-stack/blob/296fe9d348dfc0b645d2ab7130eb7621f475f57c/verse/latest.Dockerfile#L86-L95

**Comment by shug0131** [comment]
The changes suggested above do work in my adapted version of rocker.
