### ISSUE TITLE
https://travis-bin.yihui.name/texlive-local.deb has moved to https://travis-bin.yihui.org/texlive-local.deb

### ISSUE THREAD

**Issue by nickforr** [rocker-org/rocker-versioned2#884]
In `install_verse.sh` the line linked below is failing with a 301 response noting that the link has changed.

https://github.com/rocker-org/rocker-versioned2/blob/02cd56d9fb5c414b792c4c80a12adab5b9712d43/scripts/install_verse.sh#L79C11-L79C58

**Comment by eitsupi** [comment]
Thanks for the report.
Could you send a PR to fix that?

**Comment by benz0li** [comment]
See also:

* https://github.com/rocker-org/rocker-versioned2/issues/883
