### ISSUE TITLE
How do I set UID and GID via Docker Compose?

### ISSUE THREAD

**Issue by emstruong** [rocker-org/rocker-versioned2#885]
### Container image name

rocker/verse:4.4.0

### Container image digest

N/A

### What operating system related to this question?

Linux

### System information

Docker version 27.4.0, build bde2b89; Docker Compose version v2.30.3-desktop.; Ubuntu 22.04

### Question

My files are under user ID 1001 and group ID 1001, but it seems like the default rstudio user ID and group id are both 1000. Is there a way to set rstudio to 1001? Via docker-compose?

**Comment by eitsupi** [comment]
See <https://rocker-project.org/images/versioned/rstudio.html#userid-and-groupid>
