### ISSUE TITLE
pandoc-citeproc in rocker-versioned2

### ISSUE THREAD

**Issue by peterdutey** [rocker-org/rocker-versioned2#94]
Hello

I use the following images in my continuous integration pipeline:
- rocker/shiny:3.6.2
- rocker/shiny:4.0.2

It was all working very smoothly, all the way until images I last built on 20 August.
Then I rebuilt my images on 10 October, pulling the latest version.
I could be incorrect but it seems to me that pandoc-citeproc stopped being installed in between.

`> docker run rocker/shiny:4.0.2 dpkg -l | grep  pandoc`
`ii  pandoc                             2.11.1-1                          amd64        general markup converter`

`> docker run rocker/shiny:3.6.2 dpkg -l | grep  pandoc`
`ii  libghc-pandoc-citeproc-data        0.14.3.1-4                   all          Pandoc support for Citation Style Language - data files`
`ii  pandoc                             2.2.1-3+b2                   amd64        general markup converter`
`ii  pandoc-citeproc                    0.14.3.1-4+b3                amd64        Pandoc support for Citation Style Language - tools`
`ii  pandoc-data                        2.2.1-3                      all          general markup converter - data files`

Since this is still in rocker/shiny:3.6.2 and that it was originally present (unless I'm incorrect) in shiny:4.0.2, I thought this might be unintentional. I can see that [scripts/install_pandoc.sh](https://github.com/rocker-org/rocker-versioned2/blob/b9cdf5fed928d5870698d173abf711a29b97025b/scripts/install_pandoc.sh#L21) is meant to install `pandoc-citeproc`.

Apologies if I missed something!
Many thanks
Peter

**Comment by eitsupi** [comment]
I am not familiar with pandoc, but it appears that pandoc at some point incorporated the functionality of pandoc-citeproc so that pandoc-citeproc no longer exists as a stand alone executable.
https://github.com/jgm/pandoc-citeproc
