### ISSUE TITLE
install_rstudio.sh breaks on aarch64 architecture (e.g. Raspberry Pi 4)

### ISSUE THREAD

**Issue by 0x326** [rocker-org/rocker-versioned2#98]
## Steps
```bash
# On an aarch64 CPU:
cd rocker-versioned2/
cd compose/
docker-compose -f core-4.0.3.yml build
```

## Expected output

A Docker image after a successful build.

## Actual output

```
dpkg: error processing archive rstudio-server-1.3.1093-amd64.deb (--install):                                                                                            
 package architecture (amd64) does not match system (arm64)                                                                                                              
Errors were encountered while processing:                                                                                                                                
 rstudio-server-1.3.1093-amd64.deb                                                                                                                                       
ERROR: Service 'rstudio-4.0.3' failed to build: The command '/bin/sh -c /rocker_scripts/install_rstudio.sh' returned a non-zero code: 1 
```

## Potential solution

Instead of downloading the pre-built amd64 binaries from <https://rstudio.com/products/rstudio/download-server/debian-ubuntu/>, we could compile RStudio server from source (as documented [here](https://github.com/rstudio/rstudio/blob/master/INSTALL)). It might look something like this:

```bash
git clone --recurse-submodules https://github.com/rstudio/rstudio.git -b v1.3.1093
cd rstudio/ || exit 1
mkdir build
cd build || exit 1
cmake .. -DRSTUDIO_TARGET=Server -DCMAKE_BUILD_TYPE=Release
make install
```

**Comment by eddelbuettel** [comment]
This has come up before. I think there is still no matching .deb package so the recipe cannot run.  Not within our reach to "just" create an RStudio .deb for your arch.  But as you outline, _you_ could build such a binary and then have _your_ run of the Dockerfile use it.

We are a little limited in just how many variation of Rocker we can support.  At times we have to rely on the community to fill in gaps.  I hope I can count on your understanding here.

**Comment by 0x326** [comment]
@eddelbuettel What if the `Dockerfile` builds from source always (instead of building and hosting a `.deb` file)?  Then we remain architecture-independent (at the cost of adding some time to the image creation).

**Comment by eddelbuettel** [comment]
There is no "if".  It's all up to you: "merely" create the .deb, place it in a network-reachable repo (PPAs come to mind) and have your Dockerfile read from and download from that repo.  You do not need us for this.

We made a strategic decision many years to _redistribute_ the .deb files produces by RStudio, with explicit permission by them, ensuring a user experience identical to direct download.  This is just not something that will change easily or overnight.   Many people (including inside Debian, where I also contribute) have looked into build RStudio from source; to the best of my knowledge not one of these attempts has come to fruition (for various reasons).  That should not stop you.  Build a better way, use it, and others (including us) may eventually follow.  Thanks for your understanding.
